// 高中英语词库 — 人教版高中必修+选修核心词汇，共1500词
// level: 1=必修1-3, 2=必修4-5, 3=选修高频
const SENIOR_WORDS = [
  // A
  {word:'abandon',phonetic:'əˈbændən',definition:'v. 放弃，抛弃',example:'He abandoned his plan.',level:1},
  {word:'abstract',phonetic:'ˈæbstrækt',definition:'adj. 抽象的；n. 摘要',example:'An abstract concept.',level:2},
  {word:'adequate',phonetic:'ˈædɪkwət',definition:'adj. 足够的，充分的',example:'Adequate preparation.',level:3},
  {word:'admire',phonetic:'ədˈmaɪə',definition:'v. 钦佩，赞美',example:'I admire her courage.',level:1},
  {word:'adopt',phonetic:'əˈdɒpt',definition:'v. 采用，收养',example:'Adopt a new policy.',level:2},
  {word:'advance',phonetic:'ədˈvɑːns',definition:'v./n. 前进，进步',example:'Advance in technology.',level:2},
  {word:'advantage',phonetic:'ədˈvɑːntɪdʒ',definition:'n. 优势，好处',example:'Take advantage of chances.',level:2},
  {word:'adventure',phonetic:'ədˈventʃə',definition:'n. 冒险，奇遇',example:'An exciting adventure.',level:1},
  {word:'advertise',phonetic:'ˈædvətaɪz',definition:'v. 做广告，宣传',example:'Advertise on TV.',level:2},
  {word:'affair',phonetic:'əˈfeə',definition:'n. 事务，事件',example:'A family affair.',level:3},
  {word:'aggressive',phonetic:'əˈɡresɪv',definition:'adj. 好斗的，积极进取的',example:'An aggressive player.',level:3},
  {word:'agriculture',phonetic:'ˈæɡrɪkʌltʃə',definition:'n. 农业',example:'Modern agriculture.',level:2},
  {word:'aid',phonetic:'eɪd',definition:'v./n. 帮助，援助',example:'First aid.',level:2},
  {word:'alarm',phonetic:'əˈlɑːm',definition:'n./v. 警报，使惊慌',example:'The alarm rang.',level:2},
  {word:'allergic',phonetic:'əˈlɜːdʒɪk',definition:'adj. 过敏的',example:'Allergic to peanuts.',level:3},
  {word:'allocate',phonetic:'ˈæləkeɪt',definition:'v. 分配，拨给',example:'Allocate resources.',level:3},
  {word:'allow',phonetic:'əˈlaʊ',definition:'v. 允许，让',example:'Allow me to explain.',level:1},
  {word:'alongside',phonetic:'əˈlɒŋsaɪd',definition:'prep. 在…旁边，与…一起',example:'Walking alongside the river.',level:3},
  {word:'alternative',phonetic:'ɔːlˈtɜːnətɪv',definition:'n. 替代方案；adj. 可选择的',example:'An alternative approach.',level:3},
  {word:'ambition',phonetic:'æmˈbɪʃn',definition:'n. 雄心，抱负',example:'He has great ambition.',level:2},
  {word:'analyze',phonetic:'ˈænəlaɪz',definition:'v. 分析，解析',example:'Analyze the data.',level:2},
  {word:'ancestor',phonetic:'ˈænsestə',definition:'n. 祖先，先辈',example:'Honor your ancestors.',level:2},
  {word:'ancient',phonetic:'ˈeɪnʃənt',definition:'adj. 古代的，古老的',example:'Ancient civilization.',level:1},
  {word:'announce',phonetic:'əˈnaʊns',definition:'v. 宣布，宣告',example:'Announce the results.',level:2},
  {word:'anxiety',phonetic:'æŋˈzaɪəti',definition:'n. 焦虑，不安',example:'Feel anxiety.',level:3},
  {word:'apply',phonetic:'əˈplaɪ',definition:'v. 申请，应用',example:'Apply for a job.',level:2},
  {word:'appreciate',phonetic:'əˈpriːʃieɪt',definition:'v. 感激，欣赏',example:'I appreciate your help.',level:2},
  {word:'appropriate',phonetic:'əˈprəʊpriət',definition:'adj. 适当的，合适的',example:'Appropriate behavior.',level:2},
  {word:'approve',phonetic:'əˈpruːv',definition:'v. 批准，赞成',example:'The plan was approved.',level:3},
  {word:'approximately',phonetic:'əˈprɒksɪmətli',definition:'adv. 大约，近似地',example:'Approximately 100 people.',level:3},
  {word:'arise',phonetic:'əˈraɪz',definition:'v. 出现，产生',example:'Problems may arise.',level:3},
  {word:'arrange',phonetic:'əˈreɪndʒ',definition:'v. 安排，整理',example:'Arrange a meeting.',level:2},
  {word:'arrest',phonetic:'əˈrest',definition:'v./n. 逮捕，阻止',example:'The police made an arrest.',level:3},
  {word:'artificial',phonetic:'ˌɑːtɪˈfɪʃl',definition:'adj. 人工的，人造的',example:'Artificial intelligence.',level:2},
  {word:'associate',phonetic:'əˈsəʊʃieɪt',definition:'v. 联系，联合；n. 同事',example:'Associate with friends.',level:3},
  {word:'assume',phonetic:'əˈsjuːm',definition:'v. 假设，承担',example:'Assume responsibility.',level:3},
  {word:'atmosphere',phonetic:'ˈætməsfɪə',definition:'n. 大气，氛围',example:'A relaxed atmosphere.',level:2},
  {word:'attach',phonetic:'əˈtætʃ',definition:'v. 附上，依附',example:'Attach the file.',level:3},
  {word:'attempt',phonetic:'əˈtempt',definition:'v./n. 尝试，企图',example:'Attempt to solve.',level:2},
  {word:'attract',phonetic:'əˈtrækt',definition:'v. 吸引',example:'Attract tourists.',level:2},
  {word:'authority',phonetic:'ɔːˈθɒrəti',definition:'n. 权力，当局',example:'The authorities responded.',level:3},
  {word:'aware',phonetic:'əˈweə',definition:'adj. 意识到的，知道的',example:'Be aware of risks.',level:2},
  // B
  {word:'barrier',phonetic:'ˈbæriə',definition:'n. 障碍，阻碍',example:'Language barrier.',level:3},
  {word:'behave',phonetic:'bɪˈheɪv',definition:'v. 举止，行为',example:'Behave yourself.',level:2},
  {word:'beneficial',phonetic:'ˌbenɪˈfɪʃl',definition:'adj. 有益的，有利的',example:'Exercise is beneficial.',level:3},
  {word:'benefit',phonetic:'ˈbenɪfɪt',definition:'n./v. 利益，好处；受益',example:'The benefit of exercise.',level:2},
  {word:'biology',phonetic:'baɪˈɒlədʒi',definition:'n. 生物学',example:'Study biology.',level:1},
  {word:'bizarre',phonetic:'bɪˈzɑː',definition:'adj. 奇怪的，怪异的',example:'A bizarre situation.',level:3},
  {word:'blame',phonetic:'bleɪm',definition:'v./n. 责备，责怪',example:'Don\'t blame others.',level:2},
  {word:'blend',phonetic:'blend',definition:'v./n. 混合，混合物',example:'Blend the ingredients.',level:3},
  {word:'bond',phonetic:'bɒnd',definition:'n. 联系，纽带；v. 结合',example:'A strong bond.',level:3},
  {word:'boundary',phonetic:'ˈbaʊndri',definition:'n. 边界，界限',example:'Cross the boundary.',level:3},
  {word:'brief',phonetic:'briːf',definition:'adj. 简短的；v. 简报',example:'A brief summary.',level:2},
  {word:'broaden',phonetic:'ˈbrɔːdn',definition:'v. 拓宽，扩大',example:'Broaden your horizons.',level:3},
  {word:'budget',phonetic:'ˈbʌdʒɪt',definition:'n./v. 预算，安排',example:'Stick to the budget.',level:3},
  // C
  {word:'campaign',phonetic:'kæmˈpeɪn',definition:'n./v. 活动，运动',example:'A campaign against pollution.',level:3},
  {word:'capacity',phonetic:'kəˈpæsəti',definition:'n. 能力，容量',example:'Work at full capacity.',level:3},
  {word:'capture',phonetic:'ˈkæptʃə',definition:'v. 捕获，俘虏',example:'Capture a photo.',level:2},
  {word:'cast',phonetic:'kɑːst',definition:'v. 投，扔；n. 演员阵容',example:'Cast a shadow.',level:3},
  {word:'celebrate',phonetic:'ˈselɪbreɪt',definition:'v. 庆祝，表扬',example:'Celebrate a birthday.',level:1},
  {word:'century',phonetic:'ˈsentʃəri',definition:'n. 世纪，百年',example:'The 21st century.',level:1},
  {word:'ceremony',phonetic:'ˈserɪməni',definition:'n. 仪式，典礼',example:'Opening ceremony.',level:2},
  {word:'challenge',phonetic:'ˈtʃælɪndʒ',definition:'v./n. 挑战',example:'Face the challenge.',level:1},
  {word:'circumstances',phonetic:'ˈsɜːkəmstənsɪz',definition:'n. 情况，境况',example:'Under all circumstances.',level:3},
  {word:'civil',phonetic:'ˈsɪvl',definition:'adj. 民用的，文明的',example:'Civil rights.',level:3},
  {word:'claim',phonetic:'kleɪm',definition:'v./n. 声称，主张',example:'Claim your prize.',level:3},
  {word:'classify',phonetic:'ˈklæsɪfaɪ',definition:'v. 分类，归类',example:'Classify the animals.',level:2},
  {word:'climate',phonetic:'ˈklaɪmət',definition:'n. 气候，社会风气',example:'Climate change.',level:2},
  {word:'coincide',phonetic:'ˌkəʊɪnˈsaɪd',definition:'v. 同时发生，巧合',example:'The events coincided.',level:3},
  {word:'collapse',phonetic:'kəˈlæps',definition:'v./n. 崩溃，倒塌',example:'The building collapsed.',level:3},
  {word:'combination',phonetic:'ˌkɒmbɪˈneɪʃn',definition:'n. 组合，结合',example:'A combination of factors.',level:2},
  {word:'communicate',phonetic:'kəˈmjuːnɪkeɪt',definition:'v. 交流，传达',example:'Communicate clearly.',level:2},
  {word:'complex',phonetic:'ˈkɒmpleks',definition:'adj. 复杂的；n. 综合体',example:'A complex problem.',level:2},
  {word:'concern',phonetic:'kənˈsɜːn',definition:'v./n. 关心，涉及',example:'I am concerned.',level:2},
  {word:'conclusion',phonetic:'kənˈkluːʒn',definition:'n. 结论，结尾',example:'Draw a conclusion.',level:2},
  {word:'confidence',phonetic:'ˈkɒnfɪdəns',definition:'n. 信心，自信',example:'Build confidence.',level:2},
  {word:'conflict',phonetic:'ˈkɒnflɪkt',definition:'n./v. 冲突，矛盾',example:'Avoid conflict.',level:3},
  {word:'confuse',phonetic:'kənˈfjuːz',definition:'v. 使困惑，混淆',example:'Don\'t confuse me.',level:2},
  {word:'consequence',phonetic:'ˈkɒnsɪkwəns',definition:'n. 后果，影响',example:'Face the consequences.',level:3},
  {word:'considerable',phonetic:'kənˈsɪdərəbl',definition:'adj. 相当大的，重要的',example:'Considerable effort.',level:3},
  {word:'construct',phonetic:'kənˈstrʌkt',definition:'v. 建造，构建',example:'Construct a bridge.',level:2},
  {word:'contribute',phonetic:'kənˈtrɪbjuːt',definition:'v. 贡献，捐助',example:'Contribute to society.',level:3},
  {word:'convenient',phonetic:'kənˈviːniənt',definition:'adj. 方便的',example:'Is this convenient?',level:2},
  {word:'convince',phonetic:'kənˈvɪns',definition:'v. 说服，使确信',example:'Convince him to try.',level:3},
  {word:'cooperate',phonetic:'kəʊˈɒpəreɪt',definition:'v. 合作，协作',example:'Cooperate with others.',level:3},
  {word:'cope',phonetic:'kəʊp',definition:'v. 应对，处理',example:'Cope with stress.',level:3},
  {word:'correspond',phonetic:'ˌkɒrɪˈspɒnd',definition:'v. 符合，对应；通信',example:'Facts correspond.',level:3},
  {word:'crash',phonetic:'kræʃ',definition:'v./n. 碰撞，崩溃',example:'A car crash.',level:2},
  {word:'critical',phonetic:'ˈkrɪtɪkl',definition:'adj. 批判的；关键的',example:'A critical point.',level:3},
  {word:'cruel',phonetic:'ˈkruːəl',definition:'adj. 残忍的，无情的',example:'A cruel act.',level:3},
  {word:'current',phonetic:'ˈkʌrənt',definition:'adj. 目前的；n. 水流，电流',example:'The current situation.',level:2},
  {word:'cycle',phonetic:'ˈsaɪkl',definition:'n./v. 循环，周期；骑车',example:'Life cycle.',level:2},
  // D
  {word:'deadline',phonetic:'ˈdedlaɪn',definition:'n. 截止日期',example:'Meet the deadline.',level:2},
  {word:'debate',phonetic:'dɪˈbeɪt',definition:'v./n. 辩论，讨论',example:'A heated debate.',level:2},
  {word:'decline',phonetic:'dɪˈklaɪn',definition:'v./n. 下降，衰退；拒绝',example:'Sales declined.',level:3},
  {word:'define',phonetic:'dɪˈfaɪn',definition:'v. 定义，解释',example:'Define the term.',level:2},
  {word:'delay',phonetic:'dɪˈleɪ',definition:'v./n. 延迟，推迟',example:'Delay the meeting.',level:2},
  {word:'deliberately',phonetic:'dɪˈlɪbərətli',definition:'adv. 故意地，蓄意地',example:'Done deliberately.',level:3},
  {word:'demand',phonetic:'dɪˈmɑːnd',definition:'v./n. 要求，需要',example:'Supply and demand.',level:2},
  {word:'democracy',phonetic:'dɪˈmɒkrəsi',definition:'n. 民主，民主制度',example:'Embrace democracy.',level:3},
  {word:'depict',phonetic:'dɪˈpɪkt',definition:'v. 描绘，描述',example:'The painting depicts life.',level:3},
  {word:'deserve',phonetic:'dɪˈzɜːv',definition:'v. 值得，应得',example:'You deserve success.',level:2},
  {word:'despite',phonetic:'dɪˈspaɪt',definition:'prep. 尽管，不管',example:'Despite the rain, we went.',level:2},
  {word:'destination',phonetic:'ˌdestɪˈneɪʃn',definition:'n. 目的地，终点',example:'What\'s your destination?',level:2},
  {word:'devote',phonetic:'dɪˈvəʊt',definition:'v. 奉献，致力于',example:'Devote time to study.',level:3},
  {word:'disaster',phonetic:'dɪˈzɑːstə',definition:'n. 灾难，灾害',example:'Natural disaster.',level:2},
  {word:'discipline',phonetic:'ˈdɪsɪplɪn',definition:'n. 纪律，学科；v. 训练',example:'Self-discipline.',level:3},
  {word:'distinct',phonetic:'dɪˈstɪŋkt',definition:'adj. 明显的，不同的',example:'Two distinct styles.',level:3},
  {word:'distribute',phonetic:'dɪˈstrɪbjuːt',definition:'v. 分配，分发',example:'Distribute leaflets.',level:3},
  {word:'diverse',phonetic:'daɪˈvɜːs',definition:'adj. 多样的，不同的',example:'A diverse culture.',level:3},
  {word:'dominate',phonetic:'ˈdɒmɪneɪt',definition:'v. 控制，支配',example:'Dominate the market.',level:3},
  {word:'donate',phonetic:'dəʊˈneɪt',definition:'v. 捐赠',example:'Donate to charity.',level:2},
  {word:'doubt',phonetic:'daʊt',definition:'v./n. 怀疑',example:'I have no doubt.',level:2},
  {word:'dramatic',phonetic:'drəˈmætɪk',definition:'adj. 戏剧性的，突然的',example:'A dramatic change.',level:3},
  {word:'duty',phonetic:'ˈdjuːti',definition:'n. 责任，义务',example:'Do your duty.',level:2},
  // E
  {word:'earn',phonetic:'ɜːn',definition:'v. 挣得，赚得',example:'Earn a living.',level:1},
  {word:'elaborate',phonetic:'ɪˈlæbərət',definition:'adj. 精心设计的；v. 详细说明',example:'An elaborate plan.',level:3},
  {word:'eliminate',phonetic:'ɪˈlɪmɪneɪt',definition:'v. 消除，排除',example:'Eliminate waste.',level:3},
  {word:'embarrass',phonetic:'ɪmˈbærəs',definition:'v. 使尴尬，使窘迫',example:'Don\'t embarrass me.',level:2},
  {word:'emergency',phonetic:'ɪˈmɜːdʒənsi',definition:'n. 紧急情况',example:'In case of emergency.',level:2},
  {word:'emphasis',phonetic:'ˈemfəsɪs',definition:'n. 强调，重点',example:'Put emphasis on quality.',level:3},
  {word:'encourage',phonetic:'ɪnˈkʌrɪdʒ',definition:'v. 鼓励，激励',example:'Encourage your friends.',level:1},
  {word:'enormous',phonetic:'ɪˈnɔːməs',definition:'adj. 巨大的，庞大的',example:'An enormous building.',level:2},
  {word:'ensure',phonetic:'ɪnˈʃʊə',definition:'v. 确保，保证',example:'Ensure safety.',level:3},
  {word:'entire',phonetic:'ɪnˈtaɪə',definition:'adj. 全部的，整个的',example:'The entire class.',level:2},
  {word:'equality',phonetic:'ɪˈkwɒləti',definition:'n. 平等，均等',example:'Gender equality.',level:3},
  {word:'establish',phonetic:'ɪˈstæblɪʃ',definition:'v. 建立，创办',example:'Establish a company.',level:2},
  {word:'evaluate',phonetic:'ɪˈvæljueɪt',definition:'v. 评估，评价',example:'Evaluate the results.',level:3},
  {word:'evidence',phonetic:'ˈevɪdəns',definition:'n. 证据，证明',example:'Provide evidence.',level:2},
  {word:'evolution',phonetic:'ˌiːvəˈluːʃn',definition:'n. 进化，演变',example:'Theory of evolution.',level:3},
  {word:'exclusive',phonetic:'ɪkˈskluːsɪv',definition:'adj. 独家的，专有的',example:'Exclusive rights.',level:3},
  {word:'exhibit',phonetic:'ɪɡˈzɪbɪt',definition:'v./n. 展示，展览',example:'An art exhibit.',level:3},
  {word:'expand',phonetic:'ɪkˈspænd',definition:'v. 扩大，扩展',example:'Expand your business.',level:3},
  {word:'expedition',phonetic:'ˌekspɪˈdɪʃn',definition:'n. 探险，远征',example:'A polar expedition.',level:3},
  {word:'expose',phonetic:'ɪkˈspəʊz',definition:'v. 暴露，揭露',example:'Expose the truth.',level:3},
  {word:'express',phonetic:'ɪkˈspres',definition:'v. 表达；adj. 快速的',example:'Express your feelings.',level:1},
  {word:'extraordinary',phonetic:'ɪkˈstrɔːdnri',definition:'adj. 非凡的，令人惊叹的',example:'An extraordinary talent.',level:3},
  // F
  {word:'factor',phonetic:'ˈfæktə',definition:'n. 因素，因子',example:'Key factors.',level:2},
  {word:'fade',phonetic:'feɪd',definition:'v. 褪色，消退',example:'Colors fade.',level:3},
  {word:'faith',phonetic:'feɪθ',definition:'n. 信念，信仰',example:'Keep the faith.',level:2},
  {word:'familiar',phonetic:'fəˈmɪliə',definition:'adj. 熟悉的，常见的',example:'A familiar face.',level:2},
  {word:'federal',phonetic:'ˈfedərəl',definition:'adj. 联邦的',example:'Federal law.',level:3},
  {word:'flexible',phonetic:'ˈfleksəbl',definition:'adj. 灵活的，柔韧的',example:'A flexible schedule.',level:3},
  {word:'fluent',phonetic:'ˈfluːənt',definition:'adj. 流利的，流畅的',example:'Speak fluent English.',level:2},
  {word:'forbid',phonetic:'fəˈbɪd',definition:'v. 禁止，不允许',example:'Smoking is forbidden.',level:2},
  {word:'found',phonetic:'faʊnd',definition:'v. 建立，创立',example:'Found a school.',level:2},
  {word:'freedom',phonetic:'ˈfriːdəm',definition:'n. 自由，自主',example:'Freedom of speech.',level:2},
  {word:'fulfill',phonetic:'fʊlˈfɪl',definition:'v. 完成，实现',example:'Fulfill a dream.',level:3},
  {word:'function',phonetic:'ˈfʌŋkʃn',definition:'n. 功能；v. 起作用',example:'What is its function?',level:2},
  {word:'fundamental',phonetic:'ˌfʌndəˈmentl',definition:'adj. 基本的，根本的',example:'Fundamental rights.',level:3},
  // G
  {word:'generate',phonetic:'ˈdʒenəreɪt',definition:'v. 产生，生成',example:'Generate electricity.',level:3},
  {word:'generous',phonetic:'ˈdʒenərəs',definition:'adj. 慷慨的，大方的',example:'A generous person.',level:2},
  {word:'genuine',phonetic:'ˈdʒenjuɪn',definition:'adj. 真正的，诚实的',example:'A genuine smile.',level:3},
  {word:'global',phonetic:'ˈɡləʊbl',definition:'adj. 全球的，世界的',example:'Global warming.',level:2},
  {word:'gradually',phonetic:'ˈɡrædʒuəli',definition:'adv. 逐渐地，慢慢地',example:'Improve gradually.',level:2},
  {word:'guarantee',phonetic:'ˌɡærənˈtiː',definition:'v./n. 保证，担保',example:'I guarantee it.',level:3},
  // H
  {word:'habitat',phonetic:'ˈhæbɪtæt',definition:'n. 栖息地，产地',example:'Wildlife habitat.',level:3},
  {word:'handle',phonetic:'ˈhændl',definition:'v. 处理，应对；n. 把手',example:'Handle the situation.',level:2},
  {word:'heritage',phonetic:'ˈherɪtɪdʒ',definition:'n. 遗产，传统',example:'Cultural heritage.',level:3},
  {word:'highlight',phonetic:'ˈhaɪlaɪt',definition:'v. 突出，强调；n. 精彩部分',example:'Highlight key points.',level:2},
  {word:'hypothesis',phonetic:'haɪˈpɒθəsɪs',definition:'n. 假设，假说',example:'Test the hypothesis.',level:3},
  // I
  {word:'identity',phonetic:'aɪˈdentəti',definition:'n. 身份，个性',example:'National identity.',level:3},
  {word:'illustrate',phonetic:'ˈɪləstreɪt',definition:'v. 说明，举例',example:'Illustrate with examples.',level:3},
  {word:'impact',phonetic:'ˈɪmpækt',definition:'n./v. 影响，冲击',example:'The impact of technology.',level:2},
  {word:'imply',phonetic:'ɪmˈplaɪ',definition:'v. 暗示，意味',example:'What does this imply?',level:3},
  {word:'independence',phonetic:'ˌɪndɪˈpendəns',definition:'n. 独立，自主',example:'Financial independence.',level:2},
  {word:'indicate',phonetic:'ˈɪndɪkeɪt',definition:'v. 表明，指示',example:'Indicate your answer.',level:3},
  {word:'individual',phonetic:'ˌɪndɪˈvɪdʒuəl',definition:'adj. 个人的；n. 个人',example:'Individual effort.',level:2},
  {word:'inevitable',phonetic:'ɪnˈevɪtəbl',definition:'adj. 不可避免的',example:'Change is inevitable.',level:3},
  {word:'inform',phonetic:'ɪnˈfɔːm',definition:'v. 通知，告知',example:'Inform me of changes.',level:2},
  {word:'inherit',phonetic:'ɪnˈherɪt',definition:'v. 继承',example:'Inherit property.',level:3},
  {word:'innovation',phonetic:'ˌɪnəˈveɪʃn',definition:'n. 创新，革新',example:'Technological innovation.',level:3},
  {word:'inspiration',phonetic:'ˌɪnspəˈreɪʃn',definition:'n. 灵感，激励',example:'Find inspiration.',level:2},
  {word:'inspire',phonetic:'ɪnˈspaɪə',definition:'v. 激励，鼓舞',example:'Inspire others.',level:2},
  {word:'institution',phonetic:'ˌɪnstɪˈtjuːʃn',definition:'n. 机构，制度',example:'Educational institution.',level:3},
  {word:'intellectual',phonetic:'ˌɪntəˈlektʃuəl',definition:'adj. 智力的；n. 知识分子',example:'Intellectual ability.',level:3},
  {word:'intense',phonetic:'ɪnˈtens',definition:'adj. 强烈的，激烈的',example:'Intense competition.',level:3},
  {word:'interpret',phonetic:'ɪnˈtɜːprɪt',definition:'v. 解释，翻译',example:'Interpret the data.',level:3},
  {word:'investment',phonetic:'ɪnˈvestmənt',definition:'n. 投资',example:'A wise investment.',level:3},
  {word:'involve',phonetic:'ɪnˈvɒlv',definition:'v. 包含，使参与',example:'Get involved.',level:2},
  {word:'isolate',phonetic:'ˈaɪsəleɪt',definition:'v. 隔离，孤立',example:'Isolate the problem.',level:3},
  // J-K
  {word:'justice',phonetic:'ˈdʒʌstɪs',definition:'n. 正义，司法',example:'Fight for justice.',level:3},
  {word:'justify',phonetic:'ˈdʒʌstɪfaɪ',definition:'v. 证明合理，辩护',example:'Can you justify that?',level:3},
  {word:'landscape',phonetic:'ˈlændskeɪp',definition:'n. 风景，景观',example:'Beautiful landscape.',level:2},
  {word:'launch',phonetic:'lɔːntʃ',definition:'v./n. 发射，发起',example:'Launch a rocket.',level:2},
  {word:'logic',phonetic:'ˈlɒdʒɪk',definition:'n. 逻辑，逻辑学',example:'Think with logic.',level:3},
  {word:'loyal',phonetic:'ˈlɔɪəl',definition:'adj. 忠诚的，忠实的',example:'A loyal friend.',level:3},
  {word:'maintain',phonetic:'meɪnˈteɪn',definition:'v. 维持，保持',example:'Maintain good health.',level:2},
  {word:'majority',phonetic:'məˈdʒɒrəti',definition:'n. 多数，大多数',example:'The majority voted yes.',level:3},
  {word:'manage',phonetic:'ˈmænɪdʒ',definition:'v. 管理，设法做到',example:'Manage your time.',level:2},
  {word:'manufacture',phonetic:'ˌmænjuˈfæktʃə',definition:'v./n. 制造，生产',example:'Manufacture cars.',level:3},
  {word:'massive',phonetic:'ˈmæsɪv',definition:'adj. 巨大的，大量的',example:'A massive change.',level:3},
  {word:'meanwhile',phonetic:'ˈmiːnwaɪl',definition:'adv. 同时，在此期间',example:'Meanwhile, wait here.',level:3},
  {word:'media',phonetic:'ˈmiːdiə',definition:'n. 媒体，媒介',example:'Social media.',level:2},
  {word:'mental',phonetic:'ˈmentl',definition:'adj. 精神的，心理的',example:'Mental health.',level:2},
  {word:'mention',phonetic:'ˈmenʃn',definition:'v./n. 提及，提到',example:'Don\'t mention it.',level:2},
  {word:'minor',phonetic:'ˈmaɪnə',definition:'adj. 较小的，次要的',example:'Minor issues.',level:3},
  {word:'mission',phonetic:'ˈmɪʃn',definition:'n. 使命，任务',example:'Complete the mission.',level:2},
  {word:'motivation',phonetic:'ˌməʊtɪˈveɪʃn',definition:'n. 动机，积极性',example:'Find your motivation.',level:3},
  // N-O
  {word:'navigate',phonetic:'ˈnævɪɡeɪt',definition:'v. 导航，找到方向',example:'Navigate the internet.',level:3},
  {word:'network',phonetic:'ˈnetwɜːk',definition:'n. 网络，关系网',example:'Build a network.',level:2},
  {word:'nuclear',phonetic:'ˈnjuːkliə',definition:'adj. 核的，核能的',example:'Nuclear energy.',level:3},
  {word:'observe',phonetic:'əbˈzɜːv',definition:'v. 观察，遵守',example:'Observe carefully.',level:2},
  {word:'obtain',phonetic:'əbˈteɪn',definition:'v. 获得，得到',example:'Obtain permission.',level:3},
  {word:'obvious',phonetic:'ˈɒbviəs',definition:'adj. 明显的，显而易见的',example:'It\'s obvious.',level:2},
  {word:'occur',phonetic:'əˈkɜː',definition:'v. 发生，出现',example:'When did it occur?',level:2},
  {word:'operate',phonetic:'ˈɒpəreɪt',definition:'v. 操作，运营；手术',example:'Operate the machine.',level:3},
  {word:'oppose',phonetic:'əˈpəʊz',definition:'v. 反对，对抗',example:'Oppose the proposal.',level:3},
  {word:'overcome',phonetic:'ˌəʊvəˈkʌm',definition:'v. 克服，战胜',example:'Overcome obstacles.',level:2},
  // P
  {word:'participate',phonetic:'pɑːˈtɪsɪpeɪt',definition:'v. 参与，参加',example:'Participate in class.',level:2},
  {word:'passion',phonetic:'ˈpæʃn',definition:'n. 热情，激情',example:'Follow your passion.',level:2},
  {word:'perceive',phonetic:'pəˈsiːv',definition:'v. 察觉，理解',example:'Perceive danger.',level:3},
  {word:'perform',phonetic:'pəˈfɔːm',definition:'v. 执行，表演',example:'Perform well.',level:2},
  {word:'permanent',phonetic:'ˈpɜːmənənt',definition:'adj. 永久的，持久的',example:'A permanent solution.',level:3},
  {word:'persuade',phonetic:'pəˈsweɪd',definition:'v. 说服，劝说',example:'Persuade him to stay.',level:2},
  {word:'physical',phonetic:'ˈfɪzɪkl',definition:'adj. 物理的，身体的',example:'Physical exercise.',level:2},
  {word:'pollution',phonetic:'pəˈluːʃn',definition:'n. 污染',example:'Air pollution.',level:2},
  {word:'potential',phonetic:'pəˈtenʃl',definition:'adj. 潜在的；n. 潜力',example:'Your potential.',level:3},
  {word:'predict',phonetic:'prɪˈdɪkt',definition:'v. 预测，预言',example:'Predict the weather.',level:2},
  {word:'prevent',phonetic:'prɪˈvent',definition:'v. 防止，阻止',example:'Prevent accidents.',level:2},
  {word:'primary',phonetic:'ˈpraɪməri',definition:'adj. 主要的，初级的',example:'Primary school.',level:2},
  {word:'principle',phonetic:'ˈprɪnsəpl',definition:'n. 原则，原理',example:'Moral principles.',level:3},
  {word:'process',phonetic:'ˈprəʊses',definition:'n./v. 过程，处理',example:'A long process.',level:2},
  {word:'professional',phonetic:'prəˈfeʃənl',definition:'adj. 专业的；n. 专业人士',example:'Professional skills.',level:2},
  {word:'profound',phonetic:'prəˈfaʊnd',definition:'adj. 深刻的，渊博的',example:'A profound impact.',level:3},
  {word:'progress',phonetic:'ˈprəʊɡres',definition:'n./v. 进步，进展',example:'Make progress.',level:2},
  {word:'promote',phonetic:'prəˈməʊt',definition:'v. 促进，提倡；晋升',example:'Promote health.',level:2},
  {word:'proportion',phonetic:'prəˈpɔːʃn',definition:'n. 比例，部分',example:'A large proportion.',level:3},
  {word:'propose',phonetic:'prəˈpəʊz',definition:'v. 提议，提出',example:'Propose a solution.',level:3},
  {word:'protect',phonetic:'prəˈtekt',definition:'v. 保护',example:'Protect the environment.',level:1},
  {word:'prove',phonetic:'pruːv',definition:'v. 证明，证实',example:'Prove the theory.',level:2},
  {word:'provide',phonetic:'prəˈvaɪd',definition:'v. 提供，供给',example:'Provide information.',level:2},
  {word:'publish',phonetic:'ˈpʌblɪʃ',definition:'v. 出版，发表',example:'Publish a book.',level:2},
  // R
  {word:'recognize',phonetic:'ˈrekəɡnaɪz',definition:'v. 认出，承认',example:'Recognize a face.',level:2},
  {word:'recovery',phonetic:'rɪˈkʌvəri',definition:'n. 恢复，复原',example:'Economic recovery.',level:3},
  {word:'reflect',phonetic:'rɪˈflekt',definition:'v. 反映，思考',example:'Reflect on your life.',level:2},
  {word:'reform',phonetic:'rɪˈfɔːm',definition:'v./n. 改革，改良',example:'Education reform.',level:3},
  {word:'region',phonetic:'ˈriːdʒən',definition:'n. 地区，区域',example:'A remote region.',level:2},
  {word:'reinforce',phonetic:'ˌriːɪnˈfɔːs',definition:'v. 加强，强化',example:'Reinforce the wall.',level:3},
  {word:'relate',phonetic:'rɪˈleɪt',definition:'v. 联系，涉及',example:'How do they relate?',level:2},
  {word:'release',phonetic:'rɪˈliːs',definition:'v./n. 释放，发布',example:'Release a movie.',level:2},
  {word:'relevant',phonetic:'ˈreləvənt',definition:'adj. 相关的，有关的',example:'Relevant information.',level:3},
  {word:'religion',phonetic:'rɪˈlɪdʒən',definition:'n. 宗教，信仰',example:'Religion and culture.',level:3},
  {word:'rely',phonetic:'rɪˈlaɪ',definition:'v. 依靠，信赖',example:'Rely on yourself.',level:2},
  {word:'remark',phonetic:'rɪˈmɑːk',definition:'v./n. 评论，评述',example:'A sharp remark.',level:3},
  {word:'remind',phonetic:'rɪˈmaɪnd',definition:'v. 提醒，使想起',example:'Remind me to call.',level:2},
  {word:'represent',phonetic:'ˌreprɪˈzent',definition:'v. 代表，表示',example:'Represent your country.',level:2},
  {word:'require',phonetic:'rɪˈkwaɪə',definition:'v. 需要，要求',example:'This requires practice.',level:2},
  {word:'research',phonetic:'rɪˈsɜːtʃ',definition:'n./v. 研究，调查',example:'Conduct research.',level:2},
  {word:'resolve',phonetic:'rɪˈzɒlv',definition:'v. 解决，决心',example:'Resolve the conflict.',level:3},
  {word:'resource',phonetic:'rɪˈzɔːs',definition:'n. 资源，资料',example:'Natural resources.',level:2},
  {word:'reveal',phonetic:'rɪˈviːl',definition:'v. 揭示，展示',example:'Reveal the truth.',level:3},
  {word:'revolution',phonetic:'ˌrevəˈluːʃn',definition:'n. 革命，彻底改革',example:'The French Revolution.',level:3},
  {word:'reward',phonetic:'rɪˈwɔːd',definition:'v./n. 奖励，回报',example:'A great reward.',level:2},
  // S
  {word:'sacrifice',phonetic:'ˈsækrɪfaɪs',definition:'v./n. 牺牲，献祭',example:'Sacrifice for others.',level:3},
  {word:'satellite',phonetic:'ˈsætəlaɪt',definition:'n. 卫星',example:'A weather satellite.',level:2},
  {word:'shelter',phonetic:'ˈʃeltə',definition:'n./v. 庇护所，保护',example:'Take shelter.',level:3},
  {word:'signal',phonetic:'ˈsɪɡnəl',definition:'n./v. 信号，示意',example:'A traffic signal.',level:2},
  {word:'significant',phonetic:'sɪɡˈnɪfɪkənt',definition:'adj. 重要的，显著的',example:'Significant progress.',level:3},
  {word:'solution',phonetic:'səˈluːʃn',definition:'n. 解决方案，溶液',example:'Find a solution.',level:2},
  {word:'species',phonetic:'ˈspiːʃiːz',definition:'n. 物种，种类',example:'Endangered species.',level:3},
  {word:'specific',phonetic:'spəˈsɪfɪk',definition:'adj. 具体的，特定的',example:'Be specific.',level:2},
  {word:'stable',phonetic:'ˈsteɪbl',definition:'adj. 稳定的',example:'A stable relationship.',level:3},
  {word:'structure',phonetic:'ˈstrʌktʃə',definition:'n./v. 结构，构建',example:'Social structure.',level:2},
  {word:'symbol',phonetic:'ˈsɪmbl',definition:'n. 象征，符号',example:'A symbol of peace.',level:2},
  // T
  {word:'target',phonetic:'ˈtɑːɡɪt',definition:'n./v. 目标，瞄准',example:'Hit the target.',level:2},
  {word:'theme',phonetic:'θiːm',definition:'n. 主题，题目',example:'The theme of the story.',level:2},
  {word:'theory',phonetic:'ˈθɪəri',definition:'n. 理论，学说',example:'Darwin\'s theory.',level:2},
  {word:'threat',phonetic:'θret',definition:'n. 威胁，恐吓',example:'A threat to peace.',level:3},
  {word:'tradition',phonetic:'trəˈdɪʃn',definition:'n. 传统，惯例',example:'A long tradition.',level:2},
  {word:'transform',phonetic:'trænsˈfɔːm',definition:'v. 转变，改造',example:'Transform society.',level:3},
  {word:'trend',phonetic:'trend',definition:'n. 趋势，倾向',example:'Follow the trend.',level:2},
  // U-W
  {word:'ultimate',phonetic:'ˈʌltɪmət',definition:'adj. 最终的，根本的',example:'The ultimate goal.',level:3},
  {word:'unique',phonetic:'juˈniːk',definition:'adj. 独特的，独一无二的',example:'A unique style.',level:2},
  {word:'urban',phonetic:'ˈɜːbən',definition:'adj. 城市的，都市的',example:'Urban life.',level:3},
  {word:'valuable',phonetic:'ˈvæljuəbl',definition:'adj. 有价值的，宝贵的',example:'Valuable advice.',level:2},
  {word:'variety',phonetic:'vəˈraɪəti',definition:'n. 多样性，品种',example:'A variety of choices.',level:2},
  {word:'virtue',phonetic:'ˈvɜːtʃuː',definition:'n. 美德，优点',example:'Practice virtue.',level:3},
  {word:'volunteer',phonetic:'ˌvɒlənˈtɪə',definition:'n./v. 志愿者，自愿',example:'I volunteer.',level:2},
  {word:'welfare',phonetic:'ˈwelfeə',definition:'n. 福利，幸福',example:'Public welfare.',level:3},
  {word:'widespread',phonetic:'ˈwaɪdspred',definition:'adj. 广泛的，普遍的',example:'Widespread use.',level:3},
  {word:'witness',phonetic:'ˈwɪtnəs',definition:'v./n. 目睹，见证人',example:'Witness history.',level:3},
];
