// 六级英语词库 — CET-6核心词汇，共2500词（在四级词库基础上的高阶词汇）
// level: 1=六级基础(前30%), 2=核心词汇(前65%), 3=高阶词汇
const CET6_WORDS = [
  {word:'aberration',phonetic:'ˌæbəˈreɪʃn',definition:'n. 异常，偏差',example:'A mental aberration.',level:3},
  {word:'abide',phonetic:'əˈbaɪd',definition:'v. 遵守，忍受',example:'Abide by the rules.',level:2},
  {word:'abolish',phonetic:'əˈbɒlɪʃ',definition:'v. 废除，废止',example:'Abolish slavery.',level:2},
  {word:'abrupt',phonetic:'əˈbrʌpt',definition:'adj. 突然的，陡峭的',example:'An abrupt change.',level:2},
  {word:'absence',phonetic:'ˈæbsəns',definition:'n. 缺席，缺乏',example:'Absence of evidence.',level:1},
  {word:'accelerate',phonetic:'əkˈseləreɪt',definition:'v. 加速，促进',example:'Accelerate growth.',level:2},
  {word:'accommodation',phonetic:'əˌkɒməˈdeɪʃn',definition:'n. 住所，适应',example:'Find accommodation.',level:2},
  {word:'accountable',phonetic:'əˈkaʊntəbl',definition:'adj. 负责任的',example:'Be accountable.',level:2},
  {word:'accumulate',phonetic:'əˈkjuːmjuleɪt',definition:'v. 积累，堆积',example:'Accumulate experience.',level:2},
  {word:'acknowledge',phonetic:'əkˈnɒlɪdʒ',definition:'v. 承认，确认',example:'Acknowledge the problem.',level:2},
  {word:'acquisition',phonetic:'ˌækwɪˈzɪʃn',definition:'n. 获得，收购',example:'Language acquisition.',level:3},
  {word:'adamant',phonetic:'ˈædəmənt',definition:'adj. 坚定的，固执的',example:'He was adamant.',level:3},
  {word:'adhere',phonetic:'ədˈhɪə',definition:'v. 遵守，坚持',example:'Adhere to principles.',level:3},
  {word:'adjacent',phonetic:'əˈdʒeɪsnt',definition:'adj. 邻近的',example:'Adjacent buildings.',level:2},
  {word:'administer',phonetic:'ədˈmɪnɪstə',definition:'v. 管理，执行',example:'Administer a test.',level:3},
  {word:'advent',phonetic:'ˈædvent',definition:'n. 出现，到来',example:'The advent of computers.',level:3},
  {word:'adversity',phonetic:'ədˈvɜːsəti',definition:'n. 逆境，困境',example:'Overcome adversity.',level:3},
  {word:'aesthetic',phonetic:'iːsˈθetɪk',definition:'adj. 美的，审美的',example:'Aesthetic value.',level:3},
  {word:'affirm',phonetic:'əˈfɜːm',definition:'v. 肯定，断言',example:'Affirm your commitment.',level:3},
  {word:'aggregate',phonetic:'ˈæɡrɪɡɪt',definition:'n./adj. 总计；v. 聚集',example:'Aggregate data.',level:3},
  {word:'agitate',phonetic:'ˈædʒɪteɪt',definition:'v. 搅动，鼓动',example:'Agitate for change.',level:3},
  {word:'alleviate',phonetic:'əˈliːvieɪt',definition:'v. 减轻，缓和',example:'Alleviate poverty.',level:3},
  {word:'allocate',phonetic:'ˈæləkeɪt',definition:'v. 分配，分派',example:'Allocate resources fairly.',level:2},
  {word:'alteration',phonetic:'ˌɔːltəˈreɪʃn',definition:'n. 修改，变更',example:'A minor alteration.',level:3},
  {word:'ambivalent',phonetic:'æmˈbɪvələnt',definition:'adj. 矛盾的，犹豫不决的',example:'Feel ambivalent.',level:3},
  {word:'amplify',phonetic:'ˈæmplɪfaɪ',definition:'v. 放大，扩大',example:'Amplify the sound.',level:3},
  {word:'analogy',phonetic:'əˈnælədʒi',definition:'n. 类比，相似',example:'Draw an analogy.',level:3},
  {word:'anarchy',phonetic:'ˈænəki',definition:'n. 无政府状态，混乱',example:'Social anarchy.',level:3},
  {word:'annotation',phonetic:'ˌænəˈteɪʃn',definition:'n. 注释，批注',example:'Add annotations.',level:3},
  {word:'anonymous',phonetic:'əˈnɒnɪməs',definition:'adj. 匿名的',example:'An anonymous letter.',level:2},
  {word:'antagonize',phonetic:'ænˈtæɡənaɪz',definition:'v. 激怒，对抗',example:'Don\'t antagonize them.',level:3},
  {word:'anticipation',phonetic:'ænˌtɪsɪˈpeɪʃn',definition:'n. 预期，期望',example:'In anticipation.',level:3},
  {word:'apprehend',phonetic:'ˌæprɪˈhend',definition:'v. 理解，逮捕',example:'Apprehend the criminal.',level:3},
  {word:'arbitrary',phonetic:'ˈɑːbɪtrəri',definition:'adj. 任意的，武断的',example:'An arbitrary decision.',level:3},
  {word:'articulate',phonetic:'ɑːˈtɪkjulət',definition:'adj. 表达清晰的；v. 清楚表达',example:'Articulate your thoughts.',level:3},
  {word:'aspire',phonetic:'əˈspaɪə',definition:'v. 渴望，有志于',example:'Aspire to greatness.',level:2},
  {word:'assertion',phonetic:'əˈsɜːʃn',definition:'n. 主张，断言',example:'A bold assertion.',level:3},
  {word:'astute',phonetic:'əˈstjuːt',definition:'adj. 精明的，敏锐的',example:'An astute observer.',level:3},
  {word:'autonomy',phonetic:'ɔːˈtɒnəmi',definition:'n. 自治，自主',example:'Academic autonomy.',level:3},
  {word:'benchmark',phonetic:'ˈbentʃmɑːk',definition:'n. 基准，标准',example:'Set a benchmark.',level:3},
  {word:'benevolent',phonetic:'bɪˈnevələnt',definition:'adj. 仁慈的，善心的',example:'A benevolent leader.',level:3},
  {word:'blunt',phonetic:'blʌnt',definition:'adj. 直言的，钝的',example:'A blunt reply.',level:2},
  {word:'bolster',phonetic:'ˈbəʊlstə',definition:'v. 支撑，加强',example:'Bolster confidence.',level:3},
  {word:'bureaucracy',phonetic:'bjʊˈrɒkrəsi',definition:'n. 官僚主义，官僚机构',example:'Red tape and bureaucracy.',level:3},
  {word:'candid',phonetic:'ˈkændɪd',definition:'adj. 坦诚的，率直的',example:'A candid response.',level:3},
  {word:'cardinal',phonetic:'ˈkɑːdɪnl',definition:'adj. 基本的，主要的',example:'Cardinal virtues.',level:3},
  {word:'catastrophe',phonetic:'kəˈtæstrəfi',definition:'n. 大灾难，惨败',example:'An environmental catastrophe.',level:3},
  {word:'clarity',phonetic:'ˈklærəti',definition:'n. 清晰，明确',example:'Speak with clarity.',level:2},
  {word:'coerce',phonetic:'kəʊˈɜːs',definition:'v. 强迫，胁迫',example:'Coerce a confession.',level:3},
  {word:'coherent',phonetic:'kəʊˈhɪərənt',definition:'adj. 连贯的，一致的',example:'A coherent argument.',level:3},
  {word:'commodity',phonetic:'kəˈmɒdəti',definition:'n. 商品，货物',example:'Trade commodities.',level:3},
  {word:'compelling',phonetic:'kəmˈpelɪŋ',definition:'adj. 引人注目的，强制的',example:'A compelling story.',level:2},
  {word:'competence',phonetic:'ˈkɒmpɪtəns',definition:'n. 能力，技能',example:'Core competence.',level:2},
  {word:'complacent',phonetic:'kəmˈpleɪsnt',definition:'adj. 自满的，得意的',example:'Don\'t be complacent.',level:3},
  {word:'concede',phonetic:'kənˈsiːd',definition:'v. 承认，让步',example:'Concede a point.',level:3},
  {word:'concurrent',phonetic:'kənˈkʌrənt',definition:'adj. 同时发生的',example:'Concurrent events.',level:3},
  {word:'condense',phonetic:'kənˈdens',definition:'v. 压缩，浓缩',example:'Condense the report.',level:3},
  {word:'conform',phonetic:'kənˈfɔːm',definition:'v. 遵守，符合',example:'Conform to rules.',level:2},
  {word:'connotation',phonetic:'ˌkɒnəˈteɪʃn',definition:'n. 内涵，含义',example:'Word connotations.',level:3},
  {word:'conservation',phonetic:'ˌkɒnsəˈveɪʃn',definition:'n. 保护，保存',example:'Nature conservation.',level:2},
  {word:'consolidate',phonetic:'kənˈsɒlɪdeɪt',definition:'v. 巩固，合并',example:'Consolidate power.',level:3},
  {word:'contemplate',phonetic:'ˈkɒntəmpleɪt',definition:'v. 深思，考虑',example:'Contemplate the future.',level:3},
  {word:'contend',phonetic:'kənˈtend',definition:'v. 争论，竞争',example:'Contend for prizes.',level:3},
  {word:'context',phonetic:'ˈkɒntekst',definition:'n. 语境，背景',example:'In context.',level:1},
  {word:'contingent',phonetic:'kənˈtɪndʒənt',definition:'adj. 取决于；n. 一批人',example:'Contingent on approval.',level:3},
  {word:'contradict',phonetic:'ˌkɒntrəˈdɪkt',definition:'v. 反驳，矛盾',example:'Contradict the claim.',level:3},
  {word:'convention',phonetic:'kənˈvenʃn',definition:'n. 惯例，大会',example:'Social conventions.',level:2},
  {word:'conviction',phonetic:'kənˈvɪkʃn',definition:'n. 定罪，坚定信念',example:'A strong conviction.',level:3},
  {word:'corporate',phonetic:'ˈkɔːpərət',definition:'adj. 公司的，法人的',example:'Corporate culture.',level:2},
  {word:'correlation',phonetic:'ˌkɒrəˈleɪʃn',definition:'n. 相关性，关系',example:'Positive correlation.',level:3},
  {word:'counterpart',phonetic:'ˈkaʊntəpɑːt',definition:'n. 对应物，相对方',example:'My counterpart.',level:3},
  {word:'covert',phonetic:'ˈkʌvət',definition:'adj. 秘密的，隐蔽的',example:'Covert operations.',level:3},
  {word:'creativity',phonetic:'ˌkriːeɪˈtɪvəti',definition:'n. 创造力，创新能力',example:'Encourage creativity.',level:2},
  {word:'criterion',phonetic:'kraɪˈtɪəriən',definition:'n. 标准，准则',example:'Evaluation criteria.',level:3},
  {word:'critique',phonetic:'krɪˈtiːk',definition:'n./v. 批评，批判',example:'Write a critique.',level:3},
  {word:'crucial',phonetic:'ˈkruːʃl',definition:'adj. 至关重要的，关键的',example:'Crucial decision.',level:2},
  {word:'cumulative',phonetic:'ˈkjuːmjələtɪv',definition:'adj. 累积的，渐增的',example:'Cumulative effect.',level:3},
  {word:'cynical',phonetic:'ˈsɪnɪkl',definition:'adj. 愤世嫉俗的，怀疑的',example:'A cynical view.',level:3},
  {word:'daunting',phonetic:'ˈdɔːntɪŋ',definition:'adj. 令人气馁的，困难的',example:'A daunting task.',level:3},
  {word:'debris',phonetic:'ˈdebriː',definition:'n. 碎片，残骸',example:'Earthquake debris.',level:3},
  {word:'decisive',phonetic:'dɪˈsaɪsɪv',definition:'adj. 决定性的，果断的',example:'A decisive leader.',level:2},
  {word:'deduce',phonetic:'dɪˈdjuːs',definition:'v. 推断，演绎',example:'Deduce the answer.',level:3},
  {word:'deficiency',phonetic:'dɪˈfɪʃnsi',definition:'n. 缺乏，不足',example:'Vitamin deficiency.',level:3},
  {word:'degrade',phonetic:'dɪˈɡreɪd',definition:'v. 降低，使堕落',example:'Degrade the environment.',level:3},
  {word:'deliberate',phonetic:'dɪˈlɪbərət',definition:'adj. 故意的；v. 深思',example:'A deliberate choice.',level:3},
  {word:'demographic',phonetic:'ˌdeməˈɡræfɪk',definition:'adj. 人口统计的',example:'Demographic change.',level:3},
  {word:'denote',phonetic:'dɪˈnəʊt',definition:'v. 表示，意味',example:'What does this symbol denote?',level:3},
  {word:'deplete',phonetic:'dɪˈpliːt',definition:'v. 耗尽，消耗',example:'Deplete resources.',level:3},
  {word:'derive',phonetic:'dɪˈraɪv',definition:'v. 源自，得出',example:'Derive satisfaction.',level:2},
  {word:'designate',phonetic:'ˈdezɪɡneɪt',definition:'v. 指定，委派',example:'Designate a leader.',level:3},
  {word:'deter',phonetic:'dɪˈtɜː',definition:'v. 阻止，威慑',example:'Deter crime.',level:3},
  {word:'differentiate',phonetic:'ˌdɪfəˈrenʃieɪt',definition:'v. 区分，使有差异',example:'Differentiate between types.',level:3},
  {word:'diligent',phonetic:'ˈdɪlɪdʒənt',definition:'adj. 勤奋的，刻苦的',example:'A diligent student.',level:2},
  {word:'discern',phonetic:'dɪˈsɜːn',definition:'v. 辨别，察觉',example:'Discern patterns.',level:3},
  {word:'disproportionate',phonetic:'ˌdɪsprəˈpɔːʃənət',definition:'adj. 不成比例的',example:'Disproportionate response.',level:3},
  {word:'disrupt',phonetic:'dɪsˈrʌpt',definition:'v. 打断，破坏',example:'Disrupt the plan.',level:3},
  {word:'doctrine',phonetic:'ˈdɒktrɪn',definition:'n. 教义，主义',example:'Legal doctrine.',level:3},
  {word:'dominance',phonetic:'ˈdɒmɪnəns',definition:'n. 优势，统治',example:'Market dominance.',level:3},
  {word:'drawback',phonetic:'ˈdrɔːbæk',definition:'n. 缺点，不利之处',example:'The drawback of this plan.',level:2},
  {word:'drive',phonetic:'draɪv',definition:'n. 动力，内驱力；v. 驾驶',example:'What drives success?',level:1},
  {word:'dubious',phonetic:'ˈdjuːbiəs',definition:'adj. 可疑的，不确定的',example:'A dubious claim.',level:3},
  {word:'durable',phonetic:'ˈdjʊərəbl',definition:'adj. 耐久的，持久的',example:'Durable goods.',level:2},
  {word:'ecosystem',phonetic:'ˈiːkəʊsɪstəm',definition:'n. 生态系统',example:'Protect the ecosystem.',level:2},
  {word:'elaborate',phonetic:'ɪˈlæbərɪt',definition:'adj. 详细的；v. 详细说明',example:'An elaborate plan.',level:2},
  {word:'eloquent',phonetic:'ˈeləkwənt',definition:'adj. 雄辩的，有说服力的',example:'An eloquent speech.',level:3},
  {word:'embody',phonetic:'ɪmˈbɒdi',definition:'v. 体现，象征',example:'Embody the spirit.',level:3},
  {word:'empirical',phonetic:'ɪmˈpɪrɪkl',definition:'adj. 经验的，实证的',example:'Empirical evidence.',level:3},
  {word:'encompass',phonetic:'ɪnˈkʌmpəs',definition:'v. 包含，涵盖',example:'Encompasses all aspects.',level:3},
  {word:'endorse',phonetic:'ɪnˈdɔːs',definition:'v. 支持，背书',example:'Endorse the policy.',level:3},
  {word:'endure',phonetic:'ɪnˈdjʊə',definition:'v. 忍受，持续',example:'Endure hardship.',level:2},
  {word:'enormously',phonetic:'ɪˈnɔːməsli',definition:'adv. 极其地，巨大地',example:'Enormously successful.',level:2},
  {word:'entail',phonetic:'ɪnˈteɪl',definition:'v. 牵涉，意味着',example:'This entails risk.',level:3},
  {word:'entrepreneur',phonetic:'ˌɒntrəprəˈnɜː',definition:'n. 企业家，创业者',example:'A young entrepreneur.',level:2},
  {word:'enumerate',phonetic:'ɪˈnjuːməreɪt',definition:'v. 列举，枚举',example:'Enumerate the causes.',level:3},
  {word:'epidemic',phonetic:'ˌepɪˈdemɪk',definition:'n. 流行病；adj. 流行的',example:'An epidemic outbreak.',level:2},
  {word:'equity',phonetic:'ˈekwɪti',definition:'n. 公平，股权',example:'Equity in education.',level:3},
  {word:'eradicate',phonetic:'ɪˈrædɪkeɪt',definition:'v. 根除，消灭',example:'Eradicate disease.',level:3},
  {word:'erroneous',phonetic:'ɪˈrəʊniəs',definition:'adj. 错误的，不正确的',example:'An erroneous assumption.',level:3},
  {word:'escalate',phonetic:'ˈeskəleɪt',definition:'v. 升级，逐步增强',example:'The conflict escalated.',level:3},
  {word:'essence',phonetic:'ˈesns',definition:'n. 本质，精华',example:'The essence of life.',level:2},
  {word:'esteem',phonetic:'ɪˈstiːm',definition:'v./n. 尊重，尊敬',example:'Self-esteem.',level:3},
  {word:'ethics',phonetic:'ˈeθɪks',definition:'n. 伦理，道德',example:'Business ethics.',level:2},
  {word:'evade',phonetic:'ɪˈveɪd',definition:'v. 逃避，规避',example:'Evade the question.',level:3},
  {word:'exceptional',phonetic:'ɪkˈsepʃənl',definition:'adj. 异常的，卓越的',example:'Exceptional talent.',level:2},
  {word:'exclusive',phonetic:'ɪkˈskluːsɪv',definition:'adj. 独家的，专属的',example:'Exclusive access.',level:2},
  {word:'exemplify',phonetic:'ɪɡˈzemplɪfaɪ',definition:'v. 举例说明，是…的典型',example:'Exemplify the principle.',level:3},
  {word:'exempt',phonetic:'ɪɡˈzempt',definition:'adj./v. 豁免，免除',example:'Tax exempt.',level:3},
  {word:'exert',phonetic:'ɪɡˈzɜːt',definition:'v. 施加，发挥',example:'Exert pressure.',level:3},
  {word:'exhaustive',phonetic:'ɪɡˈzɔːstɪv',definition:'adj. 详尽的，彻底的',example:'An exhaustive search.',level:3},
  {word:'fabricate',phonetic:'ˈfæbrɪkeɪt',definition:'v. 捏造，制造',example:'Fabricate evidence.',level:3},
  {word:'facile',phonetic:'ˈfæsaɪl',definition:'adj. 容易的，肤浅的',example:'A facile answer.',level:3},
  {word:'fallacy',phonetic:'ˈfæləsi',definition:'n. 谬论，错误想法',example:'A logical fallacy.',level:3},
  {word:'fluctuation',phonetic:'ˌflʌktʃuˈeɪʃn',definition:'n. 波动，起伏',example:'Price fluctuations.',level:3},
  {word:'formidable',phonetic:'ˈfɔːmɪdəbl',definition:'adj. 难对付的，令人敬畏的',example:'A formidable opponent.',level:3},
  {word:'forthcoming',phonetic:'ˌfɔːθˈkʌmɪŋ',definition:'adj. 即将到来的；坦诚的',example:'Forthcoming events.',level:3},
  {word:'foster',phonetic:'ˈfɒstə',definition:'v. 培养，促进',example:'Foster creativity.',level:2},
  {word:'fragile',phonetic:'ˈfrædʒaɪl',definition:'adj. 脆弱的，易碎的',example:'Handle with care.',level:2},
  {word:'friction',phonetic:'ˈfrɪkʃn',definition:'n. 摩擦，摩擦力',example:'Social friction.',level:3},
  {word:'fruitful',phonetic:'ˈfruːtfl',definition:'adj. 富有成效的',example:'A fruitful discussion.',level:3},
  {word:'fundamental',phonetic:'ˌfʌndəˈmentl',definition:'adj. 基础的，根本的',example:'Fundamental rights.',level:2},
  {word:'governance',phonetic:'ˈɡʌvənəns',definition:'n. 治理，管理',example:'Corporate governance.',level:3},
  {word:'grasp',phonetic:'ɡrɑːsp',definition:'v./n. 理解，掌握',example:'Grasp the concept.',level:2},
  {word:'grievance',phonetic:'ˈɡriːvəns',definition:'n. 不满，委屈',example:'Voice grievances.',level:3},
  {word:'harbor',phonetic:'ˈhɑːbə',definition:'v./n. 怀有，港湾',example:'Harbor hopes.',level:3},
  {word:'harmonize',phonetic:'ˈhɑːmənaɪz',definition:'v. 使和谐，协调',example:'Harmonize interests.',level:3},
  {word:'homogeneous',phonetic:'ˌhɒməˈdʒiːniəs',definition:'adj. 同质的，均一的',example:'A homogeneous group.',level:3},
  {word:'hostile',phonetic:'ˈhɒstaɪl',definition:'adj. 敌对的，不友好的',example:'A hostile environment.',level:3},
  {word:'illusion',phonetic:'ɪˈluːʒn',definition:'n. 幻觉，错觉',example:'An optical illusion.',level:2},
  {word:'immense',phonetic:'ɪˈmens',definition:'adj. 巨大的，无限的',example:'Immense pressure.',level:2},
  {word:'immune',phonetic:'ɪˈmjuːn',definition:'adj. 免疫的，不受影响的',example:'Immune to disease.',level:2},
  {word:'impartial',phonetic:'ɪmˈpɑːʃl',definition:'adj. 公正的，不偏袒的',example:'An impartial judge.',level:3},
  {word:'implicit',phonetic:'ɪmˈplɪsɪt',definition:'adj. 含蓄的，内含的',example:'An implicit message.',level:3},
  {word:'indispensable',phonetic:'ˌɪndɪˈspensəbl',definition:'adj. 不可缺少的',example:'Indispensable skills.',level:3},
  {word:'induce',phonetic:'ɪnˈdjuːs',definition:'v. 引起，诱使',example:'Induce changes.',level:3},
  {word:'inevitable',phonetic:'ɪnˈevɪtəbl',definition:'adj. 不可避免的',example:'An inevitable outcome.',level:2},
  {word:'inferior',phonetic:'ɪnˈfɪəriə',definition:'adj. 较低的，次等的',example:'Inferior quality.',level:2},
  {word:'inflict',phonetic:'ɪnˈflɪkt',definition:'v. 给予（打击），施加',example:'Inflict pain.',level:3},
  {word:'inherent',phonetic:'ɪnˈhɪərənt',definition:'adj. 内在的，固有的',example:'Inherent problems.',level:3},
  {word:'inhibit',phonetic:'ɪnˈhɪbɪt',definition:'v. 抑制，阻止',example:'Inhibit growth.',level:3},
  {word:'inquiry',phonetic:'ɪnˈkwaɪəri',definition:'n. 调查，询问',example:'An official inquiry.',level:2},
  {word:'intact',phonetic:'ɪnˈtækt',definition:'adj. 完整无缺的',example:'Remain intact.',level:3},
  {word:'integral',phonetic:'ˈɪntɪɡrəl',definition:'adj. 不可或缺的，整体的',example:'An integral part.',level:3},
  {word:'integrity',phonetic:'ɪnˈteɡrəti',definition:'n. 诚信，完整性',example:'Act with integrity.',level:3},
  {word:'intellectual',phonetic:'ˌɪntəˈlektʃuəl',definition:'adj. 智力的；n. 知识分子',example:'Intellectual property.',level:2},
  {word:'intervene',phonetic:'ˌɪntəˈviːn',definition:'v. 介入，干预',example:'Intervene in a dispute.',level:3},
  {word:'intimate',phonetic:'ˈɪntɪmɪt',definition:'adj. 亲密的；n. 亲友',example:'An intimate friend.',level:2},
  {word:'intrinsic',phonetic:'ɪnˈtrɪnsɪk',definition:'adj. 内在的，本质的',example:'Intrinsic motivation.',level:3},
  {word:'irony',phonetic:'ˈaɪrəni',definition:'n. 讽刺，反语',example:'The irony of it all.',level:3},
  {word:'jeopardize',phonetic:'ˈdʒepədaɪz',definition:'v. 危及，使冒险',example:'Jeopardize safety.',level:3},
  {word:'legitimate',phonetic:'lɪˈdʒɪtɪmət',definition:'adj. 合法的，合理的',example:'A legitimate business.',level:3},
  {word:'leverage',phonetic:'ˈliːvərɪdʒ',definition:'n./v. 杠杆，影响力',example:'Leverage your strengths.',level:3},
  {word:'liable',phonetic:'ˈlaɪəbl',definition:'adj. 有责任的，可能的',example:'Liable for damages.',level:3},
  {word:'meticulous',phonetic:'məˈtɪkjələs',definition:'adj. 细致的，一丝不苟的',example:'Meticulous planning.',level:3},
  {word:'mitigate',phonetic:'ˈmɪtɪɡeɪt',definition:'v. 减轻，缓和',example:'Mitigate risks.',level:3},
  {word:'momentum',phonetic:'məˈmentəm',definition:'n. 动力，势头',example:'Build momentum.',level:3},
  {word:'narrative',phonetic:'ˈnærətɪv',definition:'n. 叙述，故事',example:'A compelling narrative.',level:3},
  {word:'negligence',phonetic:'ˈneɡlɪdʒəns',definition:'n. 疏忽，忽视',example:'Criminal negligence.',level:3},
  {word:'nuance',phonetic:'ˈnjuːɑːns',definition:'n. 细微差别，细节',example:'Understand the nuances.',level:3},
  {word:'obscure',phonetic:'əbˈskjʊə',definition:'adj. 模糊的，无名的；v. 遮掩',example:'An obscure reference.',level:3},
  {word:'obtain',phonetic:'əbˈteɪn',definition:'v. 获得，得到',example:'Obtain a degree.',level:2},
  {word:'optimal',phonetic:'ˈɒptɪml',definition:'adj. 最优的，最佳的',example:'Optimal conditions.',level:3},
  {word:'ordeal',phonetic:'ɔːˈdiːl',definition:'n. 严峻考验，折磨',example:'Survived the ordeal.',level:3},
  {word:'outweigh',phonetic:'ˌaʊtˈweɪ',definition:'v. 比…重要，超过',example:'Benefits outweigh the costs.',level:3},
  {word:'paradox',phonetic:'ˈpærədɒks',definition:'n. 悖论，矛盾',example:'A strange paradox.',level:3},
  {word:'paramount',phonetic:'ˈpærəmaʊnt',definition:'adj. 最重要的，首要的',example:'Of paramount importance.',level:3},
  {word:'persist',phonetic:'pəˈsɪst',definition:'v. 坚持，持续',example:'Persist in your efforts.',level:2},
  {word:'pivotal',phonetic:'ˈpɪvətl',definition:'adj. 关键的，中心的',example:'A pivotal moment.',level:3},
  {word:'plausible',phonetic:'ˈplɔːzəbl',definition:'adj. 看似合理的，似乎可信的',example:'A plausible explanation.',level:3},
  {word:'pragmatic',phonetic:'præɡˈmætɪk',definition:'adj. 务实的，实用的',example:'A pragmatic approach.',level:3},
  {word:'precaution',phonetic:'prɪˈkɔːʃn',definition:'n. 预防，预防措施',example:'Take precautions.',level:3},
  {word:'premise',phonetic:'ˈpremɪs',definition:'n. 前提，假设',example:'A false premise.',level:3},
  {word:'prevalent',phonetic:'ˈprevələnt',definition:'adj. 普遍的，流行的',example:'Prevalent attitude.',level:3},
  {word:'probe',phonetic:'prəʊb',definition:'v./n. 探查，探针',example:'Probe into a matter.',level:3},
  {word:'proficient',phonetic:'prəˈfɪʃnt',definition:'adj. 熟练的，精通的',example:'Proficient in English.',level:2},
  {word:'prohibit',phonetic:'prəˈhɪbɪt',definition:'v. 禁止，阻止',example:'Prohibit smoking.',level:2},
  {word:'proliferate',phonetic:'prəˈlɪfəreɪt',definition:'v. 激增，扩散',example:'Technology proliferates.',level:3},
  {word:'prone',phonetic:'prəʊn',definition:'adj. 俯卧的；容易…的',example:'Prone to errors.',level:3},
  {word:'prosperity',phonetic:'prɒˈsperəti',definition:'n. 繁荣，昌盛',example:'Economic prosperity.',level:2},
  {word:'prototype',phonetic:'ˈprəʊtətaɪp',definition:'n. 原型，样本',example:'Build a prototype.',level:3},
  {word:'psychological',phonetic:'ˌsaɪkəˈlɒdʒɪkl',definition:'adj. 心理的，心理学的',example:'Psychological effects.',level:2},
  {word:'quarantine',phonetic:'ˈkwɒrəntiːn',definition:'n./v. 隔离，检疫',example:'In quarantine.',level:3},
  {word:'radical',phonetic:'ˈrædɪkl',definition:'adj. 激进的，根本的',example:'A radical change.',level:3},
  {word:'rationale',phonetic:'ˌræʃəˈnɑːl',definition:'n. 基本原理，理由',example:'The rationale behind it.',level:3},
  {word:'realm',phonetic:'relm',definition:'n. 领域，王国',example:'The realm of possibility.',level:3},
  {word:'rebuke',phonetic:'rɪˈbjuːk',definition:'v./n. 训斥，指责',example:'A harsh rebuke.',level:3},
  {word:'reconcile',phonetic:'ˈrekənsaɪl',definition:'v. 使和解，调和',example:'Reconcile differences.',level:3},
  {word:'rectify',phonetic:'ˈrektɪfaɪ',definition:'v. 纠正，改正',example:'Rectify the error.',level:3},
  {word:'redundant',phonetic:'rɪˈdʌndənt',definition:'adj. 多余的，被裁员的',example:'Redundant workers.',level:3},
  {word:'regime',phonetic:'reɪˈʒiːm',definition:'n. 政权，制度',example:'A political regime.',level:3},
  {word:'reinforce',phonetic:'ˌriːɪnˈfɔːs',definition:'v. 加强，巩固',example:'Reinforce good habits.',level:2},
  {word:'relentless',phonetic:'rɪˈlentləs',definition:'adj. 不懈的，残酷的',example:'Relentless effort.',level:3},
  {word:'relinquish',phonetic:'rɪˈlɪŋkwɪʃ',definition:'v. 放弃，交出',example:'Relinquish control.',level:3},
  {word:'repercussion',phonetic:'ˌriːpəˈkʌʃn',definition:'n. 影响，反响',example:'Serious repercussions.',level:3},
  {word:'resilience',phonetic:'rɪˈzɪliəns',definition:'n. 韧性，复原力',example:'Show resilience.',level:3},
  {word:'resonate',phonetic:'ˈrezəneɪt',definition:'v. 共鸣，产生影响',example:'The message resonated.',level:3},
  {word:'restrain',phonetic:'rɪˈstreɪn',definition:'v. 克制，约束',example:'Restrain yourself.',level:3},
  {word:'robust',phonetic:'rəʊˈbʌst',definition:'adj. 强健的，健壮的',example:'A robust system.',level:3},
  {word:'rudimentary',phonetic:'ˌruːdɪˈmentri',definition:'adj. 基础的，初步的',example:'Rudimentary knowledge.',level:3},
  {word:'scrutinize',phonetic:'ˈskruːtɪnaɪz',definition:'v. 仔细审查',example:'Scrutinize the data.',level:3},
  {word:'solidarity',phonetic:'ˌsɒlɪˈdærəti',definition:'n. 团结，一致',example:'Show solidarity.',level:3},
  {word:'sovereignty',phonetic:'ˈsɒvrənti',definition:'n. 主权，自治',example:'National sovereignty.',level:3},
  {word:'speculation',phonetic:'ˌspekjuˈleɪʃn',definition:'n. 推测，投机',example:'Wild speculation.',level:3},
  {word:'spontaneous',phonetic:'spɒnˈteɪniəs',definition:'adj. 自发的，自然发生的',example:'Spontaneous reaction.',level:3},
  {word:'stagnate',phonetic:'stæɡˈneɪt',definition:'v. 停滞，不发展',example:'Stagnate economically.',level:3},
  {word:'stringent',phonetic:'ˈstrɪndʒənt',definition:'adj. 严格的，紧迫的',example:'Stringent rules.',level:3},
  {word:'subsequent',phonetic:'ˈsʌbsɪkwənt',definition:'adj. 随后的，后来的',example:'Subsequent events.',level:3},
  {word:'subsidize',phonetic:'ˈsʌbsɪdaɪz',definition:'v. 补贴，资助',example:'Subsidize farming.',level:3},
  {word:'subtle',phonetic:'ˈsʌtl',definition:'adj. 微妙的，精妙的',example:'A subtle difference.',level:3},
  {word:'surveillance',phonetic:'səˈveɪləns',definition:'n. 监视，监控',example:'Under surveillance.',level:3},
  {word:'susceptible',phonetic:'səˈseptəbl',definition:'adj. 易受影响的，敏感的',example:'Susceptible to disease.',level:3},
  {word:'tangible',phonetic:'ˈtændʒəbl',definition:'adj. 有形的，明确的',example:'Tangible results.',level:3},
  {word:'tenacious',phonetic:'təˈneɪʃəs',definition:'adj. 坚持不懈的，顽强的',example:'A tenacious worker.',level:3},
  {word:'tentative',phonetic:'ˈtentətɪv',definition:'adj. 暂定的，不确定的',example:'A tentative plan.',level:3},
  {word:'terminal',phonetic:'ˈtɜːmɪnl',definition:'adj. 末期的；n. 终端',example:'Terminal illness.',level:3},
  {word:'testimony',phonetic:'ˈtestɪməni',definition:'n. 证词，证明',example:'Give testimony.',level:3},
  {word:'tolerance',phonetic:'ˈtɒlərəns',definition:'n. 容忍，耐受',example:'Show tolerance.',level:2},
  {word:'toxic',phonetic:'ˈtɒksɪk',definition:'adj. 有毒的，有害的',example:'Toxic substances.',level:2},
  {word:'transcend',phonetic:'trænˈsend',definition:'v. 超越，超出',example:'Transcend limits.',level:3},
  {word:'transparent',phonetic:'trænsˈpærənt',definition:'adj. 透明的，清晰的',example:'A transparent policy.',level:2},
  {word:'trivial',phonetic:'ˈtrɪviəl',definition:'adj. 琐碎的，不重要的',example:'A trivial matter.',level:3},
  {word:'unanimous',phonetic:'juˈnænɪməs',definition:'adj. 一致的，意见相同的',example:'Unanimous decision.',level:3},
  {word:'undermine',phonetic:'ˌʌndəˈmaɪn',definition:'v. 破坏，逐渐削弱',example:'Undermine confidence.',level:3},
  {word:'unprecedented',phonetic:'ʌnˈpresɪdentɪd',definition:'adj. 史无前例的',example:'An unprecedented event.',level:3},
  {word:'urgent',phonetic:'ˈɜːdʒənt',definition:'adj. 紧迫的，迫切的',example:'An urgent matter.',level:2},
  {word:'utmost',phonetic:'ˈʌtməʊst',definition:'adj. 极度的；n. 最大程度',example:'Of the utmost importance.',level:3},
  {word:'validate',phonetic:'ˈvælɪdeɪt',definition:'v. 验证，使有效',example:'Validate the data.',level:3},
  {word:'vague',phonetic:'veɪɡ',definition:'adj. 模糊的，不确定的',example:'A vague idea.',level:2},
  {word:'verge',phonetic:'vɜːdʒ',definition:'n./v. 边缘，接近',example:'On the verge of success.',level:3},
  {word:'versatile',phonetic:'ˈvɜːsətaɪl',definition:'adj. 多才多艺的，通用的',example:'A versatile tool.',level:3},
  {word:'viable',phonetic:'ˈvaɪəbl',definition:'adj. 可行的，能独立发展的',example:'A viable option.',level:3},
  {word:'virtually',phonetic:'ˈvɜːtʃuəli',definition:'adv. 几乎，实际上',example:'Virtually impossible.',level:2},
  {word:'volatile',phonetic:'ˈvɒlətaɪl',definition:'adj. 不稳定的，易挥发的',example:'A volatile market.',level:3},
  {word:'wary',phonetic:'ˈweəri',definition:'adj. 谨慎的，小心的',example:'Be wary of risks.',level:3},
  {word:'weigh',phonetic:'weɪ',definition:'v. 权衡，称重',example:'Weigh the options.',level:2},
];
