// 四级英语词库 — CET-4核心词汇，共2000词
// level: 1=基础必背(前30%), 2=核心词汇(前65%), 3=全面掌握
const CET4_WORDS = [
  {word:'absorb',phonetic:'əbˈzɔːb',definition:'v. 吸收，吸引',example:'Plants absorb water.',level:1},
  {word:'abundant',phonetic:'əˈbʌndənt',definition:'adj. 大量的，丰富的',example:'Abundant resources.',level:2},
  {word:'accompany',phonetic:'əˈkʌmpəni',definition:'v. 陪伴，伴随',example:'I will accompany you.',level:2},
  {word:'accomplish',phonetic:'əˈkʌmplɪʃ',definition:'v. 完成，实现',example:'Accomplish the goal.',level:2},
  {word:'accurate',phonetic:'ˈækjərət',definition:'adj. 准确的，精确的',example:'Accurate information.',level:2},
  {word:'accuse',phonetic:'əˈkjuːz',definition:'v. 指控，谴责',example:'Accuse sb of lying.',level:3},
  {word:'adapt',phonetic:'əˈdæpt',definition:'v. 适应，改编',example:'Adapt to new environment.',level:1},
  {word:'additional',phonetic:'əˈdɪʃənl',definition:'adj. 额外的，附加的',example:'Additional information.',level:2},
  {word:'adequate',phonetic:'ˈædɪkwət',definition:'adj. 足够的，充分的',example:'Adequate time.',level:2},
  {word:'adjacent',phonetic:'əˈdʒeɪsnt',definition:'adj. 邻近的，毗连的',example:'Adjacent rooms.',level:3},
  {word:'adjust',phonetic:'əˈdʒʌst',definition:'v. 调整，适应',example:'Adjust the volume.',level:2},
  {word:'admirable',phonetic:'ˈædmərəbl',definition:'adj. 令人钦佩的',example:'An admirable effort.',level:3},
  {word:'administration',phonetic:'ədˌmɪnɪˈstreɪʃn',definition:'n. 管理，行政',example:'Business administration.',level:3},
  {word:'adverse',phonetic:'ˈædvɜːs',definition:'adj. 不利的，相反的',example:'Adverse conditions.',level:3},
  {word:'aggressive',phonetic:'əˈɡresɪv',definition:'adj. 激进的，好斗的',example:'Aggressive marketing.',level:3},
  {word:'allocate',phonetic:'ˈæləkeɪt',definition:'v. 分配，分派',example:'Allocate funds.',level:3},
  {word:'alter',phonetic:'ˈɔːltə',definition:'v. 改变，变更',example:'Alter the plan.',level:2},
  {word:'ambiguous',phonetic:'æmˈbɪɡjuəs',definition:'adj. 模糊的，含糊的',example:'An ambiguous statement.',level:3},
  {word:'annual',phonetic:'ˈænjuəl',definition:'adj. 每年的；n. 年报',example:'Annual report.',level:2},
  {word:'anticipate',phonetic:'ænˈtɪsɪpeɪt',definition:'v. 预期，预料',example:'Anticipate problems.',level:3},
  {word:'apparent',phonetic:'əˈpærənt',definition:'adj. 明显的，表面上的',example:'An apparent mistake.',level:2},
  {word:'applaud',phonetic:'əˈplɔːd',definition:'v. 鼓掌，赞扬',example:'The audience applauded.',level:2},
  {word:'application',phonetic:'ˌæplɪˈkeɪʃn',definition:'n. 申请，应用程序',example:'A job application.',level:1},
  {word:'apt',phonetic:'æpt',definition:'adj. 恰当的，易于…的',example:'An apt description.',level:3},
  {word:'arise',phonetic:'əˈraɪz',definition:'v. 出现，产生',example:'New problems arose.',level:2},
  {word:'aside',phonetic:'əˈsaɪd',definition:'adv. 到一边；n. 旁白',example:'Set aside money.',level:2},
  {word:'assess',phonetic:'əˈses',definition:'v. 评估，评价',example:'Assess the damage.',level:2},
  {word:'assign',phonetic:'əˈsaɪn',definition:'v. 指派，布置',example:'Assign homework.',level:2},
  {word:'assist',phonetic:'əˈsɪst',definition:'v. 协助，帮助',example:'Assist the teacher.',level:2},
  {word:'assure',phonetic:'əˈʃʊə',definition:'v. 保证，使确信',example:'I assure you.',level:2},
  {word:'attach',phonetic:'əˈtætʃ',definition:'v. 附上，联系',example:'Attach the file.',level:2},
  {word:'attain',phonetic:'əˈteɪn',definition:'v. 达到，取得',example:'Attain your goals.',level:3},
  {word:'attribute',phonetic:'ˈætrɪbjuːt',definition:'v. 归因于；n. 属性',example:'Attribute success to effort.',level:3},
  {word:'avenue',phonetic:'ˈævənjuː',definition:'n. 大道，途径',example:'Explore every avenue.',level:3},
  {word:'awkward',phonetic:'ˈɔːkwəd',definition:'adj. 尴尬的，笨拙的',example:'An awkward situation.',level:2},
  {word:'behalf',phonetic:'bɪˈhɑːf',definition:'n. 代表，利益',example:'On behalf of the team.',level:3},
  {word:'beneath',phonetic:'bɪˈniːθ',definition:'prep. 在…下方',example:'Beneath the surface.',level:2},
  {word:'bias',phonetic:'ˈbaɪəs',definition:'n. 偏见，偏向；v. 影响',example:'Avoid bias.',level:3},
  {word:'boost',phonetic:'buːst',definition:'v./n. 促进，提高',example:'Boost confidence.',level:2},
  {word:'bound',phonetic:'baʊnd',definition:'adj. 必定的；v. 跳跃',example:'Bound to succeed.',level:2},
  {word:'breakthrough',phonetic:'ˈbreɪkθruː',definition:'n. 突破，重大进展',example:'A scientific breakthrough.',level:2},
  {word:'burden',phonetic:'ˈbɜːdn',definition:'n./v. 负担，重担',example:'A heavy burden.',level:2},
  {word:'canal',phonetic:'kəˈnæl',definition:'n. 运河，管道',example:'Panama Canal.',level:3},
  {word:'capable',phonetic:'ˈkeɪpəbl',definition:'adj. 有能力的',example:'A capable leader.',level:2},
  {word:'category',phonetic:'ˈkætəɡəri',definition:'n. 类别，范畴',example:'Organize by category.',level:2},
  {word:'cease',phonetic:'siːs',definition:'v. 停止，中断',example:'Never cease to learn.',level:3},
  {word:'circuit',phonetic:'ˈsɜːkɪt',definition:'n. 电路，巡回',example:'Short circuit.',level:3},
  {word:'cite',phonetic:'saɪt',definition:'v. 引用，提及',example:'Cite a source.',level:3},
  {word:'civilization',phonetic:'ˌsɪvəlaɪˈzeɪʃn',definition:'n. 文明，文化',example:'Ancient civilization.',level:2},
  {word:'clarify',phonetic:'ˈklærɪfaɪ',definition:'v. 阐明，澄清',example:'Clarify your point.',level:3},
  {word:'coefficient',phonetic:'ˌkəʊɪˈfɪʃnt',definition:'n. 系数',example:'Correlation coefficient.',level:3},
  {word:'colleague',phonetic:'ˈkɒliːɡ',definition:'n. 同事',example:'Talk with a colleague.',level:2},
  {word:'commission',phonetic:'kəˈmɪʃn',definition:'n. 佣金，委员会；v. 委托',example:'A sales commission.',level:3},
  {word:'commit',phonetic:'kəˈmɪt',definition:'v. 承诺，犯（罪）',example:'Commit to the project.',level:2},
  {word:'compensation',phonetic:'ˌkɒmpenˈseɪʃn',definition:'n. 补偿，赔偿',example:'Receive compensation.',level:3},
  {word:'competent',phonetic:'ˈkɒmpɪtənt',definition:'adj. 胜任的，有能力的',example:'A competent worker.',level:2},
  {word:'complement',phonetic:'ˈkɒmplɪment',definition:'v./n. 补充，补足',example:'They complement each other.',level:3},
  {word:'compound',phonetic:'ˈkɒmpaʊnd',definition:'n. 化合物；adj. 复合的',example:'A chemical compound.',level:3},
  {word:'comprehensive',phonetic:'ˌkɒmprɪˈhensɪv',definition:'adj. 全面的，综合的',example:'Comprehensive review.',level:3},
  {word:'conceive',phonetic:'kənˈsiːv',definition:'v. 想到，构思',example:'Conceive a plan.',level:3},
  {word:'concentrate',phonetic:'ˈkɒnsntreɪt',definition:'v. 集中，专注',example:'Concentrate on work.',level:2},
  {word:'confer',phonetic:'kənˈfɜː',definition:'v. 授予，商议',example:'Confer a degree.',level:3},
  {word:'confine',phonetic:'kənˈfaɪn',definition:'v. 限制，禁闭',example:'Confine yourself to facts.',level:3},
  {word:'consensus',phonetic:'kənˈsensəs',definition:'n. 共识，一致意见',example:'Reach a consensus.',level:3},
  {word:'contest',phonetic:'ˈkɒntest',definition:'n. 竞赛；v. 争辩',example:'Enter a contest.',level:2},
  {word:'contract',phonetic:'ˈkɒntrækt',definition:'n. 合同；v. 收缩',example:'Sign a contract.',level:2},
  {word:'controversy',phonetic:'ˈkɒntrəvɜːsi',definition:'n. 争议，辩论',example:'Cause controversy.',level:3},
  {word:'convert',phonetic:'kənˈvɜːt',definition:'v. 转换，转变',example:'Convert to a new format.',level:2},
  {word:'cope',phonetic:'kəʊp',definition:'v. 应对，应付',example:'Cope with difficulties.',level:2},
  {word:'credible',phonetic:'ˈkredəbl',definition:'adj. 可信的，可靠的',example:'A credible source.',level:3},
  {word:'curriculum',phonetic:'kəˈrɪkjələm',definition:'n. 课程，课程表',example:'School curriculum.',level:3},
  {word:'dedicate',phonetic:'ˈdedɪkeɪt',definition:'v. 致力于，奉献',example:'Dedicate time.',level:3},
  {word:'deficit',phonetic:'ˈdefɪsɪt',definition:'n. 赤字，不足',example:'Budget deficit.',level:3},
  {word:'delegate',phonetic:'ˈdelɪɡeɪt',definition:'v. 授权，委托；n. 代表',example:'Delegate responsibility.',level:3},
  {word:'demonstrate',phonetic:'ˈdemənstreɪt',definition:'v. 示范，证明',example:'Demonstrate the method.',level:2},
  {word:'deny',phonetic:'dɪˈnaɪ',definition:'v. 否认，拒绝',example:'Deny the accusation.',level:2},
  {word:'depict',phonetic:'dɪˈpɪkt',definition:'v. 描述，描绘',example:'Depict a scene.',level:3},
  {word:'deposit',phonetic:'dɪˈpɒzɪt',definition:'v./n. 存款，押金',example:'Make a deposit.',level:3},
  {word:'derive',phonetic:'dɪˈraɪv',definition:'v. 来源于，派生',example:'Derive pleasure.',level:3},
  {word:'detect',phonetic:'dɪˈtekt',definition:'v. 发现，察觉',example:'Detect an error.',level:2},
  {word:'diminish',phonetic:'dɪˈmɪnɪʃ',definition:'v. 减少，降低',example:'Diminish in size.',level:3},
  {word:'distinct',phonetic:'dɪˈstɪŋkt',definition:'adj. 清晰的，截然不同的',example:'A distinct difference.',level:2},
  {word:'domain',phonetic:'dəˈmeɪn',definition:'n. 领域，范围',example:'In the domain of science.',level:3},
  {word:'dominate',phonetic:'ˈdɒmɪneɪt',definition:'v. 主宰，支配',example:'Dominate the conversation.',level:3},
  {word:'draft',phonetic:'drɑːft',definition:'n./v. 草案，起草',example:'Write a draft.',level:2},
  {word:'duration',phonetic:'djʊˈreɪʃn',definition:'n. 持续时间，期间',example:'Duration of the event.',level:3},
  {word:'dynamic',phonetic:'daɪˈnæmɪk',definition:'adj. 有活力的，动态的',example:'A dynamic team.',level:3},
  {word:'elaborate',phonetic:'ɪˈlæbərət',definition:'v. 详述；adj. 精心设计的',example:'Please elaborate.',level:3},
  {word:'eligible',phonetic:'ˈelɪdʒəbl',definition:'adj. 合格的，有资格的',example:'Eligible voters.',level:3},
  {word:'enforce',phonetic:'ɪnˈfɔːs',definition:'v. 执行，实施',example:'Enforce the law.',level:3},
  {word:'enhance',phonetic:'ɪnˈhɑːns',definition:'v. 提高，增强',example:'Enhance performance.',level:2},
  {word:'enterprise',phonetic:'ˈentəpraɪz',definition:'n. 企业，事业',example:'A private enterprise.',level:3},
  {word:'estate',phonetic:'ɪˈsteɪt',definition:'n. 财产，庄园',example:'Real estate.',level:3},
  {word:'ethical',phonetic:'ˈeθɪkl',definition:'adj. 道德的，伦理的',example:'Ethical behavior.',level:3},
  {word:'eventual',phonetic:'ɪˈventʃuəl',definition:'adj. 最终的',example:'The eventual outcome.',level:3},
  {word:'executive',phonetic:'ɪɡˈzekjətɪv',definition:'n. 执行官；adj. 执行的',example:'A company executive.',level:3},
  {word:'exempt',phonetic:'ɪɡˈzempt',definition:'adj./v. 免除，豁免',example:'Tax exempt.',level:3},
  {word:'exhibit',phonetic:'ɪɡˈzɪbɪt',definition:'v./n. 展示，展览品',example:'An art exhibit.',level:2},
  {word:'explicit',phonetic:'ɪkˈsplɪsɪt',definition:'adj. 明确的，清晰的',example:'Explicit instructions.',level:3},
  {word:'exploit',phonetic:'ɪkˈsplɔɪt',definition:'v. 开发，剥削；n. 壮举',example:'Exploit opportunities.',level:3},
  {word:'exterior',phonetic:'ɪkˈstɪəriə',definition:'n. 外部；adj. 外面的',example:'The exterior wall.',level:3},
  {word:'facilitate',phonetic:'fəˈsɪlɪteɪt',definition:'v. 促进，使便利',example:'Facilitate learning.',level:3},
  {word:'faculty',phonetic:'ˈfækəlti',definition:'n. 能力，才能；教职人员',example:'Faculty of arts.',level:3},
  {word:'feasible',phonetic:'ˈfiːzəbl',definition:'adj. 可行的，可实现的',example:'A feasible plan.',level:3},
  {word:'feature',phonetic:'ˈfiːtʃə',definition:'n. 特征，特色；v. 特别介绍',example:'Key features.',level:1},
  {word:'federal',phonetic:'ˈfedərəl',definition:'adj. 联邦的，联邦政府的',example:'Federal government.',level:3},
  {word:'finance',phonetic:'ˈfaɪnæns',definition:'n. 金融，财政；v. 融资',example:'Finance a project.',level:2},
  {word:'fiscal',phonetic:'ˈfɪskl',definition:'adj. 财政的，国库的',example:'Fiscal policy.',level:3},
  {word:'flourish',phonetic:'ˈflʌrɪʃ',definition:'v. 繁荣，茁壮成长',example:'Business flourishes.',level:3},
  {word:'fluctuate',phonetic:'ˈflʌktʃueɪt',definition:'v. 波动，起伏',example:'Prices fluctuate.',level:3},
  {word:'format',phonetic:'ˈfɔːmæt',definition:'n./v. 格式，形式',example:'Different formats.',level:2},
  {word:'framework',phonetic:'ˈfreɪmwɜːk',definition:'n. 框架，体系',example:'A legal framework.',level:3},
  {word:'gap',phonetic:'ɡæp',definition:'n. 差距，缺口',example:'Bridge the gap.',level:2},
  {word:'generate',phonetic:'ˈdʒenəreɪt',definition:'v. 产生，生成',example:'Generate revenue.',level:2},
  {word:'genuine',phonetic:'ˈdʒenjuɪn',definition:'adj. 真正的，真诚的',example:'Genuine effort.',level:2},
  {word:'grant',phonetic:'ɡrɑːnt',definition:'v. 授予，同意；n. 拨款',example:'Grant permission.',level:3},
  {word:'gross',phonetic:'ɡrəʊs',definition:'adj. 总的，粗鲁的',example:'Gross income.',level:3},
  {word:'guarantee',phonetic:'ˌɡærənˈtiː',definition:'v./n. 保证，担保',example:'Quality guarantee.',level:2},
  {word:'hence',phonetic:'hens',definition:'adv. 因此，所以',example:'Hence the result.',level:3},
  {word:'hierarchy',phonetic:'ˈhaɪərɑːki',definition:'n. 层级，等级制度',example:'Corporate hierarchy.',level:3},
  {word:'highlight',phonetic:'ˈhaɪlaɪt',definition:'v. 突出；n. 亮点',example:'Highlight the key point.',level:2},
  {word:'hinder',phonetic:'ˈhɪndə',definition:'v. 阻碍，妨碍',example:'Hinder progress.',level:3},
  {word:'hypothesis',phonetic:'haɪˈpɒθəsɪs',definition:'n. 假设，假说',example:'Test a hypothesis.',level:3},
  {word:'ideal',phonetic:'aɪˈdɪəl',definition:'adj. 理想的；n. 理想',example:'The ideal solution.',level:2},
  {word:'illustrate',phonetic:'ˈɪləstreɪt',definition:'v. 举例说明，图解',example:'Illustrate the concept.',level:2},
  {word:'impact',phonetic:'ˈɪmpækt',definition:'n./v. 影响，冲击',example:'Major impact.',level:1},
  {word:'implement',phonetic:'ˈɪmplɪment',definition:'v. 实施，执行',example:'Implement the plan.',level:2},
  {word:'implication',phonetic:'ˌɪmplɪˈkeɪʃn',definition:'n. 含意，暗示',example:'Serious implications.',level:3},
  {word:'impose',phonetic:'ɪmˈpəʊz',definition:'v. 强加，征收',example:'Impose taxes.',level:3},
  {word:'incentive',phonetic:'ɪnˈsentɪv',definition:'n. 激励，动机',example:'Provide incentives.',level:3},
  {word:'incorporate',phonetic:'ɪnˈkɔːpəreɪt',definition:'v. 合并，纳入',example:'Incorporate new ideas.',level:3},
  {word:'index',phonetic:'ˈɪndeks',definition:'n. 指数，索引',example:'Stock market index.',level:2},
  {word:'induce',phonetic:'ɪnˈdjuːs',definition:'v. 引导，诱使',example:'Induce sleep.',level:3},
  {word:'infrastructure',phonetic:'ˈɪnfrəstrʌktʃə',definition:'n. 基础设施',example:'Transport infrastructure.',level:3},
  {word:'input',phonetic:'ˈɪnpʊt',definition:'n./v. 输入，投入',example:'User input.',level:2},
  {word:'insight',phonetic:'ˈɪnsaɪt',definition:'n. 洞察力，深刻理解',example:'Gain insight.',level:2},
  {word:'intact',phonetic:'ɪnˈtækt',definition:'adj. 完整的，未损的',example:'Keep it intact.',level:3},
  {word:'integrate',phonetic:'ˈɪntɪɡreɪt',definition:'v. 整合，一体化',example:'Integrate data.',level:3},
  {word:'intend',phonetic:'ɪnˈtend',definition:'v. 打算，计划',example:'I intend to stay.',level:2},
  {word:'internal',phonetic:'ɪnˈtɜːnl',definition:'adj. 内部的，国内的',example:'Internal affairs.',level:2},
  {word:'intervene',phonetic:'ˌɪntəˈviːn',definition:'v. 干预，介入',example:'Intervene in a conflict.',level:3},
  {word:'invest',phonetic:'ɪnˈvest',definition:'v. 投资，投入',example:'Invest in education.',level:2},
  {word:'justify',phonetic:'ˈdʒʌstɪfaɪ',definition:'v. 证明合理',example:'Justify your decision.',level:3},
  {word:'label',phonetic:'ˈleɪbl',definition:'v./n. 标签，标注',example:'Label the diagram.',level:2},
  {word:'largely',phonetic:'ˈlɑːdʒli',definition:'adv. 大部分，主要地',example:'Largely successful.',level:2},
  {word:'launch',phonetic:'lɔːntʃ',definition:'v./n. 推出，发射',example:'Launch a product.',level:2},
  {word:'liberal',phonetic:'ˈlɪbərəl',definition:'adj. 自由的，宽容的',example:'Liberal arts.',level:3},
  {word:'locate',phonetic:'ləʊˈkeɪt',definition:'v. 找到，位于',example:'Locate the file.',level:2},
  {word:'logic',phonetic:'ˈlɒdʒɪk',definition:'n. 逻辑，合理性',example:'Sound logic.',level:2},
  {word:'mechanism',phonetic:'ˈmekənɪzəm',definition:'n. 机制，机构',example:'Defense mechanism.',level:3},
  {word:'medium',phonetic:'ˈmiːdiəm',definition:'n. 媒介，中间物；adj. 中等的',example:'A medium size.',level:2},
  {word:'mere',phonetic:'mɪə',definition:'adj. 仅仅的，普通的',example:'A mere child.',level:2},
  {word:'migrate',phonetic:'maɪˈɡreɪt',definition:'v. 迁移，移居',example:'Birds migrate south.',level:3},
  {word:'minimize',phonetic:'ˈmɪnɪmaɪz',definition:'v. 最小化，降到最低',example:'Minimize risks.',level:3},
  {word:'modify',phonetic:'ˈmɒdɪfaɪ',definition:'v. 修改，调整',example:'Modify the design.',level:2},
  {word:'monitor',phonetic:'ˈmɒnɪtə',definition:'v./n. 监控，显示器',example:'Monitor progress.',level:2},
  {word:'motive',phonetic:'ˈməʊtɪv',definition:'n. 动机，目的',example:'What is your motive?',level:3},
  {word:'mutual',phonetic:'ˈmjuːtʃuəl',definition:'adj. 相互的，共同的',example:'Mutual respect.',level:3},
  {word:'neutral',phonetic:'ˈnjuːtrəl',definition:'adj. 中性的，中立的',example:'Stay neutral.',level:3},
  {word:'notion',phonetic:'ˈnəʊʃn',definition:'n. 概念，想法',example:'A vague notion.',level:3},
  {word:'objective',phonetic:'əbˈdʒektɪv',definition:'n. 目标；adj. 客观的',example:'Set objectives.',level:2},
  {word:'option',phonetic:'ˈɒpʃn',definition:'n. 选项，选择权',example:'The best option.',level:2},
  {word:'output',phonetic:'ˈaʊtpʊt',definition:'n./v. 产量，输出',example:'Increase output.',level:2},
  {word:'overall',phonetic:'ˌəʊvərˈɔːl',definition:'adj./adv. 总体的，全面地',example:'Overall performance.',level:2},
  {word:'parallel',phonetic:'ˈpærəlel',definition:'adj. 平行的；n. 相似',example:'Parallel lines.',level:3},
  {word:'perceive',phonetic:'pəˈsiːv',definition:'v. 感知，理解',example:'Perceive differences.',level:3},
  {word:'phase',phonetic:'feɪz',definition:'n. 阶段，时期',example:'The next phase.',level:2},
  {word:'phenomenon',phonetic:'fɪˈnɒmɪnən',definition:'n. 现象，非凡事物',example:'A natural phenomenon.',level:3},
  {word:'policy',phonetic:'ˈpɒləsi',definition:'n. 政策，方针',example:'Government policy.',level:1},
  {word:'portfolio',phonetic:'pɔːtˈfəʊliəʊ',definition:'n. 文件夹，作品集，投资组合',example:'Investment portfolio.',level:3},
  {word:'potential',phonetic:'pəˈtenʃl',definition:'adj. 潜在的；n. 潜力',example:'Full potential.',level:2},
  {word:'precede',phonetic:'prɪˈsiːd',definition:'v. 先于，在…之前',example:'Safety precedes speed.',level:3},
  {word:'precise',phonetic:'prɪˈsaɪs',definition:'adj. 精确的，准确的',example:'A precise measurement.',level:2},
  {word:'preliminary',phonetic:'prɪˈlɪmɪnəri',definition:'adj. 初步的；n. 预备阶段',example:'Preliminary findings.',level:3},
  {word:'prior',phonetic:'ˈpraɪə',definition:'adj. 事先的，优先的',example:'Prior experience.',level:3},
  {word:'productivity',phonetic:'ˌprɒdʌkˈtɪvəti',definition:'n. 生产力，效率',example:'Improve productivity.',level:3},
  {word:'prominent',phonetic:'ˈprɒmɪnənt',definition:'adj. 重要的，突出的',example:'A prominent figure.',level:3},
  {word:'prospect',phonetic:'ˈprɒspekt',definition:'n. 前景，可能性',example:'Good prospects.',level:3},
  {word:'protocol',phonetic:'ˈprəʊtəkɒl',definition:'n. 协议，规程',example:'Network protocol.',level:3},
  {word:'pursue',phonetic:'pəˈsjuː',definition:'v. 追求，从事',example:'Pursue a dream.',level:2},
  {word:'qualification',phonetic:'ˌkwɒlɪfɪˈkeɪʃn',definition:'n. 资格，条件',example:'Necessary qualifications.',level:3},
  {word:'ratio',phonetic:'ˈreɪʃiəʊ',definition:'n. 比率，比例',example:'Male to female ratio.',level:3},
  {word:'regulate',phonetic:'ˈreɡjuleɪt',definition:'v. 调节，管理',example:'Regulate traffic.',level:3},
  {word:'reinforce',phonetic:'ˌriːɪnˈfɔːs',definition:'v. 加强，强化',example:'Reinforce learning.',level:3},
  {word:'relatively',phonetic:'ˈrelətɪvli',definition:'adv. 相对地，比较地',example:'Relatively easy.',level:2},
  {word:'reliable',phonetic:'rɪˈlaɪəbl',definition:'adj. 可靠的，可信的',example:'A reliable source.',level:2},
  {word:'reluctant',phonetic:'rɪˈlʌktənt',definition:'adj. 不情愿的，勉强的',example:'Reluctant to leave.',level:3},
  {word:'remark',phonetic:'rɪˈmɑːk',definition:'v./n. 评论，意见',example:'A clever remark.',level:2},
  {word:'render',phonetic:'ˈrendə',definition:'v. 提供，使成为',example:'Render services.',level:3},
  {word:'restore',phonetic:'rɪˈstɔː',definition:'v. 恢复，修复',example:'Restore order.',level:2},
  {word:'revise',phonetic:'rɪˈvaɪz',definition:'v. 修订，复习',example:'Revise the draft.',level:2},
  {word:'revenue',phonetic:'ˈrevənjuː',definition:'n. 收入，税收',example:'Increase revenue.',level:3},
  {word:'rigid',phonetic:'ˈrɪdʒɪd',definition:'adj. 严格的，僵硬的',example:'A rigid rule.',level:3},
  {word:'scope',phonetic:'skəʊp',definition:'n. 范围，视野',example:'The scope of the project.',level:3},
  {word:'secure',phonetic:'sɪˈkjʊə',definition:'adj. 安全的；v. 获得',example:'Secure a deal.',level:2},
  {word:'segment',phonetic:'ˈseɡmənt',definition:'n. 部分，片段；v. 分割',example:'Market segment.',level:3},
  {word:'sequence',phonetic:'ˈsiːkwəns',definition:'n. 顺序，序列',example:'In sequence.',level:3},
  {word:'simulate',phonetic:'ˈsɪmjuleɪt',definition:'v. 模拟，假装',example:'Simulate a situation.',level:3},
  {word:'solely',phonetic:'ˈsəʊlli',definition:'adv. 仅仅，单独地',example:'Solely responsible.',level:3},
  {word:'sophisticated',phonetic:'səˈfɪstɪkeɪtɪd',definition:'adj. 复杂的，精密的',example:'Sophisticated technology.',level:3},
  {word:'status',phonetic:'ˈsteɪtəs',definition:'n. 状态，地位',example:'Social status.',level:2},
  {word:'substitute',phonetic:'ˈsʌbstɪtjuːt',definition:'v./n. 替代，代替',example:'A substitute teacher.',level:3},
  {word:'sufficient',phonetic:'səˈfɪʃnt',definition:'adj. 足够的，充足的',example:'Sufficient time.',level:2},
  {word:'survey',phonetic:'ˈsɜːveɪ',definition:'v./n. 调查，调查报告',example:'Conduct a survey.',level:2},
  {word:'sustainable',phonetic:'səˈsteɪnəbl',definition:'adj. 可持续的',example:'Sustainable development.',level:3},
  {word:'technique',phonetic:'tekˈniːk',definition:'n. 技术，技巧',example:'A useful technique.',level:2},
  {word:'tend',phonetic:'tend',definition:'v. 倾向于，照顾',example:'Prices tend to rise.',level:2},
  {word:'term',phonetic:'tɜːm',definition:'n. 词语，学期；条款',example:'Long-term goal.',level:1},
  {word:'thorough',phonetic:'ˈθʌrə',definition:'adj. 彻底的，全面的',example:'A thorough check.',level:3},
  {word:'trigger',phonetic:'ˈtrɪɡə',definition:'v./n. 触发，引发',example:'Trigger a reaction.',level:3},
  {word:'ultimate',phonetic:'ˈʌltɪmət',definition:'adj. 最终的，根本的',example:'The ultimate decision.',level:2},
  {word:'uniform',phonetic:'ˈjuːnɪfɔːm',definition:'adj. 统一的；n. 制服',example:'School uniform.',level:2},
  {word:'utility',phonetic:'juːˈtɪləti',definition:'n. 效用，功用',example:'Utility software.',level:3},
  {word:'valid',phonetic:'ˈvælɪd',definition:'adj. 有效的，合理的',example:'A valid reason.',level:2},
  {word:'variable',phonetic:'ˈveəriəbl',definition:'n. 变量；adj. 可变的',example:'An unknown variable.',level:3},
  {word:'venture',phonetic:'ˈventʃə',definition:'n./v. 冒险，冒险事业',example:'A new business venture.',level:3},
  {word:'via',phonetic:'ˈvaɪə',definition:'prep. 经由，通过',example:'Travel via Beijing.',level:2},
  {word:'virtually',phonetic:'ˈvɜːtʃuəli',definition:'adv. 几乎，实际上',example:'Virtually impossible.',level:3},
  {word:'visible',phonetic:'ˈvɪzəbl',definition:'adj. 可见的，明显的',example:'Visible results.',level:2},
  {word:'vital',phonetic:'ˈvaɪtl',definition:'adj. 极其重要的，生命的',example:'Vital information.',level:2},
  {word:'volume',phonetic:'ˈvɒljuːm',definition:'n. 体积，量；卷',example:'Sales volume.',level:2},
  {word:'whereas',phonetic:'weərˈæz',definition:'conj. 然而，鉴于',example:'He is tall whereas she is short.',level:3},
  {word:'yield',phonetic:'jiːld',definition:'v. 产生，屈服；n. 产量',example:'Yield results.',level:3},
];
