// 初中英语词库 — 义务教育7-9年级核心词汇，共1200词
// level: 1=7年级基础, 2=8年级核心, 3=9年级提升
const JUNIOR_WORDS = [
  // A
  {word:'able',phonetic:'ˈeɪbl',definition:'adj. 能够的，有能力的',example:'She is able to speak French.',level:1},
  {word:'abroad',phonetic:'əˈbrɔːd',definition:'adv. 在国外，到国外',example:'My sister studies abroad.',level:2},
  {word:'absent',phonetic:'ˈæbsənt',definition:'adj. 缺席的，不在的',example:'He was absent from school.',level:2},
  {word:'accept',phonetic:'əkˈsept',definition:'v. 接受，认可',example:'Please accept my apology.',level:2},
  {word:'accident',phonetic:'ˈæksɪdənt',definition:'n. 事故，意外',example:'He had a car accident.',level:2},
  {word:'achieve',phonetic:'əˈtʃiːv',definition:'v. 实现，达到',example:'Work hard to achieve your goals.',level:3},
  {word:'across',phonetic:'əˈkrɒs',definition:'prep. 横越，穿过',example:'Walk across the street.',level:1},
  {word:'activity',phonetic:'ækˈtɪvəti',definition:'n. 活动',example:'I enjoy outdoor activities.',level:1},
  {word:'actually',phonetic:'ˈæktʃuəli',definition:'adv. 实际上，事实上',example:'Actually, I disagree.',level:2},
  {word:'add',phonetic:'æd',definition:'v. 增加，添加',example:'Add some salt.',level:1},
  {word:'address',phonetic:'əˈdres',definition:'n. 地址；v. 演讲',example:'What is your address?',level:1},
  {word:'adult',phonetic:'ˈædʌlt',definition:'n. 成年人；adj. 成年的',example:'Adults pay full price.',level:2},
  {word:'advice',phonetic:'ədˈvaɪs',definition:'n. 建议，忠告',example:'Follow the doctor\'s advice.',level:2},
  {word:'affect',phonetic:'əˈfekt',definition:'v. 影响，作用于',example:'The weather affects my mood.',level:3},
  {word:'afraid',phonetic:'əˈfreɪd',definition:'adj. 害怕的，担忧的',example:'I am afraid of snakes.',level:1},
  {word:'agree',phonetic:'əˈɡriː',definition:'v. 同意，赞成',example:'I agree with you.',level:1},
  {word:'already',phonetic:'ɔːlˈredi',definition:'adv. 已经',example:'I have already eaten.',level:1},
  {word:'although',phonetic:'ɔːlˈðəʊ',definition:'conj. 虽然，尽管',example:'Although it rained, we played outside.',level:2},
  {word:'always',phonetic:'ˈɔːlweɪz',definition:'adv. 总是，一直',example:'I always brush my teeth.',level:1},
  {word:'amount',phonetic:'əˈmaʊnt',definition:'n. 数量，总量',example:'A large amount of money.',level:2},
  {word:'angry',phonetic:'ˈæŋɡri',definition:'adj. 生气的',example:'She is angry with me.',level:1},
  {word:'another',phonetic:'əˈnʌðə',definition:'adj./pron. 另一个',example:'Give me another chance.',level:1},
  {word:'answer',phonetic:'ˈɑːnsə',definition:'n./v. 回答，答案',example:'Answer the question.',level:1},
  {word:'any',phonetic:'ˈeni',definition:'adj./pron. 任何，一些',example:'Is there any milk?',level:1},
  {word:'anything',phonetic:'ˈeniθɪŋ',definition:'pron. 任何事物',example:'Is there anything I can do?',level:1},
  {word:'anyway',phonetic:'ˈeniweɪ',definition:'adv. 无论如何，反正',example:'Anyway, let\'s begin.',level:2},
  {word:'appear',phonetic:'əˈpɪə',definition:'v. 出现；似乎',example:'A star appeared in the sky.',level:2},
  {word:'arrive',phonetic:'əˈraɪv',definition:'v. 到达，抵达',example:'We arrived at 9 o\'clock.',level:1},
  {word:'attention',phonetic:'əˈtenʃn',definition:'n. 注意，关注',example:'Pay attention to the teacher.',level:2},
  {word:'audience',phonetic:'ˈɔːdiəns',definition:'n. 观众，听众',example:'The audience clapped loudly.',level:3},
  {word:'aunt',phonetic:'ɑːnt',definition:'n. 阿姨，姑妈',example:'My aunt is a nurse.',level:1},
  {word:'awake',phonetic:'əˈweɪk',definition:'adj. 醒着的',example:'Are you still awake?',level:2},
  {word:'awful',phonetic:'ˈɔːfl',definition:'adj. 可怕的，糟糕的',example:'The weather is awful.',level:3},
  // B
  {word:'base',phonetic:'beɪs',definition:'n. 基础；v. 以…为基础',example:'The base of the pyramid.',level:2},
  {word:'bathroom',phonetic:'ˈbɑːθruːm',definition:'n. 浴室，卫生间',example:'The bathroom is upstairs.',level:1},
  {word:'beach',phonetic:'biːtʃ',definition:'n. 海滩，海滨',example:'We played on the beach.',level:1},
  {word:'become',phonetic:'bɪˈkʌm',definition:'v. 变成，成为',example:'She became a doctor.',level:1},
  {word:'begin',phonetic:'bɪˈɡɪn',definition:'v. 开始',example:'Let\'s begin the lesson.',level:1},
  {word:'believe',phonetic:'bɪˈliːv',definition:'v. 相信，认为',example:'I believe in you.',level:2},
  {word:'belong',phonetic:'bɪˈlɒŋ',definition:'v. 属于，归属',example:'This book belongs to me.',level:2},
  {word:'beside',phonetic:'bɪˈsaɪd',definition:'prep. 在…旁边',example:'Sit beside me.',level:1},
  {word:'better',phonetic:'ˈbetə',definition:'adj./adv. 更好的，更好地',example:'She feels better now.',level:1},
  {word:'billion',phonetic:'ˈbɪljən',definition:'num. 十亿',example:'There are 8 billion people.',level:3},
  {word:'borrow',phonetic:'ˈbɒrəʊ',definition:'v. 借入，借用',example:'Can I borrow your pen?',level:1},
  {word:'both',phonetic:'bəʊθ',definition:'adj./pron. 两个都，双方',example:'Both of them are right.',level:1},
  {word:'bottom',phonetic:'ˈbɒtəm',definition:'n. 底部；adj. 最低的',example:'The coin is at the bottom.',level:2},
  {word:'brain',phonetic:'breɪn',definition:'n. 大脑，智力',example:'Use your brain.',level:2},
  {word:'brave',phonetic:'breɪv',definition:'adj. 勇敢的',example:'The brave soldier fought.',level:2},
  {word:'break',phonetic:'breɪk',definition:'v. 打破，中断；n. 休息',example:'Take a break.',level:1},
  {word:'bright',phonetic:'braɪt',definition:'adj. 明亮的；聪明的',example:'A bright student.',level:2},
  {word:'bring',phonetic:'brɪŋ',definition:'v. 带来，拿来',example:'Bring your book.',level:1},
  {word:'build',phonetic:'bɪld',definition:'v. 建造，建立',example:'Build a house.',level:1},
  {word:'burn',phonetic:'bɜːn',definition:'v. 燃烧，烧伤',example:'Don\'t burn the paper.',level:2},
  // C
  {word:'call',phonetic:'kɔːl',definition:'v. 打电话；称呼；n. 呼叫',example:'Call me later.',level:1},
  {word:'calm',phonetic:'kɑːm',definition:'adj. 平静的；v. 使平静',example:'Stay calm.',level:2},
  {word:'camera',phonetic:'ˈkæmərə',definition:'n. 照相机，摄像机',example:'I take photos with my camera.',level:1},
  {word:'care',phonetic:'keə',definition:'v./n. 关心，照顾',example:'Take care of yourself.',level:1},
  {word:'careful',phonetic:'ˈkeəfl',definition:'adj. 小心的，谨慎的',example:'Be careful on the road.',level:1},
  {word:'catch',phonetic:'kætʃ',definition:'v. 接住，抓住；赶上',example:'Catch the ball.',level:1},
  {word:'cause',phonetic:'kɔːz',definition:'v. 引起，导致；n. 原因',example:'What caused the problem?',level:2},
  {word:'chance',phonetic:'tʃɑːns',definition:'n. 机会，可能性',example:'Give me a chance.',level:2},
  {word:'change',phonetic:'tʃeɪndʒ',definition:'v./n. 改变，变化',example:'Things change quickly.',level:1},
  {word:'character',phonetic:'ˈkærəktə',definition:'n. 性格，人物；汉字',example:'She has a strong character.',level:3},
  {word:'check',phonetic:'tʃek',definition:'v. 检查，核对',example:'Check your homework.',level:1},
  {word:'child',phonetic:'tʃaɪld',definition:'n. 小孩，儿童',example:'Every child is special.',level:1},
  {word:'choice',phonetic:'tʃɔɪs',definition:'n. 选择，选项',example:'You have a choice.',level:2},
  {word:'choose',phonetic:'tʃuːz',definition:'v. 选择，挑选',example:'Choose your answer.',level:2},
  {word:'close',phonetic:'kləʊz',definition:'v. 关闭；adj. 近的',example:'Close the door.',level:1},
  {word:'collect',phonetic:'kəˈlekt',definition:'v. 收集，采集',example:'I collect stamps.',level:2},
  {word:'common',phonetic:'ˈkɒmən',definition:'adj. 普通的，常见的',example:'It is a common problem.',level:2},
  {word:'community',phonetic:'kəˈmjuːnəti',definition:'n. 社区，共同体',example:'Help your community.',level:3},
  {word:'compare',phonetic:'kəmˈpeə',definition:'v. 比较，对比',example:'Compare the two pictures.',level:3},
  {word:'complete',phonetic:'kəmˈpliːt',definition:'v. 完成；adj. 完整的',example:'Complete the exercise.',level:2},
  {word:'connect',phonetic:'kəˈnekt',definition:'v. 连接，联系',example:'Connect the dots.',level:2},
  {word:'continue',phonetic:'kənˈtɪnjuː',definition:'v. 继续',example:'Please continue.',level:2},
  {word:'control',phonetic:'kənˈtrəʊl',definition:'v./n. 控制，管理',example:'Control your temper.',level:3},
  {word:'correct',phonetic:'kəˈrekt',definition:'adj. 正确的；v. 纠正',example:'The answer is correct.',level:1},
  {word:'cost',phonetic:'kɒst',definition:'v./n. 花费，代价',example:'How much does it cost?',level:2},
  {word:'cover',phonetic:'ˈkʌvə',definition:'v. 覆盖，遮盖；n. 封面',example:'Cover the pot.',level:2},
  {word:'crazy',phonetic:'ˈkreɪzi',definition:'adj. 疯狂的，狂热的',example:'Don\'t go crazy.',level:2},
  {word:'create',phonetic:'kriˈeɪt',definition:'v. 创造，创作',example:'Create a new project.',level:3},
  {word:'cross',phonetic:'krɒs',definition:'v. 穿越；n. 十字；adj. 生气的',example:'Cross the road.',level:2},
  {word:'crowd',phonetic:'kraʊd',definition:'n. 人群，群众',example:'A large crowd gathered.',level:3},
  {word:'culture',phonetic:'ˈkʌltʃə',definition:'n. 文化，文明',example:'Chinese culture is rich.',level:3},
  {word:'cut',phonetic:'kʌt',definition:'v. 切，割；n. 伤口',example:'Cut the paper.',level:1},
  // D
  {word:'danger',phonetic:'ˈdeɪndʒə',definition:'n. 危险',example:'The danger is real.',level:2},
  {word:'dead',phonetic:'ded',definition:'adj. 死的，无生命的',example:'The plant is dead.',level:2},
  {word:'decide',phonetic:'dɪˈsaɪd',definition:'v. 决定',example:'I decided to study harder.',level:2},
  {word:'deep',phonetic:'diːp',definition:'adj. 深的；adv. 深深地',example:'The lake is deep.',level:2},
  {word:'delicious',phonetic:'dɪˈlɪʃəs',definition:'adj. 美味的，好吃的',example:'The food is delicious.',level:1},
  {word:'describe',phonetic:'dɪˈskraɪb',definition:'v. 描述，描写',example:'Describe what you see.',level:3},
  {word:'develop',phonetic:'dɪˈveləp',definition:'v. 发展，发育',example:'Children develop quickly.',level:3},
  {word:'die',phonetic:'daɪ',definition:'v. 死亡，枯萎',example:'The flowers died.',level:2},
  {word:'different',phonetic:'ˈdɪfrənt',definition:'adj. 不同的，有差异的',example:'We are different.',level:1},
  {word:'direction',phonetic:'dɪˈrekʃn',definition:'n. 方向，指示',example:'Go in this direction.',level:2},
  {word:'dirty',phonetic:'ˈdɜːti',definition:'adj. 脏的',example:'Your hands are dirty.',level:1},
  {word:'disappear',phonetic:'ˌdɪsəˈpɪə',definition:'v. 消失',example:'The clouds disappeared.',level:3},
  {word:'discover',phonetic:'dɪˈskʌvə',definition:'v. 发现，找到',example:'Columbus discovered America.',level:3},
  {word:'discuss',phonetic:'dɪˈskʌs',definition:'v. 讨论，商量',example:'Discuss the problem.',level:2},
  {word:'double',phonetic:'ˈdʌbl',definition:'adj./v. 双倍的，加倍',example:'Double the recipe.',level:2},
  {word:'drop',phonetic:'drɒp',definition:'v. 滴，落下；n. 水滴',example:'Don\'t drop the plate.',level:2},
  // E
  {word:'early',phonetic:'ˈɜːli',definition:'adj./adv. 早，提前',example:'Wake up early.',level:1},
  {word:'earth',phonetic:'ɜːθ',definition:'n. 地球，土地',example:'The earth is round.',level:2},
  {word:'education',phonetic:'ˌedʒuˈkeɪʃn',definition:'n. 教育',example:'Education is important.',level:3},
  {word:'either',phonetic:'ˈaɪðə',definition:'adj./pron. 两者之一；conj. 也（否定句）',example:'Either answer is fine.',level:2},
  {word:'else',phonetic:'els',definition:'adj. 其他的；adv. 否则',example:'What else do you need?',level:2},
  {word:'emotion',phonetic:'ɪˈməʊʃn',definition:'n. 情感，情绪',example:'Express your emotions.',level:3},
  {word:'enough',phonetic:'ɪˈnʌf',definition:'adj./adv. 足够的，充分地',example:'I have enough money.',level:2},
  {word:'environment',phonetic:'ɪnˈvaɪrənmənt',definition:'n. 环境，自然环境',example:'Protect the environment.',level:3},
  {word:'especially',phonetic:'ɪˈspeʃəli',definition:'adv. 特别，尤其',example:'I especially like cats.',level:3},
  {word:'event',phonetic:'ɪˈvent',definition:'n. 事件，活动',example:'A major event happened.',level:3},
  {word:'exactly',phonetic:'ɪɡˈzæktli',definition:'adv. 恰好，正好',example:'That\'s exactly right.',level:3},
  {word:'exam',phonetic:'ɪɡˈzæm',definition:'n. 考试',example:'Pass the exam.',level:1},
  {word:'example',phonetic:'ɪɡˈzɑːmpl',definition:'n. 例子，示例',example:'Give me an example.',level:1},
  {word:'exciting',phonetic:'ɪkˈsaɪtɪŋ',definition:'adj. 令人兴奋的',example:'This is exciting news!',level:2},
  {word:'expect',phonetic:'ɪkˈspekt',definition:'v. 期待，预期',example:'I expect you to arrive on time.',level:3},
  {word:'experience',phonetic:'ɪkˈspɪəriəns',definition:'n./v. 经历，体验',example:'I have experience in teaching.',level:3},
  {word:'explain',phonetic:'ɪkˈspleɪn',definition:'v. 解释，说明',example:'Can you explain this?',level:2},
  // F
  {word:'fail',phonetic:'feɪl',definition:'v. 失败，不及格',example:'Don\'t be afraid to fail.',level:2},
  {word:'fall',phonetic:'fɔːl',definition:'v. 跌倒，下降；n. 秋天',example:'Leaves fall in autumn.',level:1},
  {word:'famous',phonetic:'ˈfeɪməs',definition:'adj. 著名的，有名的',example:'He is a famous singer.',level:2},
  {word:'far',phonetic:'fɑː',definition:'adj./adv. 远的，遥远地',example:'How far is the school?',level:1},
  {word:'feel',phonetic:'fiːl',definition:'v. 感觉，触摸',example:'I feel tired.',level:1},
  {word:'field',phonetic:'fiːld',definition:'n. 田地，领域',example:'A field of wheat.',level:2},
  {word:'fight',phonetic:'faɪt',definition:'v./n. 打架，战斗',example:'Don\'t fight.',level:2},
  {word:'fill',phonetic:'fɪl',definition:'v. 填满，充满',example:'Fill in the blanks.',level:2},
  {word:'finally',phonetic:'ˈfaɪnəli',definition:'adv. 最后，终于',example:'Finally, we arrived.',level:2},
  {word:'find',phonetic:'faɪnd',definition:'v. 找到，发现',example:'Find the key.',level:1},
  {word:'fine',phonetic:'faɪn',definition:'adj. 好的，晴朗的；n. 罚款',example:'I\'m fine, thanks.',level:1},
  {word:'finish',phonetic:'ˈfɪnɪʃ',definition:'v./n. 完成，结束',example:'Finish your homework.',level:1},
  {word:'fire',phonetic:'faɪə',definition:'n. 火，火灾；v. 解雇',example:'Call the fire department.',level:1},
  {word:'fix',phonetic:'fɪks',definition:'v. 修理，固定',example:'Fix the bicycle.',level:2},
  {word:'follow',phonetic:'ˈfɒləʊ',definition:'v. 跟随，遵守',example:'Follow the rules.',level:2},
  {word:'force',phonetic:'fɔːs',definition:'n./v. 力，力量；强迫',example:'The force of gravity.',level:3},
  {word:'foreign',phonetic:'ˈfɒrən',definition:'adj. 外国的，外来的',example:'Learn a foreign language.',level:2},
  {word:'forget',phonetic:'fəˈɡet',definition:'v. 忘记',example:'Don\'t forget to call.',level:1},
  {word:'free',phonetic:'friː',definition:'adj. 自由的；免费的',example:'Are you free tomorrow?',level:1},
  {word:'fresh',phonetic:'freʃ',definition:'adj. 新鲜的，清新的',example:'Fresh air is good.',level:2},
  {word:'front',phonetic:'frʌnt',definition:'n. 前面，正面；adj. 前面的',example:'Sit at the front.',level:2},
  {word:'full',phonetic:'fʊl',definition:'adj. 满的，饱的',example:'I am full.',level:1},
  {word:'funny',phonetic:'ˈfʌni',definition:'adj. 有趣的，奇怪的',example:'That\'s funny!',level:1},
  {word:'future',phonetic:'ˈfjuːtʃə',definition:'n. 未来，将来',example:'Think about the future.',level:2},
  // G
  {word:'general',phonetic:'ˈdʒenrəl',definition:'adj. 普遍的，一般的',example:'In general, I agree.',level:3},
  {word:'gentle',phonetic:'ˈdʒentl',definition:'adj. 温和的，轻柔的',example:'Be gentle with the baby.',level:2},
  {word:'glad',phonetic:'ɡlæd',definition:'adj. 高兴的，乐意的',example:'I am glad to see you.',level:1},
  {word:'goal',phonetic:'ɡəʊl',definition:'n. 目标；进球',example:'Set a goal.',level:2},
  {word:'government',phonetic:'ˈɡʌvənmənt',definition:'n. 政府',example:'The government made a decision.',level:3},
  {word:'grow',phonetic:'ɡrəʊ',definition:'v. 生长，成长；种植',example:'Plants grow in sunlight.',level:1},
  {word:'guess',phonetic:'ɡes',definition:'v./n. 猜测，猜想',example:'Guess what happened.',level:2},
  {word:'guide',phonetic:'ɡaɪd',definition:'v./n. 引导，向导',example:'A tour guide.',level:2},
  // H
  {word:'happen',phonetic:'ˈhæpən',definition:'v. 发生',example:'What happened?',level:1},
  {word:'hard',phonetic:'hɑːd',definition:'adj. 困难的；硬的；adv. 努力地',example:'Study hard.',level:1},
  {word:'hate',phonetic:'heɪt',definition:'v./n. 恨，讨厌',example:'I hate being late.',level:2},
  {word:'health',phonetic:'helθ',definition:'n. 健康',example:'Good health is important.',level:2},
  {word:'hear',phonetic:'hɪə',definition:'v. 听到，听说',example:'I hear music.',level:1},
  {word:'heart',phonetic:'hɑːt',definition:'n. 心脏，内心',example:'My heart beats fast.',level:2},
  {word:'heavy',phonetic:'ˈhevi',definition:'adj. 重的，沉的',example:'The box is heavy.',level:1},
  {word:'history',phonetic:'ˈhɪstri',definition:'n. 历史',example:'I love history.',level:2},
  {word:'hold',phonetic:'həʊld',definition:'v. 握住，持有',example:'Hold my hand.',level:2},
  {word:'hope',phonetic:'həʊp',definition:'v./n. 希望',example:'I hope you feel better.',level:1},
  {word:'however',phonetic:'haʊˈevə',definition:'adv./conj. 然而，但是',example:'It is expensive. However, I want it.',level:3},
  {word:'human',phonetic:'ˈhjuːmən',definition:'adj. 人类的；n. 人',example:'Human beings are smart.',level:2},
  {word:'humor',phonetic:'ˈhjuːmə',definition:'n. 幽默，幽默感',example:'He has a great sense of humor.',level:3},
  {word:'hurt',phonetic:'hɜːt',definition:'v. 伤害，疼痛；adj. 受伤的',example:'My leg hurts.',level:1},
  // I
  {word:'imagine',phonetic:'ɪˈmædʒɪn',definition:'v. 想象，设想',example:'Imagine a better world.',level:3},
  {word:'important',phonetic:'ɪmˈpɔːtnt',definition:'adj. 重要的',example:'Health is important.',level:1},
  {word:'improve',phonetic:'ɪmˈpruːv',definition:'v. 改善，提高',example:'Improve your English.',level:2},
  {word:'include',phonetic:'ɪnˈkluːd',definition:'v. 包括，包含',example:'The price includes tax.',level:2},
  {word:'information',phonetic:'ˌɪnfəˈmeɪʃn',definition:'n. 信息，资料',example:'Find information online.',level:2},
  {word:'instead',phonetic:'ɪnˈsted',definition:'adv. 代替，而不是',example:'Use this instead.',level:2},
  {word:'internet',phonetic:'ˈɪntənet',definition:'n. 互联网，网络',example:'Search on the internet.',level:2},
  {word:'introduce',phonetic:'ˌɪntrəˈdjuːs',definition:'v. 介绍，引进',example:'Let me introduce myself.',level:2},
  {word:'invite',phonetic:'ɪnˈvaɪt',definition:'v. 邀请',example:'I invite you to my party.',level:1},
  {word:'island',phonetic:'ˈaɪlənd',definition:'n. 岛屿',example:'The island is beautiful.',level:2},
  // J
  {word:'joke',phonetic:'dʒəʊk',definition:'n./v. 笑话，开玩笑',example:'That\'s a good joke.',level:2},
  {word:'journey',phonetic:'ˈdʒɜːni',definition:'n. 旅行，旅程',example:'A long journey.',level:2},
  {word:'judge',phonetic:'dʒʌdʒ',definition:'v. 判断，评判；n. 法官',example:'Don\'t judge a book by its cover.',level:3},
  // K
  {word:'keep',phonetic:'kiːp',definition:'v. 保持，保留；继续',example:'Keep trying.',level:1},
  {word:'kill',phonetic:'kɪl',definition:'v. 杀死，消灭',example:'Pollution kills animals.',level:2},
  // L
  {word:'language',phonetic:'ˈlæŋɡwɪdʒ',definition:'n. 语言',example:'Learn a new language.',level:2},
  {word:'last',phonetic:'lɑːst',definition:'adj. 最后的；v. 持续；adv. 最近',example:'Last week.',level:1},
  {word:'laugh',phonetic:'lɑːf',definition:'v./n. 笑，大笑',example:'Make me laugh.',level:1},
  {word:'law',phonetic:'lɔː',definition:'n. 法律，定律',example:'Follow the law.',level:3},
  {word:'lazy',phonetic:'ˈleɪzi',definition:'adj. 懒惰的',example:'Don\'t be lazy.',level:2},
  {word:'lead',phonetic:'liːd',definition:'v. 领导，带领；n. 铅',example:'Lead the team.',level:2},
  {word:'learn',phonetic:'lɜːn',definition:'v. 学习，了解',example:'Learn from your mistakes.',level:1},
  {word:'leave',phonetic:'liːv',definition:'v. 离开，剩下；n. 假假',example:'Leave early.',level:1},
  {word:'lend',phonetic:'lend',definition:'v. 借出，借给',example:'Lend me a pen.',level:2},
  {word:'level',phonetic:'ˈlevl',definition:'n. 水平，级别',example:'What level are you?',level:2},
  {word:'lift',phonetic:'lɪft',definition:'v. 举起，抬起；n. 电梯',example:'Lift the box.',level:2},
  {word:'listen',phonetic:'ˈlɪsn',definition:'v. 听，倾听',example:'Listen carefully.',level:1},
  {word:'local',phonetic:'ˈləʊkl',definition:'adj. 本地的，当地的',example:'Local food is fresh.',level:3},
  {word:'lonely',phonetic:'ˈləʊnli',definition:'adj. 孤独的，寂寞的',example:'I feel lonely.',level:2},
  {word:'loud',phonetic:'laʊd',definition:'adj. 大声的，响亮的',example:'Don\'t be too loud.',level:2},
  // M
  {word:'main',phonetic:'meɪn',definition:'adj. 主要的，最重要的',example:'The main idea.',level:2},
  {word:'mean',phonetic:'miːn',definition:'v. 意味，意思是；adj. 吝啬的',example:'What do you mean?',level:1},
  {word:'meet',phonetic:'miːt',definition:'v. 见面，遇见',example:'Nice to meet you.',level:1},
  {word:'method',phonetic:'ˈmeθəd',definition:'n. 方法，方式',example:'A good study method.',level:3},
  {word:'mind',phonetic:'maɪnd',definition:'n. 头脑，心智；v. 在乎',example:'Keep it in mind.',level:2},
  {word:'miss',phonetic:'mɪs',definition:'v. 想念，错过；n. 小姐',example:'I miss my family.',level:1},
  {word:'modern',phonetic:'ˈmɒdn',definition:'adj. 现代的，当代的',example:'Modern technology.',level:3},
  {word:'moment',phonetic:'ˈməʊmənt',definition:'n. 片刻，时刻',example:'Just a moment.',level:2},
  {word:'money',phonetic:'ˈmʌni',definition:'n. 钱，金钱',example:'Money is important.',level:1},
  {word:'month',phonetic:'mʌnθ',definition:'n. 月份，月',example:'One month has about 30 days.',level:1},
  {word:'more',phonetic:'mɔː',definition:'adj./adv. 更多的，更多地',example:'I want more.',level:1},
  {word:'move',phonetic:'muːv',definition:'v. 移动，搬家；感动',example:'Move your chair.',level:1},
  {word:'movie',phonetic:'ˈmuːvi',definition:'n. 电影',example:'Let\'s watch a movie.',level:1},
  {word:'must',phonetic:'mʌst',definition:'modal v. 必须，一定',example:'You must study hard.',level:1},
  // N
  {word:'natural',phonetic:'ˈnætʃrəl',definition:'adj. 自然的，天然的',example:'Natural food is healthy.',level:3},
  {word:'nature',phonetic:'ˈneɪtʃə',definition:'n. 自然，大自然；性质',example:'Enjoy nature.',level:2},
  {word:'necessary',phonetic:'ˈnesəsəri',definition:'adj. 必要的，必需的',example:'Is it necessary?',level:3},
  {word:'need',phonetic:'niːd',definition:'v./n. 需要',example:'I need help.',level:1},
  {word:'neither',phonetic:'ˈnaɪðə',definition:'adj./pron. 两者都不',example:'Neither of them came.',level:3},
  {word:'nervous',phonetic:'ˈnɜːvəs',definition:'adj. 紧张的，不安的',example:'I feel nervous before exams.',level:2},
  {word:'nobody',phonetic:'ˈnəʊbədi',definition:'pron. 没有人',example:'Nobody answered.',level:2},
  {word:'normal',phonetic:'ˈnɔːml',definition:'adj. 正常的，普通的',example:'This is normal.',level:3},
  {word:'notice',phonetic:'ˈnəʊtɪs',definition:'v. 注意到；n. 通知',example:'Did you notice anything?',level:2},
  // O
  {word:'offer',phonetic:'ˈɒfə',definition:'v./n. 提供，提议',example:'I offer you help.',level:3},
  {word:'once',phonetic:'wʌns',definition:'adv. 曾经，一次；conj. 一旦',example:'Once upon a time.',level:2},
  {word:'only',phonetic:'ˈəʊnli',definition:'adj./adv. 只有，唯一的',example:'I have only one chance.',level:1},
  {word:'opinion',phonetic:'əˈpɪnjən',definition:'n. 意见，看法',example:'In my opinion, it\'s wrong.',level:3},
  {word:'opportunity',phonetic:'ˌɒpəˈtjuːnəti',definition:'n. 机会，良机',example:'A great opportunity.',level:3},
  {word:'order',phonetic:'ˈɔːdə',definition:'v./n. 命令，订购；顺序',example:'In order to succeed.',level:2},
  {word:'outside',phonetic:'ˌaʊtˈsaɪd',definition:'prep./adv. 外面，在外',example:'Go outside and play.',level:1},
  // P
  {word:'parent',phonetic:'ˈpeərənt',definition:'n. 父母之一',example:'My parents are strict.',level:1},
  {word:'pass',phonetic:'pɑːs',definition:'v. 通过，经过；传递',example:'Pass the ball.',level:1},
  {word:'past',phonetic:'pɑːst',definition:'n. 过去；adj. 过去的；prep. 经过',example:'In the past.',level:2},
  {word:'patient',phonetic:'ˈpeɪʃnt',definition:'adj. 有耐心的；n. 病人',example:'Be patient.',level:2},
  {word:'peace',phonetic:'piːs',definition:'n. 和平，平静',example:'World peace.',level:2},
  {word:'per',phonetic:'pɜː',definition:'prep. 每，每个',example:'50 km per hour.',level:2},
  {word:'perfect',phonetic:'ˈpɜːfɪkt',definition:'adj. 完美的，理想的',example:'Nobody is perfect.',level:2},
  {word:'perhaps',phonetic:'pəˈhæps',definition:'adv. 也许，可能',example:'Perhaps I was wrong.',level:2},
  {word:'phone',phonetic:'fəʊn',definition:'n. 电话；v. 打电话',example:'Answer the phone.',level:1},
  {word:'pick',phonetic:'pɪk',definition:'v. 采摘，挑选',example:'Pick a card.',level:1},
  {word:'planet',phonetic:'ˈplænɪt',definition:'n. 行星',example:'Earth is a planet.',level:2},
  {word:'plant',phonetic:'plɑːnt',definition:'n. 植物；v. 种植',example:'Plant a tree.',level:1},
  {word:'point',phonetic:'pɔɪnt',definition:'n. 点，要点；v. 指',example:'Point to the picture.',level:2},
  {word:'popular',phonetic:'ˈpɒpjələ',definition:'adj. 流行的，受欢迎的',example:'A popular song.',level:2},
  {word:'possible',phonetic:'ˈpɒsəbl',definition:'adj. 可能的',example:'Is it possible?',level:2},
  {word:'practice',phonetic:'ˈpræktɪs',definition:'n./v. 练习，实践',example:'Practice makes perfect.',level:2},
  {word:'prepare',phonetic:'prɪˈpeə',definition:'v. 准备，预备',example:'Prepare for the exam.',level:2},
  {word:'present',phonetic:'ˈpreznt',definition:'n. 礼物；adj. 当前的；v. 呈现',example:'I got a present.',level:2},
  {word:'price',phonetic:'praɪs',definition:'n. 价格，代价',example:'What\'s the price?',level:2},
  {word:'proud',phonetic:'praʊd',definition:'adj. 骄傲的，自豪的',example:'I am proud of you.',level:2},
  {word:'pull',phonetic:'pʊl',definition:'v./n. 拉，拖',example:'Pull the door.',level:1},
  {word:'push',phonetic:'pʊʃ',definition:'v./n. 推，推动',example:'Push the button.',level:1},
  // R
  {word:'raise',phonetic:'reɪz',definition:'v. 举起，提高；抚养',example:'Raise your hand.',level:2},
  {word:'reach',phonetic:'riːtʃ',definition:'v. 到达，够到',example:'Can you reach the shelf?',level:2},
  {word:'ready',phonetic:'ˈredi',definition:'adj. 准备好的',example:'Are you ready?',level:1},
  {word:'real',phonetic:'rɪəl',definition:'adj. 真实的，真正的',example:'Is this real?',level:1},
  {word:'reason',phonetic:'ˈriːzn',definition:'n. 原因，理由',example:'What\'s the reason?',level:2},
  {word:'receive',phonetic:'rɪˈsiːv',definition:'v. 收到，接受',example:'Receive a gift.',level:2},
  {word:'record',phonetic:'ˈrekɔːd',definition:'n. 记录；v. 录制',example:'Break a record.',level:3},
  {word:'refuse',phonetic:'rɪˈfjuːz',definition:'v. 拒绝',example:'She refused to help.',level:3},
  {word:'relax',phonetic:'rɪˈlæks',definition:'v. 放松，休息',example:'Relax and enjoy.',level:2},
  {word:'remember',phonetic:'rɪˈmembə',definition:'v. 记住，记得',example:'Remember my name.',level:1},
  {word:'repeat',phonetic:'rɪˈpiːt',definition:'v. 重复，重说',example:'Repeat after me.',level:1},
  {word:'reply',phonetic:'rɪˈplaɪ',definition:'v./n. 回答，答复',example:'Reply to my message.',level:2},
  {word:'report',phonetic:'rɪˈpɔːt',definition:'v./n. 报告，汇报',example:'Write a report.',level:2},
  {word:'respect',phonetic:'rɪˈspekt',definition:'v./n. 尊重，尊敬',example:'Respect your elders.',level:2},
  {word:'rest',phonetic:'rest',definition:'v./n. 休息；n. 剩余',example:'Take a rest.',level:1},
  {word:'result',phonetic:'rɪˈzʌlt',definition:'n. 结果，结局',example:'The exam result.',level:2},
  {word:'return',phonetic:'rɪˈtɜːn',definition:'v. 返回，归还',example:'Return the book.',level:2},
  {word:'rich',phonetic:'rɪtʃ',definition:'adj. 富有的；丰富的',example:'A rich country.',level:2},
  {word:'rise',phonetic:'raɪz',definition:'v. 升起，上升',example:'The sun rises in the east.',level:2},
  {word:'role',phonetic:'rəʊl',definition:'n. 角色，作用',example:'Play a role.',level:3},
  {word:'rule',phonetic:'ruːl',definition:'n. 规则，规定；v. 统治',example:'Follow the rules.',level:2},
  // S
  {word:'safe',phonetic:'seɪf',definition:'adj. 安全的',example:'Stay safe.',level:1},
  {word:'save',phonetic:'seɪv',definition:'v. 拯救；节省；保存',example:'Save the planet.',level:2},
  {word:'search',phonetic:'sɜːtʃ',definition:'v./n. 搜寻，查找',example:'Search online.',level:2},
  {word:'secret',phonetic:'ˈsiːkrɪt',definition:'n. 秘密；adj. 秘密的',example:'Keep a secret.',level:2},
  {word:'seem',phonetic:'siːm',definition:'v. 看起来，似乎',example:'You seem tired.',level:2},
  {word:'send',phonetic:'send',definition:'v. 发送，寄',example:'Send a letter.',level:1},
  {word:'serious',phonetic:'ˈsɪəriəs',definition:'adj. 严肃的，严重的',example:'This is serious.',level:2},
  {word:'share',phonetic:'ʃeə',definition:'v./n. 分享，共享',example:'Share your food.',level:2},
  {word:'shop',phonetic:'ʃɒp',definition:'n. 商店；v. 购物',example:'Go shopping.',level:1},
  {word:'should',phonetic:'ʃʊd',definition:'modal v. 应该',example:'You should rest.',level:1},
  {word:'show',phonetic:'ʃəʊ',definition:'v. 展示，显示；n. 演出',example:'Show me the way.',level:1},
  {word:'sign',phonetic:'saɪn',definition:'n. 迹象，标志；v. 签名',example:'A road sign.',level:2},
  {word:'simple',phonetic:'ˈsɪmpl',definition:'adj. 简单的，容易的',example:'It\'s simple.',level:2},
  {word:'since',phonetic:'sɪns',definition:'prep./conj. 从…以来，因为',example:'I\'ve been here since 9.',level:2},
  {word:'skill',phonetic:'skɪl',definition:'n. 技能，技巧',example:'A useful skill.',level:3},
  {word:'slowly',phonetic:'ˈsləʊli',definition:'adv. 缓慢地',example:'Walk slowly.',level:2},
  {word:'smart',phonetic:'smɑːt',definition:'adj. 聪明的；整洁的',example:'A smart student.',level:2},
  {word:'smell',phonetic:'smel',definition:'v./n. 闻，气味',example:'This smells nice.',level:2},
  {word:'smile',phonetic:'smaɪl',definition:'v./n. 微笑',example:'Smile at everyone.',level:1},
  {word:'solve',phonetic:'sɒlv',definition:'v. 解决，解答',example:'Solve the problem.',level:3},
  {word:'somewhere',phonetic:'ˈsʌmweə',definition:'adv. 某处，在某处',example:'Let\'s go somewhere nice.',level:2},
  {word:'soon',phonetic:'suːn',definition:'adv. 不久，很快',example:'See you soon.',level:1},
  {word:'sorry',phonetic:'ˈsɒri',definition:'adj. 对不起的；遗憾的',example:'I\'m sorry.',level:1},
  {word:'space',phonetic:'speɪs',definition:'n. 空间，太空',example:'Explore space.',level:2},
  {word:'spend',phonetic:'spend',definition:'v. 花费，度过',example:'Spend time with family.',level:2},
  {word:'spread',phonetic:'spred',definition:'v. 传播，蔓延',example:'Spread good news.',level:3},
  {word:'stand',phonetic:'stænd',definition:'v. 站立，忍受',example:'Stand up.',level:1},
  {word:'start',phonetic:'stɑːt',definition:'v./n. 开始，出发',example:'Start the engine.',level:1},
  {word:'stay',phonetic:'steɪ',definition:'v. 停留，留下',example:'Stay here.',level:1},
  {word:'step',phonetic:'step',definition:'n. 步骤，步伐；v. 踩',example:'One step at a time.',level:2},
  {word:'still',phonetic:'stɪl',definition:'adv. 还，仍然；adj. 静止的',example:'I still don\'t understand.',level:2},
  {word:'stop',phonetic:'stɒp',definition:'v./n. 停止，停止',example:'Stop right there.',level:1},
  {word:'story',phonetic:'ˈstɔːri',definition:'n. 故事，楼层',example:'Tell me a story.',level:1},
  {word:'strange',phonetic:'streɪndʒ',definition:'adj. 奇怪的，陌生的',example:'A strange sound.',level:2},
  {word:'subway',phonetic:'ˈsʌbweɪ',definition:'n. 地铁',example:'Take the subway.',level:2},
  {word:'succeed',phonetic:'səkˈsiːd',definition:'v. 成功，继承',example:'Work hard to succeed.',level:3},
  {word:'suddenly',phonetic:'ˈsʌdnli',definition:'adv. 突然地',example:'It suddenly rained.',level:2},
  {word:'suggest',phonetic:'səˈdʒest',definition:'v. 建议，提议',example:'I suggest we leave.',level:3},
  {word:'sunshine',phonetic:'ˈsʌnʃaɪn',definition:'n. 阳光',example:'Enjoy the sunshine.',level:2},
  {word:'support',phonetic:'səˈpɔːt',definition:'v./n. 支持，帮助',example:'Support each other.',level:3},
  {word:'sure',phonetic:'ʃʊə',definition:'adj. 确定的；adv. 当然',example:'Are you sure?',level:1},
  {word:'surprise',phonetic:'səˈpraɪz',definition:'n./v. 惊喜，使惊讶',example:'What a surprise!',level:2},
  // T
  {word:'take',phonetic:'teɪk',definition:'v. 拿，带；花费',example:'Take an umbrella.',level:1},
  {word:'task',phonetic:'tɑːsk',definition:'n. 任务，工作',example:'Complete the task.',level:3},
  {word:'taste',phonetic:'teɪst',definition:'v./n. 品尝，味道',example:'Taste the soup.',level:2},
  {word:'team',phonetic:'tiːm',definition:'n. 队，团队',example:'Work as a team.',level:2},
  {word:'technology',phonetic:'tekˈnɒlədʒi',definition:'n. 技术，科技',example:'Modern technology.',level:3},
  {word:'tell',phonetic:'tel',definition:'v. 告诉，讲述',example:'Tell me the truth.',level:1},
  {word:'test',phonetic:'test',definition:'n./v. 测验，考验',example:'Pass the test.',level:1},
  {word:'than',phonetic:'ðæn',definition:'conj. 比，与其',example:'She is taller than me.',level:1},
  {word:'though',phonetic:'ðəʊ',definition:'conj. 虽然，尽管',example:'Though tired, I continued.',level:2},
  {word:'thousand',phonetic:'ˈθaʊznd',definition:'num. 千，一千',example:'A thousand words.',level:2},
  {word:'through',phonetic:'θruː',definition:'prep. 穿过，通过',example:'Walk through the door.',level:2},
  {word:'throw',phonetic:'θrəʊ',definition:'v. 投，扔',example:'Throw the ball.',level:2},
  {word:'ticket',phonetic:'ˈtɪkɪt',definition:'n. 票，券',example:'Buy a ticket.',level:1},
  {word:'together',phonetic:'təˈɡeðə',definition:'adv. 一起，共同',example:'Work together.',level:1},
  {word:'top',phonetic:'tɒp',definition:'n. 顶部，最高处；adj. 最好的',example:'At the top.',level:2},
  {word:'touch',phonetic:'tʌtʃ',definition:'v./n. 触摸，感动',example:'Don\'t touch that.',level:2},
  {word:'toward',phonetic:'təˈwɔːd',definition:'prep. 朝向，对于',example:'Walk toward the light.',level:3},
  {word:'true',phonetic:'truː',definition:'adj. 真实的，正确的',example:'Is it true?',level:1},
  {word:'trust',phonetic:'trʌst',definition:'v./n. 信任，相信',example:'I trust you.',level:2},
  {word:'try',phonetic:'traɪ',definition:'v. 尝试，努力',example:'Try your best.',level:1},
  {word:'turn',phonetic:'tɜːn',definition:'v. 转，转动；n. 轮流',example:'Turn left.',level:1},
  {word:'type',phonetic:'taɪp',definition:'n. 类型；v. 打字',example:'What type is it?',level:2},
  // U
  {word:'uncle',phonetic:'ˈʌŋkl',definition:'n. 叔叔，伯伯，舅舅',example:'My uncle is funny.',level:1},
  {word:'understand',phonetic:'ˌʌndəˈstænd',definition:'v. 理解，明白',example:'I understand.',level:1},
  {word:'until',phonetic:'ənˈtɪl',definition:'prep./conj. 直到，到…时',example:'Wait until I come back.',level:2},
  {word:'usually',phonetic:'ˈjuːʒuəli',definition:'adv. 通常，一般',example:'I usually wake up at 7.',level:1},
  // V
  {word:'voice',phonetic:'vɔɪs',definition:'n. 嗓音，声音',example:'She has a sweet voice.',level:2},
  {word:'volunteer',phonetic:'ˌvɒlənˈtɪə',definition:'n./v. 志愿者，自愿',example:'Volunteer to help.',level:3},
  // W
  {word:'wake',phonetic:'weɪk',definition:'v. 醒来，唤醒',example:'Wake up early.',level:1},
  {word:'warm',phonetic:'wɔːm',definition:'adj. 温暖的，热情的',example:'A warm welcome.',level:1},
  {word:'waste',phonetic:'weɪst',definition:'v./n. 浪费',example:'Don\'t waste water.',level:2},
  {word:'watch',phonetic:'wɒtʃ',definition:'v. 观看；n. 手表',example:'Watch a movie.',level:1},
  {word:'way',phonetic:'weɪ',definition:'n. 方式，方法；路',example:'Find a way.',level:1},
  {word:'well',phonetic:'wel',definition:'adv. 好，令人满意地；adj. 健康的',example:'I am doing well.',level:1},
  {word:'while',phonetic:'waɪl',definition:'conj. 当…时；n. 一会儿',example:'While I was cooking.',level:2},
  {word:'wide',phonetic:'waɪd',definition:'adj. 宽的，宽阔的',example:'A wide road.',level:2},
  {word:'win',phonetic:'wɪn',definition:'v./n. 赢，获胜',example:'Win the game.',level:1},
  {word:'wish',phonetic:'wɪʃ',definition:'v./n. 希望，祝愿',example:'I wish you luck.',level:1},
  {word:'wonder',phonetic:'ˈwʌndə',definition:'v. 想知道；n. 奇迹',example:'I wonder why.',level:2},
  {word:'wonderful',phonetic:'ˈwʌndəfl',definition:'adj. 精彩的，美好的',example:'Wonderful performance!',level:2},
  {word:'worry',phonetic:'ˈwʌri',definition:'v./n. 担心，烦恼',example:'Don\'t worry.',level:1},
  {word:'worth',phonetic:'wɜːθ',definition:'adj. 值得的；n. 价值',example:'Is it worth it?',level:3},
  {word:'wrong',phonetic:'rɒŋ',definition:'adj. 错误的；adv. 错误地',example:'You are wrong.',level:1},
  // Y
  {word:'yet',phonetic:'jet',definition:'adv. 还，尚未；conj. 然而',example:'Is he here yet?',level:2},
  {word:'yourself',phonetic:'jɔːˈself',definition:'pron. 你自己',example:'Do it yourself.',level:2},
];
