// 小学英语词库 — 义务教育1-6年级核心词汇，共600词
// level: 1=1-2年级, 2=3-4年级, 3=5-6年级
const PRIMARY_WORDS = [
  // A
  {word:'a',phonetic:'eɪ',definition:'art. 一（个）；某一',example:'I have a cat.',level:1},
  {word:'apple',phonetic:'ˈæpl',definition:'n. 苹果',example:'I like apples.',level:1},
  {word:'and',phonetic:'ænd',definition:'conj. 和，与',example:'Tom and Jerry are friends.',level:1},
  {word:'am',phonetic:'æm',definition:'v. be的第一人称单数现在式',example:'I am a student.',level:1},
  {word:'are',phonetic:'ɑː',definition:'v. be的第二人称及复数现在式',example:'We are happy.',level:1},
  {word:'ant',phonetic:'ænt',definition:'n. 蚂蚁',example:'The ant is small.',level:1},
  {word:'about',phonetic:'əˈbaʊt',definition:'prep. 关于；大约',example:'Tell me about your family.',level:2},
  {word:'after',phonetic:'ˈɑːftə',definition:'prep. 在…之后',example:'After school, I go home.',level:2},
  {word:'afternoon',phonetic:'ˌɑːftəˈnuːn',definition:'n. 下午',example:'Good afternoon!',level:2},
  {word:'again',phonetic:'əˈɡen',definition:'adv. 再次，又',example:'Say it again, please.',level:2},
  {word:'age',phonetic:'eɪdʒ',definition:'n. 年龄',example:'How old are you? My age is 10.',level:2},
  {word:'animal',phonetic:'ˈænɪml',definition:'n. 动物',example:'A dog is an animal.',level:2},
  {word:'ask',phonetic:'ɑːsk',definition:'v. 问，询问',example:'Please ask the teacher.',level:2},
  {word:'also',phonetic:'ˈɔːlsəʊ',definition:'adv. 也，同样',example:'I also like swimming.',level:3},
  {word:'autumn',phonetic:'ˈɔːtəm',definition:'n. 秋天',example:'Autumn is cool.',level:3},
  {word:'above',phonetic:'əˈbʌv',definition:'prep. 在…上面',example:'The bird is above the tree.',level:3},
  // B
  {word:'bag',phonetic:'bæɡ',definition:'n. 包，袋',example:'My bag is red.',level:1},
  {word:'ball',phonetic:'bɔːl',definition:'n. 球',example:'I kick the ball.',level:1},
  {word:'banana',phonetic:'bəˈnɑːnə',definition:'n. 香蕉',example:'Monkeys love bananas.',level:1},
  {word:'big',phonetic:'bɪɡ',definition:'adj. 大的',example:'This is a big house.',level:1},
  {word:'bird',phonetic:'bɜːd',definition:'n. 鸟',example:'The bird sings.',level:1},
  {word:'black',phonetic:'blæk',definition:'adj. 黑色的',example:'My cat is black.',level:1},
  {word:'blue',phonetic:'bluː',definition:'adj. 蓝色的',example:'The sky is blue.',level:1},
  {word:'book',phonetic:'bʊk',definition:'n. 书',example:'I read a book.',level:1},
  {word:'boy',phonetic:'bɔɪ',definition:'n. 男孩',example:'The boy plays football.',level:1},
  {word:'bread',phonetic:'bred',definition:'n. 面包',example:'I eat bread for breakfast.',level:1},
  {word:'breakfast',phonetic:'ˈbrekfəst',definition:'n. 早餐',example:'We have breakfast at 7.',level:2},
  {word:'brother',phonetic:'ˈbrʌðə',definition:'n. 兄弟',example:'My brother is ten.',level:2},
  {word:'bus',phonetic:'bʌs',definition:'n. 公共汽车',example:'I go to school by bus.',level:2},
  {word:'busy',phonetic:'ˈbɪzi',definition:'adj. 忙的',example:'My mother is busy.',level:2},
  {word:'but',phonetic:'bʌt',definition:'conj. 但是',example:'I like cats but not dogs.',level:2},
  {word:'buy',phonetic:'baɪ',definition:'v. 买',example:'I want to buy a pen.',level:2},
  {word:'bedroom',phonetic:'ˈbedruːm',definition:'n. 卧室',example:'My bedroom is small.',level:3},
  {word:'below',phonetic:'bɪˈləʊ',definition:'prep. 在…下面',example:'The fish is below the water.',level:3},
  {word:'between',phonetic:'bɪˈtwiːn',definition:'prep. 在…之间',example:'The cat is between the boxes.',level:3},
  // C
  {word:'can',phonetic:'kæn',definition:'modal v. 能，会',example:'I can swim.',level:1},
  {word:'cat',phonetic:'kæt',definition:'n. 猫',example:'My cat is white.',level:1},
  {word:'chair',phonetic:'tʃeə',definition:'n. 椅子',example:'Sit on the chair.',level:1},
  {word:'class',phonetic:'klɑːs',definition:'n. 班级；课',example:'I am in Class 3.',level:1},
  {word:'clean',phonetic:'kliːn',definition:'adj. 干净的；v. 打扫',example:'Clean the room.',level:1},
  {word:'cold',phonetic:'kəʊld',definition:'adj. 冷的',example:'It is cold today.',level:1},
  {word:'colour',phonetic:'ˈkʌlə',definition:'n. 颜色',example:'What colour is it?',level:1},
  {word:'come',phonetic:'kʌm',definition:'v. 来',example:'Come here, please.',level:1},
  {word:'cow',phonetic:'kaʊ',definition:'n. 奶牛',example:'The cow eats grass.',level:1},
  {word:'cook',phonetic:'kʊk',definition:'v. 做饭；n. 厨师',example:'My mum can cook well.',level:2},
  {word:'city',phonetic:'ˈsɪti',definition:'n. 城市',example:'I live in a big city.',level:2},
  {word:'clock',phonetic:'klɒk',definition:'n. 时钟',example:'The clock is on the wall.',level:2},
  {word:'cloud',phonetic:'klaʊd',definition:'n. 云',example:'The cloud is white.',level:2},
  {word:'coat',phonetic:'kəʊt',definition:'n. 外套',example:'Put on your coat.',level:2},
  {word:'computer',phonetic:'kəmˈpjuːtə',definition:'n. 计算机',example:'I use a computer.',level:2},
  {word:'country',phonetic:'ˈkʌntri',definition:'n. 国家；农村',example:'China is my country.',level:3},
  {word:'carry',phonetic:'ˈkæri',definition:'v. 携带，搬运',example:'Can you carry this box?',level:3},
  {word:'climb',phonetic:'klaɪm',definition:'v. 爬，攀登',example:'Cats can climb trees.',level:3},
  // D
  {word:'dad',phonetic:'dæd',definition:'n. 爸爸',example:'My dad is tall.',level:1},
  {word:'day',phonetic:'deɪ',definition:'n. 天，日',example:'Today is a good day.',level:1},
  {word:'desk',phonetic:'desk',definition:'n. 书桌',example:'My book is on the desk.',level:1},
  {word:'dog',phonetic:'dɒɡ',definition:'n. 狗',example:'The dog barks.',level:1},
  {word:'door',phonetic:'dɔː',definition:'n. 门',example:'Open the door.',level:1},
  {word:'drink',phonetic:'drɪŋk',definition:'v. 喝',example:'I drink water.',level:1},
  {word:'duck',phonetic:'dʌk',definition:'n. 鸭子',example:'The duck swims.',level:1},
  {word:'dinner',phonetic:'ˈdɪnə',definition:'n. 晚餐，正餐',example:'We have dinner at 6.',level:2},
  {word:'draw',phonetic:'drɔː',definition:'v. 画；拉',example:'I can draw a cat.',level:2},
  {word:'dream',phonetic:'driːm',definition:'n./v. 梦；做梦',example:'I had a sweet dream.',level:2},
  {word:'dress',phonetic:'dres',definition:'n. 连衣裙；v. 穿衣',example:'She wears a red dress.',level:2},
  {word:'dance',phonetic:'dɑːns',definition:'v./n. 跳舞，舞蹈',example:'I love to dance.',level:3},
  {word:'difficult',phonetic:'ˈdɪfɪkəlt',definition:'adj. 困难的',example:'This is a difficult question.',level:3},
  // E
  {word:'eat',phonetic:'iːt',definition:'v. 吃',example:'I eat rice.',level:1},
  {word:'egg',phonetic:'eɡ',definition:'n. 鸡蛋',example:'I eat an egg.',level:1},
  {word:'eye',phonetic:'aɪ',definition:'n. 眼睛',example:'I have two eyes.',level:1},
  {word:'ear',phonetic:'ɪə',definition:'n. 耳朵',example:'Rabbits have big ears.',level:1},
  {word:'eight',phonetic:'eɪt',definition:'num. 八',example:'I have eight books.',level:1},
  {word:'evening',phonetic:'ˈiːvnɪŋ',definition:'n. 傍晚，夜晚',example:'Good evening!',level:2},
  {word:'every',phonetic:'ˈevri',definition:'adj. 每，每个',example:'I read every day.',level:2},
  {word:'exercise',phonetic:'ˈeksəsaɪz',definition:'n. 练习；运动',example:'Do exercise every day.',level:3},
  {word:'easy',phonetic:'ˈiːzi',definition:'adj. 容易的',example:'This is easy.',level:3},
  // F
  {word:'face',phonetic:'feɪs',definition:'n. 脸，面部',example:'Wash your face.',level:1},
  {word:'family',phonetic:'ˈfæməli',definition:'n. 家庭，家人',example:'I love my family.',level:1},
  {word:'fast',phonetic:'fɑːst',definition:'adj./adv. 快的，快地',example:'He runs fast.',level:1},
  {word:'fat',phonetic:'fæt',definition:'adj. 胖的',example:'The pig is fat.',level:1},
  {word:'fish',phonetic:'fɪʃ',definition:'n. 鱼',example:'I eat fish.',level:1},
  {word:'five',phonetic:'faɪv',definition:'num. 五',example:'I have five cats.',level:1},
  {word:'flower',phonetic:'ˈflaʊə',definition:'n. 花',example:'I like flowers.',level:1},
  {word:'fly',phonetic:'flaɪ',definition:'v. 飞',example:'Birds can fly.',level:1},
  {word:'food',phonetic:'fuːd',definition:'n. 食物',example:'I like Chinese food.',level:1},
  {word:'four',phonetic:'fɔː',definition:'num. 四',example:'I have four books.',level:1},
  {word:'friend',phonetic:'frend',definition:'n. 朋友',example:'She is my best friend.',level:1},
  {word:'frog',phonetic:'frɒɡ',definition:'n. 青蛙',example:'The frog jumps.',level:1},
  {word:'fruit',phonetic:'fruːt',definition:'n. 水果',example:'Eat more fruit.',level:2},
  {word:'father',phonetic:'ˈfɑːðə',definition:'n. 父亲',example:'My father is a teacher.',level:2},
  {word:'favourite',phonetic:'ˈfeɪvərɪt',definition:'adj. 最喜爱的',example:'Blue is my favourite colour.',level:2},
  {word:'flag',phonetic:'flæɡ',definition:'n. 旗帜',example:'The national flag is red.',level:2},
  {word:'forest',phonetic:'ˈfɒrɪst',definition:'n. 森林',example:'There are many trees in the forest.',level:3},
  {word:'far',phonetic:'fɑː',definition:'adj./adv. 远的，远地',example:'Is the school far?',level:3},
  // G
  {word:'game',phonetic:'ɡeɪm',definition:'n. 游戏；比赛',example:'I like computer games.',level:1},
  {word:'get',phonetic:'ɡet',definition:'v. 得到；变得',example:'Get up early.',level:1},
  {word:'girl',phonetic:'ɡɜːl',definition:'n. 女孩',example:'The girl is pretty.',level:1},
  {word:'give',phonetic:'ɡɪv',definition:'v. 给',example:'Give me a book.',level:1},
  {word:'go',phonetic:'ɡəʊ',definition:'v. 去',example:'I go to school by bus.',level:1},
  {word:'good',phonetic:'ɡʊd',definition:'adj. 好的',example:'Good morning!',level:1},
  {word:'grape',phonetic:'ɡreɪp',definition:'n. 葡萄',example:'I like grapes.',level:1},
  {word:'green',phonetic:'ɡriːn',definition:'adj. 绿色的',example:'The grass is green.',level:1},
  {word:'garden',phonetic:'ˈɡɑːdn',definition:'n. 花园',example:'There are flowers in the garden.',level:2},
  {word:'glasses',phonetic:'ˈɡlɑːsɪz',definition:'n. 眼镜',example:'I wear glasses.',level:2},
  {word:'grass',phonetic:'ɡrɑːs',definition:'n. 草',example:'The grass is green.',level:2},
  {word:'ground',phonetic:'ɡraʊnd',definition:'n. 地面',example:'Sit on the ground.',level:3},
  // H
  {word:'hand',phonetic:'hænd',definition:'n. 手',example:'Raise your hand.',level:1},
  {word:'happy',phonetic:'ˈhæpi',definition:'adj. 快乐的，高兴的',example:'I am very happy.',level:1},
  {word:'have',phonetic:'hæv',definition:'v. 有；吃',example:'I have a dog.',level:1},
  {word:'he',phonetic:'hiː',definition:'pron. 他',example:'He is my brother.',level:1},
  {word:'head',phonetic:'hed',definition:'n. 头',example:'My head hurts.',level:1},
  {word:'help',phonetic:'help',definition:'v./n. 帮助',example:'Can you help me?',level:1},
  {word:'her',phonetic:'hɜː',definition:'pron. 她的；她（宾格）',example:'This is her book.',level:1},
  {word:'here',phonetic:'hɪə',definition:'adv. 这里',example:'Come here.',level:1},
  {word:'his',phonetic:'hɪz',definition:'pron. 他的',example:'This is his pen.',level:1},
  {word:'hot',phonetic:'hɒt',definition:'adj. 热的',example:'The soup is hot.',level:1},
  {word:'house',phonetic:'haʊs',definition:'n. 房子',example:'This is my house.',level:1},
  {word:'hungry',phonetic:'ˈhʌŋɡri',definition:'adj. 饥饿的',example:'I am hungry.',level:2},
  {word:'homework',phonetic:'ˈhəʊmwɜːk',definition:'n. 家庭作业',example:'Do your homework.',level:2},
  {word:'holiday',phonetic:'ˈhɒlədeɪ',definition:'n. 假日，节日',example:'I love holidays.',level:2},
  {word:'horse',phonetic:'hɔːs',definition:'n. 马',example:'The horse runs fast.',level:2},
  {word:'hill',phonetic:'hɪl',definition:'n. 小山，丘陵',example:'They climbed the hill.',level:3},
  // I
  {word:'I',phonetic:'aɪ',definition:'pron. 我',example:'I am a student.',level:1},
  {word:'in',phonetic:'ɪn',definition:'prep. 在…里面',example:'The book is in the bag.',level:1},
  {word:'is',phonetic:'ɪz',definition:'v. be的第三人称单数',example:'She is a teacher.',level:1},
  {word:'it',phonetic:'ɪt',definition:'pron. 它',example:'It is a cat.',level:1},
  {word:'ice',phonetic:'aɪs',definition:'n. 冰',example:'The ice is cold.',level:2},
  {word:'idea',phonetic:'aɪˈdɪə',definition:'n. 主意，想法',example:'Good idea!',level:3},
  {word:'interest',phonetic:'ˈɪntrəst',definition:'n. 兴趣；v. 使感兴趣',example:'I have an interest in music.',level:3},
  // J
  {word:'jump',phonetic:'dʒʌmp',definition:'v./n. 跳',example:'Can you jump high?',level:1},
  {word:'juice',phonetic:'dʒuːs',definition:'n. 果汁',example:'Orange juice is sweet.',level:1},
  {word:'jacket',phonetic:'ˈdʒækɪt',definition:'n. 夹克',example:'Wear your jacket.',level:2},
  {word:'job',phonetic:'dʒɒb',definition:'n. 工作，职业',example:'My dad has a good job.',level:3},
  // K
  {word:'key',phonetic:'kiː',definition:'n. 钥匙；关键',example:'I lost my key.',level:2},
  {word:'kind',phonetic:'kaɪnd',definition:'adj. 和蔼的；n. 种类',example:'She is very kind.',level:2},
  {word:'kitchen',phonetic:'ˈkɪtʃɪn',definition:'n. 厨房',example:'Mum is in the kitchen.',level:2},
  {word:'know',phonetic:'nəʊ',definition:'v. 知道，了解',example:'I know the answer.',level:2},
  // L
  {word:'leg',phonetic:'leɡ',definition:'n. 腿',example:'The table has four legs.',level:1},
  {word:'like',phonetic:'laɪk',definition:'v. 喜欢；prep. 像',example:'I like dogs.',level:1},
  {word:'little',phonetic:'ˈlɪtl',definition:'adj. 小的；少量的',example:'A little bird sang.',level:1},
  {word:'live',phonetic:'lɪv',definition:'v. 住，生活',example:'I live in Beijing.',level:1},
  {word:'long',phonetic:'lɒŋ',definition:'adj. 长的',example:'The river is long.',level:1},
  {word:'look',phonetic:'lʊk',definition:'v. 看，看起来',example:'Look at the sky.',level:1},
  {word:'love',phonetic:'lʌv',definition:'v./n. 爱，热爱',example:'I love my family.',level:1},
  {word:'lunch',phonetic:'lʌntʃ',definition:'n. 午餐',example:'I have lunch at noon.',level:2},
  {word:'lake',phonetic:'leɪk',definition:'n. 湖',example:'The lake is beautiful.',level:2},
  {word:'leaf',phonetic:'liːf',definition:'n. 叶子',example:'The leaves are yellow.',level:2},
  {word:'letter',phonetic:'ˈletə',definition:'n. 字母；信',example:'Write a letter.',level:2},
  {word:'lesson',phonetic:'ˈlesn',definition:'n. 课，功课',example:'Today we have a maths lesson.',level:2},
  {word:'library',phonetic:'ˈlaɪbrəri',definition:'n. 图书馆',example:'I go to the library.',level:3},
  // M
  {word:'make',phonetic:'meɪk',definition:'v. 制作；使',example:'I make a cake.',level:1},
  {word:'man',phonetic:'mæn',definition:'n. 男人',example:'The man is tall.',level:1},
  {word:'map',phonetic:'mæp',definition:'n. 地图',example:'Look at the map.',level:1},
  {word:'me',phonetic:'miː',definition:'pron. 我（宾格）',example:'Help me, please.',level:1},
  {word:'milk',phonetic:'mɪlk',definition:'n. 牛奶',example:'I drink milk.',level:1},
  {word:'mum',phonetic:'mʌm',definition:'n. 妈妈',example:'My mum is nice.',level:1},
  {word:'monkey',phonetic:'ˈmʌŋki',definition:'n. 猴子',example:'The monkey climbs a tree.',level:1},
  {word:'moon',phonetic:'muːn',definition:'n. 月亮',example:'The moon is round.',level:1},
  {word:'morning',phonetic:'ˈmɔːnɪŋ',definition:'n. 早晨',example:'Good morning!',level:1},
  {word:'mouth',phonetic:'maʊθ',definition:'n. 嘴巴',example:'Open your mouth.',level:1},
  {word:'music',phonetic:'ˈmjuːzɪk',definition:'n. 音乐',example:'I love music.',level:2},
  {word:'mountain',phonetic:'ˈmaʊntɪn',definition:'n. 山',example:'The mountain is high.',level:2},
  {word:'match',phonetic:'mætʃ',definition:'n. 比赛；火柴；v. 搭配',example:'We win the match.',level:3},
  {word:'message',phonetic:'ˈmesɪdʒ',definition:'n. 信息，短信',example:'Send me a message.',level:3},
  // N
  {word:'name',phonetic:'neɪm',definition:'n. 名字',example:'My name is Lily.',level:1},
  {word:'nice',phonetic:'naɪs',definition:'adj. 好的，令人愉快的',example:'What a nice day!',level:1},
  {word:'nine',phonetic:'naɪn',definition:'num. 九',example:'I have nine books.',level:1},
  {word:'nose',phonetic:'nəʊz',definition:'n. 鼻子',example:'I have a small nose.',level:1},
  {word:'not',phonetic:'nɒt',definition:'adv. 不，没有',example:'I do not like snakes.',level:1},
  {word:'now',phonetic:'naʊ',definition:'adv. 现在',example:'What time is it now?',level:1},
  {word:'night',phonetic:'naɪt',definition:'n. 夜晚',example:'Good night!',level:2},
  {word:'new',phonetic:'njuː',definition:'adj. 新的',example:'I have a new pen.',level:2},
  {word:'next',phonetic:'nekst',definition:'adj./adv. 下一个；其次',example:'Next time, try harder.',level:2},
  {word:'near',phonetic:'nɪə',definition:'prep./adj. 近，在…附近',example:'The school is near my home.',level:3},
  // O
  {word:'old',phonetic:'əʊld',definition:'adj. 老的；旧的',example:'He is an old man.',level:1},
  {word:'on',phonetic:'ɒn',definition:'prep. 在…上面',example:'The cup is on the table.',level:1},
  {word:'one',phonetic:'wʌn',definition:'num. 一',example:'I have one brother.',level:1},
  {word:'open',phonetic:'ˈəʊpən',definition:'v. 打开；adj. 开着的',example:'Open the window.',level:1},
  {word:'orange',phonetic:'ˈɒrɪndʒ',definition:'n. 橙子；adj. 橙色的',example:'I eat an orange.',level:1},
  {word:'our',phonetic:'aʊə',definition:'pron. 我们的',example:'This is our school.',level:1},
  {word:'office',phonetic:'ˈɒfɪs',definition:'n. 办公室',example:'My dad works in an office.',level:2},
  {word:'other',phonetic:'ˈʌðə',definition:'adj. 其他的',example:'The other students are quiet.',level:2},
  {word:'often',phonetic:'ˈɒfn',definition:'adv. 经常，常常',example:'I often go to the park.',level:3},
  // P
  {word:'pencil',phonetic:'ˈpensl',definition:'n. 铅笔',example:'I write with a pencil.',level:1},
  {word:'pig',phonetic:'pɪɡ',definition:'n. 猪',example:'The pig is pink.',level:1},
  {word:'pink',phonetic:'pɪŋk',definition:'adj. 粉红色的',example:'She likes pink.',level:1},
  {word:'play',phonetic:'pleɪ',definition:'v. 玩；演奏',example:'I play football.',level:1},
  {word:'please',phonetic:'pliːz',definition:'adv. 请',example:'Please sit down.',level:1},
  {word:'purple',phonetic:'ˈpɜːpl',definition:'adj. 紫色的',example:'She wears a purple skirt.',level:1},
  {word:'put',phonetic:'pʊt',definition:'v. 放，放置',example:'Put the book on the desk.',level:2},
  {word:'park',phonetic:'pɑːk',definition:'n. 公园',example:'I go to the park.',level:2},
  {word:'people',phonetic:'ˈpiːpl',definition:'n. 人，人们',example:'Many people live here.',level:2},
  {word:'photo',phonetic:'ˈfəʊtəʊ',definition:'n. 照片',example:'Take a photo.',level:2},
  {word:'place',phonetic:'pleɪs',definition:'n. 地方，地点',example:'This is a nice place.',level:3},
  {word:'plan',phonetic:'plæn',definition:'n./v. 计划',example:'I have a plan.',level:3},
  {word:'problem',phonetic:'ˈprɒbləm',definition:'n. 问题，难题',example:'No problem!',level:3},
  // Q
  {word:'quiet',phonetic:'ˈkwaɪət',definition:'adj. 安静的',example:'Please be quiet.',level:2},
  {word:'question',phonetic:'ˈkwestʃən',definition:'n. 问题',example:'Answer the question.',level:2},
  {word:'quickly',phonetic:'ˈkwɪkli',definition:'adv. 快速地',example:'Come quickly.',level:3},
  // R
  {word:'rabbit',phonetic:'ˈræbɪt',definition:'n. 兔子',example:'The rabbit is white.',level:1},
  {word:'rain',phonetic:'reɪn',definition:'n./v. 雨；下雨',example:'It rains today.',level:1},
  {word:'read',phonetic:'riːd',definition:'v. 读，阅读',example:'I read books.',level:1},
  {word:'red',phonetic:'red',definition:'adj. 红色的',example:'The rose is red.',level:1},
  {word:'right',phonetic:'raɪt',definition:'adj. 对的；右边的',example:'Turn right.',level:1},
  {word:'run',phonetic:'rʌn',definition:'v. 跑',example:'I can run fast.',level:1},
  {word:'ruler',phonetic:'ˈruːlə',definition:'n. 尺子',example:'Use a ruler to draw.',level:2},
  {word:'rice',phonetic:'raɪs',definition:'n. 米，米饭',example:'I eat rice every day.',level:2},
  {word:'river',phonetic:'ˈrɪvə',definition:'n. 河流',example:'The river is long.',level:2},
  {word:'road',phonetic:'rəʊd',definition:'n. 路，道路',example:'Cross the road carefully.',level:2},
  {word:'room',phonetic:'ruːm',definition:'n. 房间',example:'Clean your room.',level:2},
  {word:'round',phonetic:'raʊnd',definition:'adj. 圆的',example:'The earth is round.',level:3},
  // S
  {word:'sad',phonetic:'sæd',definition:'adj. 伤心的',example:'I am sad today.',level:1},
  {word:'say',phonetic:'seɪ',definition:'v. 说',example:'What did you say?',level:1},
  {word:'see',phonetic:'siː',definition:'v. 看见',example:'I can see the sun.',level:1},
  {word:'she',phonetic:'ʃiː',definition:'pron. 她',example:'She is my sister.',level:1},
  {word:'sheep',phonetic:'ʃiːp',definition:'n. 羊',example:'The sheep eats grass.',level:1},
  {word:'shirt',phonetic:'ʃɜːt',definition:'n. 衬衫',example:'He wears a white shirt.',level:1},
  {word:'shoe',phonetic:'ʃuː',definition:'n. 鞋子',example:'Put on your shoes.',level:1},
  {word:'short',phonetic:'ʃɔːt',definition:'adj. 矮的；短的',example:'She is short.',level:1},
  {word:'sit',phonetic:'sɪt',definition:'v. 坐',example:'Sit down, please.',level:1},
  {word:'six',phonetic:'sɪks',definition:'num. 六',example:'I have six apples.',level:1},
  {word:'sleep',phonetic:'sliːp',definition:'v./n. 睡觉',example:'I sleep eight hours.',level:1},
  {word:'small',phonetic:'smɔːl',definition:'adj. 小的',example:'The mouse is small.',level:1},
  {word:'snow',phonetic:'snəʊ',definition:'n./v. 雪；下雪',example:'It snows in winter.',level:1},
  {word:'sofa',phonetic:'ˈsəʊfə',definition:'n. 沙发',example:'Sit on the sofa.',level:1},
  {word:'song',phonetic:'sɒŋ',definition:'n. 歌曲',example:'I sing a song.',level:1},
  {word:'sorry',phonetic:'ˈsɒri',definition:'adj. 对不起的；遗憾的',example:'I am sorry.',level:1},
  {word:'speak',phonetic:'spiːk',definition:'v. 说话',example:'Can you speak English?',level:2},
  {word:'spring',phonetic:'sprɪŋ',definition:'n. 春天；弹簧',example:'Spring is warm.',level:2},
  {word:'star',phonetic:'stɑː',definition:'n. 星星',example:'The stars are bright.',level:2},
  {word:'strong',phonetic:'strɒŋ',definition:'adj. 强壮的',example:'He is strong.',level:2},
  {word:'student',phonetic:'ˈstjuːdnt',definition:'n. 学生',example:'I am a student.',level:2},
  {word:'study',phonetic:'ˈstʌdi',definition:'v./n. 学习，书房',example:'I study hard.',level:2},
  {word:'summer',phonetic:'ˈsʌmə',definition:'n. 夏天',example:'Summer is hot.',level:2},
  {word:'sun',phonetic:'sʌn',definition:'n. 太阳',example:'The sun shines.',level:2},
  {word:'swim',phonetic:'swɪm',definition:'v. 游泳',example:'Fish can swim.',level:2},
  {word:'school',phonetic:'skuːl',definition:'n. 学校',example:'I go to school.',level:2},
  {word:'second',phonetic:'ˈsekənd',definition:'num. 第二；n. 秒',example:'I am second.',level:3},
  {word:'science',phonetic:'ˈsaɪəns',definition:'n. 科学',example:'I like science.',level:3},
  {word:'street',phonetic:'striːt',definition:'n. 街道',example:'She lives on this street.',level:3},
  {word:'subject',phonetic:'ˈsʌbdʒɪkt',definition:'n. 科目；主题',example:'My favourite subject is art.',level:3},
  // T
  {word:'table',phonetic:'ˈteɪbl',definition:'n. 桌子',example:'The table is wooden.',level:1},
  {word:'tall',phonetic:'tɔːl',definition:'adj. 高的',example:'He is tall.',level:1},
  {word:'teacher',phonetic:'ˈtiːtʃə',definition:'n. 老师',example:'My teacher is kind.',level:1},
  {word:'ten',phonetic:'ten',definition:'num. 十',example:'I am ten years old.',level:1},
  {word:'thank',phonetic:'θæŋk',definition:'v. 感谢',example:'Thank you.',level:1},
  {word:'that',phonetic:'ðæt',definition:'pron./adj. 那，那个',example:'That is my book.',level:1},
  {word:'the',phonetic:'ðə',definition:'art. 这，那（定冠词）',example:'The cat is cute.',level:1},
  {word:'thin',phonetic:'θɪn',definition:'adj. 瘦的；薄的',example:'She is thin.',level:1},
  {word:'think',phonetic:'θɪŋk',definition:'v. 想，认为',example:'I think it is right.',level:1},
  {word:'three',phonetic:'θriː',definition:'num. 三',example:'I have three books.',level:1},
  {word:'tiger',phonetic:'ˈtaɪɡə',definition:'n. 老虎',example:'The tiger is strong.',level:1},
  {word:'time',phonetic:'taɪm',definition:'n. 时间；次',example:'What time is it?',level:1},
  {word:'today',phonetic:'təˈdeɪ',definition:'adv./n. 今天',example:'Today is Monday.',level:1},
  {word:'too',phonetic:'tuː',definition:'adv. 也；太',example:'I can swim, too.',level:1},
  {word:'tree',phonetic:'triː',definition:'n. 树',example:'The tree is tall.',level:1},
  {word:'two',phonetic:'tuː',definition:'num. 二',example:'I have two sisters.',level:1},
  {word:'tomorrow',phonetic:'təˈmɒrəʊ',definition:'adv./n. 明天',example:'See you tomorrow.',level:2},
  {word:'town',phonetic:'taʊn',definition:'n. 城镇',example:'I live in a small town.',level:2},
  {word:'toy',phonetic:'tɔɪ',definition:'n. 玩具',example:'I have many toys.',level:2},
  {word:'train',phonetic:'treɪn',definition:'n. 火车；v. 训练',example:'I go by train.',level:2},
  {word:'trip',phonetic:'trɪp',definition:'n. 旅行，旅程',example:'Have a nice trip!',level:3},
  {word:'talk',phonetic:'tɔːk',definition:'v./n. 说话，谈话',example:'Talk to me.',level:3},
  // U
  {word:'umbrella',phonetic:'ʌmˈbrelə',definition:'n. 雨伞',example:'Take an umbrella.',level:2},
  {word:'under',phonetic:'ˈʌndə',definition:'prep. 在…下面',example:'The cat is under the table.',level:2},
  {word:'up',phonetic:'ʌp',definition:'adv./prep. 向上',example:'Get up early.',level:1},
  {word:'use',phonetic:'juːz',definition:'v. 使用',example:'Use a pen.',level:2},
  // V
  {word:'very',phonetic:'ˈveri',definition:'adv. 非常',example:'I am very happy.',level:1},
  {word:'vegetable',phonetic:'ˈvedʒtəbl',definition:'n. 蔬菜',example:'Eat more vegetables.',level:2},
  {word:'visit',phonetic:'ˈvɪzɪt',definition:'v./n. 参观，拜访',example:'We visit the museum.',level:3},
  {word:'village',phonetic:'ˈvɪlɪdʒ',definition:'n. 村庄',example:'My grandma lives in a village.',level:3},
  // W
  {word:'walk',phonetic:'wɔːk',definition:'v./n. 步行，走',example:'I walk to school.',level:1},
  {word:'want',phonetic:'wɒnt',definition:'v. 想要',example:'I want a dog.',level:1},
  {word:'water',phonetic:'ˈwɔːtə',definition:'n. 水',example:'Drink more water.',level:1},
  {word:'we',phonetic:'wiː',definition:'pron. 我们',example:'We are a team.',level:1},
  {word:'what',phonetic:'wɒt',definition:'pron./adj. 什么',example:'What is this?',level:1},
  {word:'where',phonetic:'weə',definition:'adv. 哪里',example:'Where are you from?',level:1},
  {word:'white',phonetic:'waɪt',definition:'adj. 白色的',example:'Snow is white.',level:1},
  {word:'who',phonetic:'huː',definition:'pron. 谁',example:'Who is she?',level:1},
  {word:'window',phonetic:'ˈwɪndəʊ',definition:'n. 窗户',example:'Open the window.',level:1},
  {word:'winter',phonetic:'ˈwɪntə',definition:'n. 冬天',example:'Winter is cold.',level:1},
  {word:'word',phonetic:'wɜːd',definition:'n. 单词，词',example:'Learn new words.',level:1},
  {word:'write',phonetic:'raɪt',definition:'v. 写，书写',example:'Write your name.',level:1},
  {word:'watch',phonetic:'wɒtʃ',definition:'v. 观看；n. 手表',example:'Watch TV.',level:2},
  {word:'work',phonetic:'wɜːk',definition:'v./n. 工作',example:'My parents work hard.',level:2},
  {word:'world',phonetic:'wɜːld',definition:'n. 世界',example:'The world is big.',level:3},
  {word:'weather',phonetic:'ˈweðə',definition:'n. 天气',example:'What is the weather like?',level:3},
  {word:'week',phonetic:'wiːk',definition:'n. 周，星期',example:'One week has seven days.',level:3},
  // Y
  {word:'year',phonetic:'jɪə',definition:'n. 年，年份',example:'Happy New Year!',level:1},
  {word:'yellow',phonetic:'ˈjeləʊ',definition:'adj. 黄色的',example:'Bananas are yellow.',level:1},
  {word:'yes',phonetic:'jes',definition:'adv. 是，对',example:'Yes, I can.',level:1},
  {word:'you',phonetic:'juː',definition:'pron. 你，你们',example:'I love you.',level:1},
  {word:'your',phonetic:'jɔː',definition:'pron. 你的，你们的',example:'What is your name?',level:1},
  {word:'young',phonetic:'jʌŋ',definition:'adj. 年轻的',example:'She is young.',level:2},
  // Z
  {word:'zoo',phonetic:'zuː',definition:'n. 动物园',example:'We go to the zoo.',level:1},
  {word:'zero',phonetic:'ˈzɪərəʊ',definition:'num. 零',example:'The score is zero.',level:2},
];
