// 考研英语一词库 v3 - 约2500词本地核心词 + API在线补充
// 结构: {word, phonetic, pos, definition, example, level}
// level: 1=基础, 2=核心高频, 3=考研必备, 4=拓展提升
// API补充: Free Dictionary API (dictionaryapi.dev) 提供详细英文释义/例句/音频

const KAOYAN_WORDS = [
// ===== A =====
{word:"abandon",phonetic:"/əˈbændən/",pos:"v.",definition:"放弃；遗弃；放纵",example:"He abandoned his plan after facing difficulties.",level:3},
{word:"abnormal",phonetic:"/æbˈnɔːrml/",pos:"adj.",definition:"不正常的；异常的",example:"The doctor noticed abnormal cell growth.",level:3},
{word:"abolish",phonetic:"/əˈbɒlɪʃ/",pos:"v.",definition:"废除；废止（法律、制度等）",example:"The government decided to abolish the old tax system.",level:3},
{word:"abrupt",phonetic:"/əˈbrʌpt/",pos:"adj.",definition:"突然的；唐突的；陡峭的",example:"There was an abrupt change in the weather.",level:3},
{word:"absence",phonetic:"/ˈæbsəns/",pos:"n.",definition:"缺席；不在；缺乏",example:"His absence from the meeting was noticed.",level:2},
{word:"abstract",phonetic:"/ˈæbstrækt/",pos:"adj./n./v.",definition:"抽象的；摘要；提取",example:"The professor gave an abstract explanation.",level:3},
{word:"absurd",phonetic:"/əbˈsɜːrd/",pos:"adj.",definition:"荒谬的；可笑的",example:"It would be absurd to spend so much money on that.",level:3},
{word:"abundant",phonetic:"/əˈbʌndənt/",pos:"adj.",definition:"丰富的；大量的",example:"The region has abundant natural resources.",level:3},
{word:"accelerate",phonetic:"/əkˈseləreɪt/",pos:"v.",definition:"加速；促进",example:"New technology can accelerate economic growth.",level:3},
{word:"access",phonetic:"/ˈækses/",pos:"n./v.",definition:"通道；机会；访问；使用权",example:"Students need access to computers.",level:2},
{word:"accommodate",phonetic:"/əˈkɒmədeɪt/",pos:"v.",definition:"容纳；适应；提供住宿",example:"The hotel can accommodate 500 guests.",level:3},
{word:"accomplish",phonetic:"/əˈkʌmplɪʃ/",pos:"v.",definition:"完成；实现；达到",example:"She accomplished her goals through hard work.",level:2},
{word:"accumulate",phonetic:"/əˈkjuːmjəleɪt/",pos:"v.",definition:"积累；积聚",example:"Dust accumulates quickly in this room.",level:3},
{word:"accurate",phonetic:"/ˈækjərət/",pos:"adj.",definition:"准确的；精确的",example:"The report must be accurate and complete.",level:2},
{word:"achieve",phonetic:"/əˈtʃiːv/",pos:"v.",definition:"实现；完成；达到",example:"Hard work helps you achieve your dreams.",level:1},
{word:"acknowledge",phonetic:"/əkˈnɒlɪdʒ/",pos:"v.",definition:"承认；致谢；确认",example:"He acknowledged his mistakes openly.",level:3},
{word:"acquire",phonetic:"/əˈkwaɪər/",pos:"v.",definition:"获得；习得；取得",example:"Children acquire language naturally.",level:3},
{word:"adapt",phonetic:"/əˈdæpt/",pos:"v.",definition:"适应；改编；改装",example:"Animals adapt to their environment.",level:2},
{word:"adequate",phonetic:"/ˈædɪkwət/",pos:"adj.",definition:"足够的；适当的；胜任的",example:"We need adequate time to finish the project.",level:3},
{word:"adhere",phonetic:"/ədˈhɪər/",pos:"v.",definition:"坚持；遵守；粘附",example:"You must adhere to the rules.",level:3},
{word:"adjacent",phonetic:"/əˈdʒeɪsnt/",pos:"adj.",definition:"邻近的；毗连的",example:"The school is adjacent to the park.",level:3},
{word:"adjust",phonetic:"/əˈdʒʌst/",pos:"v.",definition:"调整；适应；校正",example:"She adjusted the mirror before driving.",level:2},
{word:"administration",phonetic:"/ədˌmɪnɪˈstreɪʃn/",pos:"n.",definition:"管理；行政；政府",example:"The administration announced new policies.",level:2},
{word:"adolescent",phonetic:"/ˌædəˈlesnt/",pos:"n./adj.",definition:"青少年；青春期的",example:"Adolescents often seek independence.",level:3},
{word:"advocate",phonetic:"/ˈædvəkeɪt/",pos:"v./n.",definition:"提倡；支持；律师",example:"She advocates for environmental protection.",level:3},
{word:"aesthetic",phonetic:"/iːsˈθetɪk/",pos:"adj./n.",definition:"美学的；审美的；美感",example:"The aesthetic quality of the painting is superb.",level:4},
{word:"affect",phonetic:"/əˈfekt/",pos:"v.",definition:"影响；感动；患病",example:"Pollution affects our health.",level:1},
{word:"afford",phonetic:"/əˈfɔːrd/",pos:"v.",definition:"负担得起；提供；给予",example:"I can't afford a new car right now.",level:1},
{word:"aggravate",phonetic:"/ˈæɡrəveɪt/",pos:"v.",definition:"加重；使恶化；激怒",example:"Stress can aggravate health problems.",level:3},
{word:"aggressive",phonetic:"/əˈɡresɪv/",pos:"adj.",definition:"侵略的；好斗的；有进取心的",example:"He is known for his aggressive business tactics.",level:2},
{word:"alarm",phonetic:"/əˈlɑːrm/",pos:"n./v.",definition:"警报；担忧；使惊恐",example:"The alarm woke everyone up.",level:1},
{word:"alienate",phonetic:"/ˈeɪliəneɪt/",pos:"v.",definition:"疏远；使孤立；转让",example:"His attitude alienated many friends.",level:4},
{word:"alleviate",phonetic:"/əˈliːvieɪt/",pos:"v.",definition:"减轻；缓和；缓解",example:"This medicine can alleviate pain.",level:3},
{word:"allocate",phonetic:"/ˈæləkeɪt/",pos:"v.",definition:"分配；分派；拨给",example:"The school allocated funds for new equipment.",level:3},
{word:"alter",phonetic:"/ˈɔːltər/",pos:"v.",definition:"改变；改动；更改",example:"She altered her opinion after hearing the evidence.",level:2},
{word:"ambiguous",phonetic:"/æmˈbɪɡjuəs/",pos:"adj.",definition:"模糊的；含糊不清的；有歧义的",example:"The contract contained some ambiguous clauses.",level:3},
{word:"ambitious",phonetic:"/æmˈbɪʃəs/",pos:"adj.",definition:"有雄心的；追求名利的",example:"She is an ambitious young manager.",level:2},
{word:"analogous",phonetic:"/əˈnæləɡəs/",pos:"adj.",definition:"类似的；相似的；可类比的",example:"The situation is analogous to what happened last year.",level:4},
{word:"analyze",phonetic:"/ˈænəlaɪz/",pos:"v.",definition:"分析；解析",example:"Scientists analyze data to find patterns.",level:2},
{word:"anecdote",phonetic:"/ˈænɪkdəʊt/",pos:"n.",definition:"轶事；趣闻；短篇故事",example:"He told an amusing anecdote about his childhood.",level:4},
{word:"annual",phonetic:"/ˈænjuəl/",pos:"adj./n.",definition:"每年的；年度的；年刊",example:"We hold an annual meeting every December.",level:2},
{word:"anonymous",phonetic:"/əˈnɒnɪməs/",pos:"adj.",definition:"匿名的；无名的；无特色的",example:"The donor wished to remain anonymous.",level:3},
{word:"anticipate",phonetic:"/ænˈtɪsɪpeɪt/",pos:"v.",definition:"预期；期待；预料到",example:"We anticipate a rise in sales next quarter.",level:3},
{word:"anxiety",phonetic:"/æŋˈzaɪəti/",pos:"n.",definition:"焦虑；忧虑；渴望",example:"Students often feel anxiety before exams.",level:2},
{word:"apparent",phonetic:"/əˈpærənt/",pos:"adj.",definition:"明显的；表面上的",example:"It was apparent that she was tired.",level:2},
{word:"apprehend",phonetic:"/ˌæprɪˈhend/",pos:"v.",definition:"逮捕；理解；忧虑",example:"The police apprehended the suspect.",level:4},
{word:"appropriate",phonetic:"/əˈprəʊpriət/",pos:"adj.",definition:"适当的；合适的",example:"Choose appropriate clothing for the weather.",level:2},
{word:"approximately",phonetic:"/əˈprɒksɪmətli/",pos:"adv.",definition:"大约；近似地",example:"The project costs approximately $5,000.",level:2},
{word:"arbitrary",phonetic:"/ˈɑːrbɪtreri/",pos:"adj.",definition:"随意的；专断的；武断的",example:"The decision seemed arbitrary and unfair.",level:3},
{word:"assess",phonetic:"/əˈses/",pos:"v.",definition:"评估；评价；估算",example:"Teachers assess students' progress regularly.",level:2},
{word:"assumption",phonetic:"/əˈsʌmpʃn/",pos:"n.",definition:"假设；假定；承担",example:"His plan was based on false assumptions.",level:3},
{word:"atmosphere",phonetic:"/ˈætməsfɪər/",pos:"n.",definition:"大气；气氛；空气",example:"The restaurant had a warm atmosphere.",level:2},
{word:"attain",phonetic:"/əˈteɪn/",pos:"v.",definition:"达到；获得；实现",example:"He attained his goal through hard work.",level:3},
{word:"attribute",phonetic:"/ˈætrɪbjuːt/",pos:"v./n.",definition:"归因于；特性；属性",example:"She attributed her success to luck.",level:3},
{word:"authentic",phonetic:"/ɔːˈθentɪk/",pos:"adj.",definition:"真实的；可信的；真正的",example:"This is an authentic painting from the 17th century.",level:3},
{word:"autonomy",phonetic:"/ɔːˈtɒnəmi/",pos:"n.",definition:"自治；自主；自律",example:"The region gained greater autonomy.",level:4},
{word:"awareness",phonetic:"/əˈweənəs/",pos:"n.",definition:"意识；认识；了解",example:"Public awareness of climate change has increased.",level:2},
// ===== B =====
{word:"barrier",phonetic:"/ˈbæriər/",pos:"n.",definition:"障碍；屏障；界限",example:"Language can be a barrier to communication.",level:2},
{word:"benefit",phonetic:"/ˈbenɪfɪt/",pos:"n./v.",definition:"利益；好处；受益",example:"Exercise has many health benefits.",level:1},
{word:"bias",phonetic:"/ˈbaɪəs/",pos:"n./v.",definition:"偏见；偏差；使有偏见",example:"Journalists should report without bias.",level:3},
{word:"boost",phonetic:"/buːst/",pos:"v./n.",definition:"推动；提高；促进",example:"Exercise can boost your energy levels.",level:2},
{word:"brief",phonetic:"/briːf/",pos:"adj./v./n.",definition:"简短的；短暂的；摘要",example:"Please give a brief summary of the report.",level:1},
{word:"brilliant",phonetic:"/ˈbrɪliənt/",pos:"adj.",definition:"才华横溢的；辉煌的；明亮的",example:"She had a brilliant idea.",level:2},
{word:"burden",phonetic:"/ˈbɜːrdn/",pos:"n./v.",definition:"负担；重担；使受担负",example:"The tax burden is too heavy for small businesses.",level:2},
{word:"bureaucracy",phonetic:"/bjʊˈrɒkrəsi/",pos:"n.",definition:"官僚主义；官僚体制；行政管理",example:"Too much bureaucracy slows progress.",level:4},
// ===== C =====
{word:"capacity",phonetic:"/kəˈpæsəti/",pos:"n.",definition:"能力；容量；资格",example:"The stadium has a seating capacity of 50,000.",level:2},
{word:"catalyst",phonetic:"/ˈkætəlɪst/",pos:"n.",definition:"催化剂；促进因素",example:"The invention was a catalyst for change.",level:4},
{word:"characteristic",phonetic:"/ˌkærəktəˈrɪstɪk/",pos:"n./adj.",definition:"特征；特性；特有的",example:"Curiosity is a characteristic of scientists.",level:2},
{word:"chronic",phonetic:"/ˈkrɒnɪk/",pos:"adj.",definition:"慢性的；长期的；积习难改的",example:"He suffers from chronic back pain.",level:3},
{word:"circumstance",phonetic:"/ˈsɜːrkəmstəns/",pos:"n.",definition:"情况；环境；境况",example:"Under these circumstances, we must act quickly.",level:2},
{word:"cite",phonetic:"/saɪt/",pos:"v.",definition:"引用；提到；传唤",example:"The lawyer cited several relevant cases.",level:3},
{word:"cognitive",phonetic:"/ˈkɒɡnɪtɪv/",pos:"adj.",definition:"认知的；认识的",example:"Cognitive skills improve with practice.",level:3},
{word:"coherent",phonetic:"/kəʊˈhɪərənt/",pos:"adj.",definition:"连贯的；条理清晰的；一致的",example:"Her argument was clear and coherent.",level:4},
{word:"collaborate",phonetic:"/kəˈlæbəreɪt/",pos:"v.",definition:"合作；协作；通敌",example:"Scientists from many countries collaborated on the project.",level:3},
{word:"compensate",phonetic:"/ˈkɒmpenseɪt/",pos:"v.",definition:"补偿；赔偿；弥补",example:"The company compensated him for his loss.",level:3},
{word:"competent",phonetic:"/ˈkɒmpɪtənt/",pos:"adj.",definition:"有能力的；胜任的；足够的",example:"A competent doctor should know the symptoms.",level:2},
{word:"complex",phonetic:"/ˈkɒmpleks/",pos:"adj./n.",definition:"复杂的；综合体；情结",example:"The situation is very complex.",level:1},
{word:"comply",phonetic:"/kəmˈplaɪ/",pos:"v.",definition:"遵守；顺从；服从",example:"You must comply with the regulations.",level:3},
{word:"compromise",phonetic:"/ˈkɒmprəmaɪz/",pos:"v./n.",definition:"妥协；折中；危及",example:"Both sides had to compromise to reach a deal.",level:2},
{word:"conceive",phonetic:"/kənˈsiːv/",pos:"v.",definition:"构思；设想；怀孕",example:"She conceived a brilliant plan.",level:3},
{word:"concentrate",phonetic:"/ˈkɒnsntreɪt/",pos:"v./n.",definition:"集中；专注；浓缩物",example:"Please concentrate on your work.",level:2},
{word:"condemn",phonetic:"/kənˈdem/",pos:"v.",definition:"谴责；判刑；判定",example:"The government condemned the terrorist attack.",level:3},
{word:"confine",phonetic:"/kənˈfaɪn/",pos:"v.",definition:"限制；禁闭；局限于",example:"The research was confined to one area.",level:3},
{word:"confront",phonetic:"/kənˈfrʌnt/",pos:"v.",definition:"面对；使对质；对抗",example:"We must confront the problem directly.",level:2},
{word:"conscious",phonetic:"/ˈkɒnʃəs/",pos:"adj.",definition:"有意识的；自觉的；神志清醒的",example:"She was conscious of his stare.",level:2},
{word:"consensus",phonetic:"/kənˈsensəs/",pos:"n.",definition:"共识；一致意见；合意",example:"The team reached a consensus on the decision.",level:3},
{word:"conserve",phonetic:"/kənˈsɜːrv/",pos:"v.",definition:"保护；节约；保存",example:"We should conserve natural resources.",level:2},
{word:"consistent",phonetic:"/kənˈsɪstənt/",pos:"adj.",definition:"一致的；连续的；前后一贯的",example:"She delivers consistent results every time.",level:2},
{word:"constitute",phonetic:"/ˈkɒnstɪtjuːt/",pos:"v.",definition:"构成；组成；设立",example:"Women constitute 40% of the workforce.",level:3},
{word:"constraint",phonetic:"/kənˈstreɪnt/",pos:"n.",definition:"约束；限制；强迫",example:"Budget constraints limited the project scope.",level:3},
{word:"consume",phonetic:"/kənˈsjuːm/",pos:"v.",definition:"消耗；消费；吃喝",example:"Cars consume a lot of fuel.",level:2},
{word:"contemporary",phonetic:"/kənˈtemprəri/",pos:"adj./n.",definition:"当代的；同时代的；同代人",example:"He is one of the greatest contemporary writers.",level:3},
{word:"contradict",phonetic:"/ˌkɒntrəˈdɪkt/",pos:"v.",definition:"反驳；与…矛盾；抵触",example:"His actions contradict his words.",level:3},
{word:"controversial",phonetic:"/ˌkɒntrəˈvɜːʃl/",pos:"adj.",definition:"有争议的；引起争议的",example:"Abortion is a controversial issue.",level:3},
{word:"convey",phonetic:"/kənˈveɪ/",pos:"v.",definition:"传达；传送；运输",example:"Art can convey powerful emotions.",level:3},
{word:"cooperate",phonetic:"/kəʊˈɒpəreɪt/",pos:"v.",definition:"合作；协作；配合",example:"Countries should cooperate on climate change.",level:2},
{word:"coordinate",phonetic:"/kəʊˈɔːrdɪneɪt/",pos:"v./n.",definition:"协调；配合；坐标",example:"We need to coordinate our efforts.",level:3},
{word:"counterpart",phonetic:"/ˈkaʊntəpɑːrt/",pos:"n.",definition:"对应的人/物；副本；相对物",example:"The foreign minister met with his counterpart.",level:4},
{word:"credible",phonetic:"/ˈkredɪbl/",pos:"adj.",definition:"可信的；可靠的；真实可信的",example:"We need credible evidence to make a decision.",level:3},
{word:"criterion",phonetic:"/kraɪˈtɪəriən/",pos:"n.",definition:"标准；准则；准据",example:"The main criterion for success is effort.",level:3},
{word:"crucial",phonetic:"/ˈkruːʃl/",pos:"adj.",definition:"至关重要的；决定性的",example:"This decision is crucial to our success.",level:2},
{word:"cultivate",phonetic:"/ˈkʌltɪveɪt/",pos:"v.",definition:"培育；耕种；修养",example:"Good habits can be cultivated over time.",level:3},
{word:"cumulative",phonetic:"/ˈkjuːmjələtɪv/",pos:"adj.",definition:"积累的；累积的；渐增的",example:"The cumulative effect of stress can be harmful.",level:4},
{word:"curriculum",phonetic:"/kəˈrɪkjələm/",pos:"n.",definition:"课程；课程体系",example:"Schools are updating their curriculum.",level:3},
// ===== D =====
{word:"deduce",phonetic:"/dɪˈdjuːs/",pos:"v.",definition:"推断；演绎；推论",example:"From the evidence, we can deduce the cause.",level:3},
{word:"deficiency",phonetic:"/dɪˈfɪʃnsi/",pos:"n.",definition:"不足；缺乏；缺陷",example:"Vitamin D deficiency is common in winter.",level:3},
{word:"define",phonetic:"/dɪˈfaɪn/",pos:"v.",definition:"定义；规定；明确说明",example:"Please define your goals clearly.",level:1},
{word:"deliberate",phonetic:"/dɪˈlɪbərət/",pos:"adj./v.",definition:"蓄意的；深思熟虑的；仔细考虑",example:"It was a deliberate choice.",level:3},
{word:"demonstrate",phonetic:"/ˈdemənstreɪt/",pos:"v.",definition:"证明；演示；示威",example:"The experiment demonstrates the effect.",level:2},
{word:"denote",phonetic:"/dɪˈnəʊt/",pos:"v.",definition:"表示；意味；是…的标志",example:"Red traffic lights denote stop.",level:4},
{word:"depict",phonetic:"/dɪˈpɪkt/",pos:"v.",definition:"描述；描绘；刻画",example:"The novel depicts life in rural China.",level:3},
{word:"deplete",phonetic:"/dɪˈpliːt/",pos:"v.",definition:"耗尽；使大量减少",example:"Mining depletes natural resources.",level:3},
{word:"derive",phonetic:"/dɪˈraɪv/",pos:"v.",definition:"取得；获得；起源于",example:"Many English words derive from Latin.",level:3},
{word:"designate",phonetic:"/ˈdezɪɡneɪt/",pos:"v.",definition:"指定；任命；标明",example:"The area has been designated a nature reserve.",level:4},
{word:"despite",phonetic:"/dɪˈspaɪt/",pos:"prep.",definition:"尽管；不管；不顾",example:"Despite the rain, we continued hiking.",level:1},
{word:"determine",phonetic:"/dɪˈtɜːrmɪn/",pos:"v.",definition:"决定；确定；查明",example:"Hard work determines success.",level:2},
{word:"devastating",phonetic:"/ˈdevəsteɪtɪŋ/",pos:"adj.",definition:"毁灭性的；压倒性的；极为有效的",example:"The flood had a devastating effect.",level:3},
{word:"devote",phonetic:"/dɪˈvəʊt/",pos:"v.",definition:"致力于；奉献；专注于",example:"She devoted her life to teaching.",level:2},
{word:"dictate",phonetic:"/dɪkˈteɪt/",pos:"v.",definition:"口述；规定；命令",example:"His boss dictated every detail of the project.",level:3},
{word:"diminish",phonetic:"/dɪˈmɪnɪʃ/",pos:"v.",definition:"减少；缩小；贬低",example:"Her influence has diminished over the years.",level:3},
{word:"discipline",phonetic:"/ˈdɪsɪplɪn/",pos:"n./v.",definition:"纪律；学科；惩罚",example:"Self-discipline is key to success.",level:2},
{word:"discriminate",phonetic:"/dɪˈskrɪmɪneɪt/",pos:"v.",definition:"歧视；区分；辨别",example:"It is wrong to discriminate against women.",level:3},
{word:"displace",phonetic:"/dɪsˈpleɪs/",pos:"v.",definition:"取代；移走；驱逐",example:"Automation displaces many workers.",level:3},
{word:"dispute",phonetic:"/dɪˈspjuːt/",pos:"v./n.",definition:"争论；争议；质疑",example:"The two companies are in a dispute over patents.",level:2},
{word:"disrupt",phonetic:"/dɪsˈrʌpt/",pos:"v.",definition:"打乱；扰乱；使中断",example:"The storm disrupted transportation.",level:3},
{word:"diverse",phonetic:"/daɪˈvɜːrs/",pos:"adj.",definition:"多种多样的；不同的",example:"New York has a diverse population.",level:2},
{word:"dominant",phonetic:"/ˈdɒmɪnənt/",pos:"adj.",definition:"占主导地位的；支配性的",example:"English is the dominant language in business.",level:3},
{word:"dramatic",phonetic:"/drəˈmætɪk/",pos:"adj.",definition:"戏剧性的；激动人心的；显著的",example:"There was a dramatic improvement in results.",level:2},
{word:"dynamic",phonetic:"/daɪˈnæmɪk/",pos:"adj./n.",definition:"有活力的；动态的；动力",example:"The dynamic leader motivated her team.",level:2},
// ===== E =====
{word:"elaborate",phonetic:"/ɪˈlæbərət/",pos:"adj./v.",definition:"精心制作的；详尽的；详细说明",example:"She wore an elaborate costume.",level:3},
{word:"eliminate",phonetic:"/ɪˈlɪmɪneɪt/",pos:"v.",definition:"消除；排除；淘汰",example:"We must eliminate waste from the process.",level:2},
{word:"embrace",phonetic:"/ɪmˈbreɪs/",pos:"v./n.",definition:"接受；拥抱；包含",example:"We should embrace new ideas.",level:2},
{word:"emerge",phonetic:"/ɪˈmɜːrdʒ/",pos:"v.",definition:"出现；浮现；摆脱",example:"A new solution emerged from the discussion.",level:2},
{word:"emphasis",phonetic:"/ˈemfəsɪs/",pos:"n.",definition:"强调；重点；重要性",example:"The teacher placed emphasis on pronunciation.",level:2},
{word:"empirical",phonetic:"/ɪmˈpɪrɪkl/",pos:"adj.",definition:"经验主义的；实证的；实验的",example:"The theory is supported by empirical evidence.",level:4},
{word:"enable",phonetic:"/ɪˈneɪbl/",pos:"v.",definition:"使能够；使可能；授权",example:"Technology enables people to work remotely.",level:1},
{word:"encounter",phonetic:"/ɪnˈkaʊntər/",pos:"v./n.",definition:"遭遇；偶遇；碰到",example:"We encountered many difficulties.",level:2},
{word:"enforce",phonetic:"/ɪnˈfɔːrs/",pos:"v.",definition:"执行；强制；强加",example:"The police enforce traffic laws.",level:2},
{word:"enhance",phonetic:"/ɪnˈhɑːns/",pos:"v.",definition:"提高；增强；加强",example:"Exercise enhances your overall health.",level:2},
{word:"enormous",phonetic:"/ɪˈnɔːrməs/",pos:"adj.",definition:"巨大的；庞大的",example:"The company made enormous profits.",level:2},
{word:"ensure",phonetic:"/ɪnˈʃʊər/",pos:"v.",definition:"确保；保证",example:"Please ensure your safety at all times.",level:1},
{word:"enterprise",phonetic:"/ˈentərpraɪz/",pos:"n.",definition:"企业；事业；进取心",example:"Small enterprises drive economic growth.",level:2},
{word:"environment",phonetic:"/ɪnˈvaɪrənmənt/",pos:"n.",definition:"环境；自然环境；周围状况",example:"We must protect our environment.",level:1},
{word:"equip",phonetic:"/ɪˈkwɪp/",pos:"v.",definition:"装备；配备；使适应",example:"The school is equipped with modern computers.",level:2},
{word:"equivalent",phonetic:"/ɪˈkwɪvələnt/",pos:"adj./n.",definition:"相等的；等价的；同等物",example:"A master's degree is equivalent to two years of research.",level:3},
{word:"establish",phonetic:"/ɪˈstæblɪʃ/",pos:"v.",definition:"建立；设立；确立",example:"The company was established in 1990.",level:1},
{word:"ethical",phonetic:"/ˈeθɪkl/",pos:"adj.",definition:"道德的；伦理的；合乎道德的",example:"Doctors must follow ethical guidelines.",level:3},
{word:"evaluate",phonetic:"/ɪˈvæljueɪt/",pos:"v.",definition:"评估；评价；估计",example:"Teachers evaluate students' performance.",level:2},
{word:"evident",phonetic:"/ˈevɪdənt/",pos:"adj.",definition:"明显的；明白的；显然的",example:"It was evident that he was upset.",level:2},
{word:"evolve",phonetic:"/ɪˈvɒlv/",pos:"v.",definition:"进化；演变；逐渐发展",example:"Languages evolve over time.",level:2},
{word:"exceed",phonetic:"/ɪkˈsiːd/",pos:"v.",definition:"超过；超越；胜过",example:"Sales exceeded expectations this year.",level:2},
{word:"exclude",phonetic:"/ɪkˈskluːd/",pos:"v.",definition:"排除；排斥；不包括",example:"The price excludes tax.",level:2},
{word:"exhibit",phonetic:"/ɪɡˈzɪbɪt/",pos:"v./n.",definition:"展示；表现；展品",example:"The museum exhibits ancient artifacts.",level:2},
{word:"explicit",phonetic:"/ɪkˈsplɪsɪt/",pos:"adj.",definition:"明确的；清楚的；直言的",example:"Please give explicit instructions.",level:3},
{word:"exploit",phonetic:"/ɪkˈsplɔɪt/",pos:"v./n.",definition:"剥削；利用；开发",example:"We should not exploit natural resources carelessly.",level:3},
{word:"extensive",phonetic:"/ɪkˈstensɪv/",pos:"adj.",definition:"广阔的；广泛的；大量的",example:"The report requires extensive research.",level:2},
// ===== F =====
{word:"facilitate",phonetic:"/fəˈsɪlɪteɪt/",pos:"v.",definition:"促进；有助于；使容易",example:"Technology facilitates communication.",level:3},
{word:"factor",phonetic:"/ˈfæktər/",pos:"n./v.",definition:"因素；要素；分解",example:"Luck is a factor in success.",level:1},
{word:"feasible",phonetic:"/ˈfiːzəbl/",pos:"adj.",definition:"可行的；可能的；合理的",example:"Is this plan feasible?",level:3},
{word:"fluctuate",phonetic:"/ˈflʌktʃueɪt/",pos:"v.",definition:"波动；起伏；涨落不定",example:"Oil prices fluctuate daily.",level:3},
{word:"focus",phonetic:"/ˈfəʊkəs/",pos:"v./n.",definition:"集中；关注；焦点",example:"Let's focus on the main issue.",level:1},
{word:"formulate",phonetic:"/ˈfɔːrmjuleɪt/",pos:"v.",definition:"制定；阐明；构想",example:"They formulated a new strategy.",level:3},
{word:"foster",phonetic:"/ˈfɒstər/",pos:"v.",definition:"培养；促进；寄养",example:"Education fosters creativity.",level:3},
{word:"fragile",phonetic:"/ˈfrædʒaɪl/",pos:"adj.",definition:"脆弱的；易碎的；虚弱的",example:"Handle the fragile objects with care.",level:2},
{word:"function",phonetic:"/ˈfʌŋkʃn/",pos:"n./v.",definition:"功能；作用；起作用",example:"What is the function of this organ?",level:1},
{word:"fundamental",phonetic:"/ˌfʌndəˈmentl/",pos:"adj./n.",definition:"基本的；根本的；基础",example:"This is a fundamental principle of science.",level:2},
// ===== G =====
{word:"generate",phonetic:"/ˈdʒenəreɪt/",pos:"v.",definition:"产生；发电；引起",example:"Solar panels generate electricity.",level:2},
{word:"genuine",phonetic:"/ˈdʒenjuɪn/",pos:"adj.",definition:"真正的；真实的；真诚的",example:"She showed genuine concern for others.",level:2},
{word:"global",phonetic:"/ˈɡləʊbl/",pos:"adj.",definition:"全球的；全球性的；整体的",example:"Climate change is a global issue.",level:1},
{word:"grant",phonetic:"/ɡrɑːnt/",pos:"v./n.",definition:"授予；批准；助学金",example:"The government granted them permission.",level:2},
{word:"guarantee",phonetic:"/ˌɡærənˈtiː/",pos:"v./n.",definition:"保证；担保；保障",example:"Nothing can guarantee success.",level:2},
{word:"guideline",phonetic:"/ˈɡaɪdlaɪn/",pos:"n.",definition:"指导方针；准则；指南",example:"Follow the guidelines carefully.",level:2},
// ===== H =====
{word:"hierarchy",phonetic:"/ˈhaɪərɑːrki/",pos:"n.",definition:"等级制度；层级；阶层体系",example:"The company has a strict hierarchy.",level:4},
{word:"highlight",phonetic:"/ˈhaɪlaɪt/",pos:"v./n.",definition:"强调；突出；最精彩部分",example:"The report highlights key issues.",level:2},
{word:"hypothesis",phonetic:"/haɪˈpɒθəsɪs/",pos:"n.",definition:"假说；假设；前提",example:"The scientist tested her hypothesis.",level:3},
// ===== I =====
{word:"identify",phonetic:"/aɪˈdentɪfaɪ/",pos:"v.",definition:"识别；确认；认同",example:"Police identified the suspect.",level:2},
{word:"ignore",phonetic:"/ɪɡˈnɔːr/",pos:"v.",definition:"忽视；不顾；漠视",example:"Don't ignore the warning signs.",level:1},
{word:"illustrate",phonetic:"/ˈɪləstreɪt/",pos:"v.",definition:"说明；阐明；给…加插图",example:"This example illustrates the point.",level:2},
{word:"imply",phonetic:"/ɪmˈplaɪ/",pos:"v.",definition:"暗示；意味着；包含",example:"His silence implied agreement.",level:2},
{word:"impose",phonetic:"/ɪmˈpəʊz/",pos:"v.",definition:"强加；征税；强制推行",example:"They imposed strict rules on the students.",level:3},
{word:"incentive",phonetic:"/ɪnˈsentɪv/",pos:"n.",definition:"激励；奖励；动机",example:"Bonuses are an incentive to work harder.",level:3},
{word:"incorporate",phonetic:"/ɪnˈkɔːrpəreɪt/",pos:"v.",definition:"包含；吸收；合并",example:"The design incorporates modern features.",level:3},
{word:"indicate",phonetic:"/ˈɪndɪkeɪt/",pos:"v.",definition:"表明；暗示；指示",example:"The signs indicate danger.",level:2},
{word:"induce",phonetic:"/ɪnˈdjuːs/",pos:"v.",definition:"引起；诱导；劝说",example:"Stress can induce health problems.",level:3},
{word:"inevitable",phonetic:"/ɪnˈevɪtəbl/",pos:"adj.",definition:"不可避免的；必然发生的",example:"Change is inevitable.",level:3},
{word:"influence",phonetic:"/ˈɪnfluəns/",pos:"n./v.",definition:"影响；作用；势力",example:"Parents have a strong influence on children.",level:1},
{word:"inherent",phonetic:"/ɪnˈhɪərənt/",pos:"adj.",definition:"内在的；固有的；天生的",example:"There are inherent risks in every business.",level:4},
{word:"initiate",phonetic:"/ɪˈnɪʃieɪt/",pos:"v.",definition:"开始；发起；启动",example:"The president initiated the peace talks.",level:3},
{word:"innovate",phonetic:"/ˈɪnəveɪt/",pos:"v.",definition:"革新；创新",example:"Companies must innovate to survive.",level:3},
{word:"insight",phonetic:"/ˈɪnsaɪt/",pos:"n.",definition:"洞察力；深刻理解；见解",example:"He offered valuable insights into the problem.",level:3},
{word:"integrate",phonetic:"/ˈɪntɪɡreɪt/",pos:"v.",definition:"整合；使融入；结合",example:"The school integrates students from different backgrounds.",level:3},
{word:"interact",phonetic:"/ˌɪntərˈækt/",pos:"v.",definition:"互动；相互作用；交流",example:"Children learn by interacting with others.",level:2},
{word:"interpret",phonetic:"/ɪnˈtɜːrprɪt/",pos:"v.",definition:"解释；口译；理解",example:"How do you interpret this passage?",level:2},
{word:"intrinsic",phonetic:"/ɪnˈtrɪnsɪk/",pos:"adj.",definition:"内在的；固有的；本质的",example:"Intrinsic motivation is more lasting.",level:4},
{word:"investigate",phonetic:"/ɪnˈvestɪɡeɪt/",pos:"v.",definition:"调查；研究；审查",example:"Police are investigating the crime.",level:2},
{word:"involve",phonetic:"/ɪnˈvɒlv/",pos:"v.",definition:"涉及；包含；使参与",example:"This project involves many people.",level:1},
{word:"isolate",phonetic:"/ˈaɪsəleɪt/",pos:"v.",definition:"隔离；孤立；使独立",example:"The patient was isolated to prevent infection.",level:3},
// ===== J-L =====
{word:"justify",phonetic:"/ˈdʒʌstɪfaɪ/",pos:"v.",definition:"证明合理；为…辩护；使齐行",example:"Can you justify this decision?",level:3},
{word:"legislate",phonetic:"/ˈledʒɪsleɪt/",pos:"v.",definition:"立法；制定法律",example:"Congress legislates on national issues.",level:4},
{word:"legitimate",phonetic:"/lɪˈdʒɪtɪmət/",pos:"adj.",definition:"合法的；正当的；合情合理的",example:"That is a legitimate concern.",level:3},
{word:"liable",phonetic:"/ˈlaɪəbl/",pos:"adj.",definition:"有责任的；易于…的；应受处罚的",example:"The company is liable for the damages.",level:3},
{word:"liberal",phonetic:"/ˈlɪbərəl/",pos:"adj./n.",definition:"自由主义的；慷慨的；进步的",example:"He holds liberal political views.",level:3},
{word:"limitation",phonetic:"/ˌlɪmɪˈteɪʃn/",pos:"n.",definition:"限制；局限性；缺陷",example:"There are limitations to every approach.",level:2},
// ===== M =====
{word:"maintain",phonetic:"/meɪnˈteɪn/",pos:"v.",definition:"维持；保持；坚持",example:"It's hard to maintain a healthy diet.",level:1},
{word:"manifest",phonetic:"/ˈmænɪfest/",pos:"v./adj.",definition:"表明；显现；明显的",example:"His talents manifested at an early age.",level:4},
{word:"manipulate",phonetic:"/məˈnɪpjuleɪt/",pos:"v.",definition:"操纵；操作；控制",example:"He manipulated the data to support his theory.",level:3},
{word:"mechanism",phonetic:"/ˈmekənɪzəm/",pos:"n.",definition:"机制；机械装置；手段",example:"The brain has complex coping mechanisms.",level:3},
{word:"merit",phonetic:"/ˈmerɪt/",pos:"n./v.",definition:"优点；价值；功绩",example:"The plan has its merits and drawbacks.",level:3},
{word:"methodology",phonetic:"/ˌmeθəˈdɒlədʒi/",pos:"n.",definition:"方法论；研究方法",example:"The study uses a new methodology.",level:4},
{word:"minimize",phonetic:"/ˈmɪnɪmaɪz/",pos:"v.",definition:"最小化；减少到最低",example:"Try to minimize waste.",level:2},
{word:"modify",phonetic:"/ˈmɒdɪfaɪ/",pos:"v.",definition:"修改；改进；调整",example:"We need to modify the plan.",level:2},
{word:"monitor",phonetic:"/ˈmɒnɪtər/",pos:"v./n.",definition:"监测；监控；显示器",example:"Doctors monitor patients' progress.",level:2},
{word:"motivate",phonetic:"/ˈməʊtɪveɪt/",pos:"v.",definition:"激励；激发；驱动",example:"A good teacher motivates students.",level:2},
// ===== N =====
{word:"notable",phonetic:"/ˈnəʊtəbl/",pos:"adj.",definition:"值得注意的；显著的；著名的",example:"She made a notable contribution.",level:3},
{word:"notion",phonetic:"/ˈnəʊʃn/",pos:"n.",definition:"概念；看法；观念",example:"The notion of justice varies across cultures.",level:3},
{word:"neglect",phonetic:"/nɪˈɡlekt/",pos:"v./n.",definition:"忽视；疏忽；漠视",example:"Don't neglect your health.",level:2},
// ===== O =====
{word:"objective",phonetic:"/əbˈdʒektɪv/",pos:"adj./n.",definition:"客观的；目标；任务",example:"Be objective when making a decision.",level:2},
{word:"obstacle",phonetic:"/ˈɒbstəkl/",pos:"n.",definition:"障碍；阻碍；绊脚石",example:"Poverty is an obstacle to education.",level:2},
{word:"obtain",phonetic:"/əbˈteɪn/",pos:"v.",definition:"获得；得到；实现",example:"She obtained a scholarship.",level:2},
{word:"obvious",phonetic:"/ˈɒbviəs/",pos:"adj.",definition:"明显的；显而易见的",example:"The answer is obvious.",level:1},
{word:"occupy",phonetic:"/ˈɒkjəpaɪ/",pos:"v.",definition:"占据；占领；使忙碌",example:"Work occupies most of my day.",level:2},
{word:"ongoing",phonetic:"/ˈɒnɡəʊɪŋ/",pos:"adj.",definition:"持续的；不间断的；进行中的",example:"This is an ongoing project.",level:2},
{word:"oppose",phonetic:"/əˈpəʊz/",pos:"v.",definition:"反对；抵制；抗拒",example:"Many citizens oppose the new policy.",level:2},
{word:"optimize",phonetic:"/ˈɒptɪmaɪz/",pos:"v.",definition:"优化；使最优化",example:"We need to optimize our performance.",level:3},
{word:"outcome",phonetic:"/ˈaʊtkʌm/",pos:"n.",definition:"结果；成果；后果",example:"The outcome of the election surprised everyone.",level:2},
{word:"overcome",phonetic:"/ˌəʊvərˈkʌm/",pos:"v.",definition:"克服；战胜；压倒",example:"She overcame many challenges.",level:2},
{word:"overlook",phonetic:"/ˌəʊvərˈlʊk/",pos:"v.",definition:"俯瞰；忽视；宽容",example:"Don't overlook the details.",level:2},
// ===== P =====
{word:"paradigm",phonetic:"/ˈpærədaɪm/",pos:"n.",definition:"范式；模式；范例",example:"This discovery represents a paradigm shift.",level:4},
{word:"perceive",phonetic:"/pərˈsiːv/",pos:"v.",definition:"感知；察觉；认为",example:"How do you perceive this situation?",level:3},
{word:"perspective",phonetic:"/pərˈspektɪv/",pos:"n.",definition:"观点；角度；视角",example:"Consider the problem from a different perspective.",level:2},
{word:"phenomenon",phonetic:"/fɪˈnɒmɪnən/",pos:"n.",definition:"现象；奇特的事；奇才",example:"Globalization is a modern phenomenon.",level:3},
{word:"polarize",phonetic:"/ˈpəʊləraɪz/",pos:"v.",definition:"两极化；使分化；极化",example:"The debate polarized public opinion.",level:4},
{word:"potential",phonetic:"/pəˈtenʃl/",pos:"adj./n.",definition:"潜在的；潜力；可能性",example:"Every student has potential.",level:2},
{word:"predict",phonetic:"/prɪˈdɪkt/",pos:"v.",definition:"预测；预言；预报",example:"It's hard to predict the future.",level:2},
{word:"predominant",phonetic:"/prɪˈdɒmɪnənt/",pos:"adj.",definition:"主导的；显著的；占优势的",example:"English is the predominant language in business.",level:4},
{word:"preserve",phonetic:"/prɪˈzɜːrv/",pos:"v.",definition:"保存；保护；维持",example:"We must preserve our cultural heritage.",level:2},
{word:"priority",phonetic:"/praɪˈɒrəti/",pos:"n.",definition:"优先；重点；优先权",example:"Health should be your first priority.",level:2},
{word:"profound",phonetic:"/prəˈfaʊnd/",pos:"adj.",definition:"深刻的；意义深远的；渊博的",example:"Technology has had a profound impact on society.",level:3},
{word:"prohibit",phonetic:"/prəˈhɪbɪt/",pos:"v.",definition:"禁止；阻止；不准",example:"Smoking is prohibited in this building.",level:2},
{word:"promote",phonetic:"/prəˈməʊt/",pos:"v.",definition:"促进；推广；晋升",example:"The campaign promotes healthy eating.",level:1},
{word:"proportion",phonetic:"/prəˈpɔːrʃn/",pos:"n.",definition:"比例；部分；均衡",example:"A large proportion of students passed.",level:2},
{word:"propose",phonetic:"/prəˈpəʊz/",pos:"v.",definition:"建议；提出；求婚",example:"She proposed a new solution.",level:2},
{word:"psychology",phonetic:"/saɪˈkɒlədʒi/",pos:"n.",definition:"心理学；心理状态",example:"Psychology helps us understand behavior.",level:2},
{word:"pursue",phonetic:"/pərˈsjuː/",pos:"v.",definition:"追求；从事；追捕",example:"He pursued a career in medicine.",level:2},
// ===== R =====
{word:"rationale",phonetic:"/ˌræʃəˈnɑːl/",pos:"n.",definition:"根本原因；基本原理；理性基础",example:"What is the rationale behind this decision?",level:4},
{word:"recognize",phonetic:"/ˈrekəɡnaɪz/",pos:"v.",definition:"认识；承认；识别",example:"I recognized her voice immediately.",level:1},
{word:"refine",phonetic:"/rɪˈfaɪn/",pos:"v.",definition:"提炼；改进；使完善",example:"We need to refine our approach.",level:3},
{word:"regulate",phonetic:"/ˈreɡjuleɪt/",pos:"v.",definition:"规范；调节；管理",example:"The government regulates food safety.",level:2},
{word:"reinforce",phonetic:"/ˌriːɪnˈfɔːrs/",pos:"v.",definition:"加强；强化；巩固",example:"Practice reinforces learning.",level:3},
{word:"relevant",phonetic:"/ˈreləvənt/",pos:"adj.",definition:"相关的；切题的；恰当的",example:"Please provide relevant information.",level:2},
{word:"reluctant",phonetic:"/rɪˈlʌktənt/",pos:"adj.",definition:"不情愿的；勉强的",example:"She was reluctant to leave.",level:3},
{word:"remarkable",phonetic:"/rɪˈmɑːrkəbl/",pos:"adj.",definition:"非凡的；卓越的；引人注目的",example:"He made remarkable progress.",level:2},
{word:"require",phonetic:"/rɪˈkwaɪər/",pos:"v.",definition:"需要；要求；命令",example:"This job requires experience.",level:1},
{word:"resolve",phonetic:"/rɪˈzɒlv/",pos:"v./n.",definition:"解决；决心；决议",example:"We need to resolve this conflict.",level:2},
{word:"restrict",phonetic:"/rɪˈstrɪkt/",pos:"v.",definition:"限制；约束；限定",example:"The new law restricts pollution.",level:2},
{word:"reveal",phonetic:"/rɪˈviːl/",pos:"v.",definition:"揭示；透露；显示",example:"The investigation revealed the truth.",level:2},
// ===== S =====
{word:"sufficient",phonetic:"/səˈfɪʃnt/",pos:"adj.",definition:"足够的；充分的",example:"We have sufficient resources.",level:2},
{word:"significant",phonetic:"/sɪɡˈnɪfɪkənt/",pos:"adj.",definition:"重大的；有意义的；显著的",example:"This is a significant discovery.",level:2},
{word:"simulate",phonetic:"/ˈsɪmjuleɪt/",pos:"v.",definition:"模仿；模拟；假装",example:"Scientists simulate climate change effects.",level:3},
{word:"stability",phonetic:"/stəˈbɪləti/",pos:"n.",definition:"稳定性；稳固；稳定状态",example:"Political stability encourages investment.",level:2},
{word:"strategy",phonetic:"/ˈstrætədʒi/",pos:"n.",definition:"策略；战略；计划",example:"The company developed a new marketing strategy.",level:2},
{word:"strive",phonetic:"/straɪv/",pos:"v.",definition:"努力；奋斗；力求",example:"Always strive to improve yourself.",level:2},
{word:"substantial",phonetic:"/səbˈstænʃl/",pos:"adj.",definition:"大量的；实质的；坚固的",example:"She made a substantial contribution.",level:3},
{word:"substitute",phonetic:"/ˈsʌbstɪtjuːt/",pos:"v./n.",definition:"替代；代替物；替换",example:"You can substitute honey for sugar.",level:2},
{word:"subtle",phonetic:"/ˈsʌtl/",pos:"adj.",definition:"微妙的；精细的；不易察觉的",example:"There is a subtle difference between them.",level:3},
{word:"suppress",phonetic:"/səˈpres/",pos:"v.",definition:"压制；抑制；镇压",example:"He tried to suppress his anger.",level:3},
{word:"sustain",phonetic:"/səˈsteɪn/",pos:"v.",definition:"维持；持续；支撑",example:"We must sustain economic growth.",level:2},
// ===== T =====
{word:"tendency",phonetic:"/ˈtendənsi/",pos:"n.",definition:"倾向；趋势；偏好",example:"There is a tendency to blame others.",level:2},
{word:"theoretical",phonetic:"/ˌθɪəˈretɪkl/",pos:"adj.",definition:"理论的；假设的；推理的",example:"This is only a theoretical framework.",level:3},
{word:"tolerate",phonetic:"/ˈtɒləreɪt/",pos:"v.",definition:"容忍；忍受；默许",example:"She cannot tolerate injustice.",level:3},
{word:"transform",phonetic:"/trænsˈfɔːrm/",pos:"v.",definition:"变换；改造；使改观",example:"Education transforms people's lives.",level:2},
{word:"transmit",phonetic:"/trænsˈmɪt/",pos:"v.",definition:"传送；传播；传达",example:"Viruses can be transmitted through air.",level:3},
{word:"transparent",phonetic:"/trænsˈpærənt/",pos:"adj.",definition:"透明的；清晰的；易懂的",example:"The government should be transparent.",level:2},
{word:"trigger",phonetic:"/ˈtrɪɡər/",pos:"v./n.",definition:"触发；引起；触发器",example:"Stress can trigger illness.",level:2},
// ===== U =====
{word:"undermine",phonetic:"/ˌʌndərˈmaɪn/",pos:"v.",definition:"破坏；削弱；挖空基础",example:"Corruption undermines public trust.",level:3},
{word:"unique",phonetic:"/juːˈniːk/",pos:"adj.",definition:"独特的；唯一的；独一无二的",example:"Everyone has a unique personality.",level:1},
{word:"universal",phonetic:"/ˌjuːnɪˈvɜːrsl/",pos:"adj.",definition:"普遍的；全球的；共有的",example:"Mathematics is a universal language.",level:2},
{word:"utilize",phonetic:"/ˈjuːtɪlaɪz/",pos:"v.",definition:"利用；使用；运用",example:"We must utilize all available resources.",level:3},
{word:"urbanization",phonetic:"/ˌɜːrbənɪˈzeɪʃn/",pos:"n.",definition:"城镇化；城市化",example:"Rapid urbanization causes many social issues.",level:3},
// ===== V =====
{word:"validate",phonetic:"/ˈvælɪdeɪt/",pos:"v.",definition:"验证；证实；使生效",example:"These findings validate the theory.",level:3},
{word:"vague",phonetic:"/veɪɡ/",pos:"adj.",definition:"模糊的；不明确的；朦胧的",example:"His instructions were vague and unclear.",level:2},
{word:"versatile",phonetic:"/ˈvɜːrsətl/",pos:"adj.",definition:"多才多艺的；多功能的",example:"She is a versatile and talented artist.",level:3},
{word:"virtually",phonetic:"/ˈvɜːrtʃuəli/",pos:"adv.",definition:"几乎；实际上；虚拟地",example:"This is virtually impossible.",level:2},
{word:"volatile",phonetic:"/ˈvɒlətl/",pos:"adj.",definition:"不稳定的；易挥发的；善变的",example:"The stock market is highly volatile.",level:3},
{word:"welfare",phonetic:"/ˈwelfeər/",pos:"n.",definition:"福利；幸福；福祉",example:"The government cares about public welfare.",level:2},
{word:"withstand",phonetic:"/wɪðˈstænd/",pos:"v.",definition:"经受住；抵御；承受",example:"The bridge can withstand heavy loads.",level:3},
{word:"yield",phonetic:"/jiːld/",pos:"v./n.",definition:"产生；屈服；产量",example:"The investment yielded good returns.",level:3},
// ===== 拓展词汇 Level 4 =====
{word:"abdicate",phonetic:"/ˈæbdɪkeɪt/",pos:"v.",definition:"退位；放弃（权力/责任）",example:"The king abdicated the throne.",level:4},
{word:"aberration",phonetic:"/ˌæbəˈreɪʃn/",pos:"n.",definition:"异常；偏差；失常行为",example:"The accident was an aberration.",level:4},
{word:"abstain",phonetic:"/əbˈsteɪn/",pos:"v.",definition:"戒除；弃权；回避",example:"She abstained from voting.",level:4},
{word:"accentuate",phonetic:"/əkˈsentʃueɪt/",pos:"v.",definition:"着重；强调；使突出",example:"The lighting accentuates the painting.",level:4},
{word:"accommodate",phonetic:"/əˈkɒmədeɪt/",pos:"v.",definition:"容纳；适应；迎合",example:"We can accommodate your request.",level:3},
{word:"affirmative",phonetic:"/əˈfɜːrmətɪv/",pos:"adj./n.",definition:"肯定的；确定的；赞成的回答",example:"She gave an affirmative response.",level:4},
{word:"aloof",phonetic:"/əˈluːf/",pos:"adj.",definition:"冷漠的；疏远的；保持距离的",example:"He remained aloof from the argument.",level:4},
{word:"ambivalent",phonetic:"/æmˈbɪvələnt/",pos:"adj.",definition:"矛盾的；态度不明确的",example:"She felt ambivalent about leaving.",level:4},
{word:"ameliorate",phonetic:"/əˈmiːliəreɪt/",pos:"v.",definition:"改善；改进；减轻",example:"Aid can ameliorate suffering.",level:4},
{word:"anarchy",phonetic:"/ˈænəki/",pos:"n.",definition:"无政府状态；混乱；无秩序",example:"The country fell into anarchy.",level:4},
{word:"antithesis",phonetic:"/ænˈtɪθəsɪs/",pos:"n.",definition:"对立；对立面；对照",example:"His actions are the antithesis of kindness.",level:4},
{word:"apathy",phonetic:"/ˈæpəθi/",pos:"n.",definition:"冷漠；漠然；缺乏兴趣",example:"Voter apathy is a serious problem.",level:4},
{word:"appease",phonetic:"/əˈpiːz/",pos:"v.",definition:"安抚；缓和；迎合",example:"The offer was meant to appease critics.",level:4},
{word:"articulate",phonetic:"/ɑːrˈtɪkjuleɪt/",pos:"v./adj.",definition:"清晰表达；关节的；有条理的",example:"She articulated her views clearly.",level:4},
{word:"assertion",phonetic:"/əˈsɜːrʃn/",pos:"n.",definition:"断言；声明；坚持",example:"His assertion was not backed by evidence.",level:4},
{word:"atrocity",phonetic:"/əˈtrɒsəti/",pos:"n.",definition:"暴行；凶残行为；极其残酷",example:"War atrocities shocked the world.",level:4},
{word:"audacious",phonetic:"/ɔːˈdeɪʃəs/",pos:"adj.",definition:"大胆的；无畏的；厚颜无耻的",example:"The plan was audacious but effective.",level:4},
{word:"augment",phonetic:"/ɔːɡˈment/",pos:"v.",definition:"增加；扩大；增强",example:"Technology can augment human capabilities.",level:4},
{word:"avert",phonetic:"/əˈvɜːrt/",pos:"v.",definition:"避免；转移（目光/注意力）",example:"Quick action averted disaster.",level:4},
{word:"axiom",phonetic:"/ˈæksiəm/",pos:"n.",definition:"公理；格言；自明之理",example:"It is an axiom that honesty is the best policy.",level:4},
{word:"benevolent",phonetic:"/bɪˈnevələnt/",pos:"adj.",definition:"慈善的；善意的；仁慈的",example:"The benevolent donor funded many schools.",level:4},
{word:"clandestine",phonetic:"/klænˈdestɪn/",pos:"adj.",definition:"秘密的；隐密的；偷偷摸摸的",example:"They held clandestine meetings.",level:4},
{word:"complacent",phonetic:"/kəmˈpleɪsnt/",pos:"adj.",definition:"自满的；得意的；漠然的",example:"Don't become complacent after success.",level:4},
{word:"concede",phonetic:"/kənˈsiːd/",pos:"v.",definition:"承认；让步；退让",example:"He conceded that the plan needed revision.",level:4},
{word:"condone",phonetic:"/kənˈdəʊn/",pos:"v.",definition:"宽恕；容忍；对…视而不见",example:"We cannot condone violence.",level:4},
{word:"contemplate",phonetic:"/ˈkɒntəmpleɪt/",pos:"v.",definition:"沉思；考虑；注视",example:"She contemplated her future options.",level:4},
{word:"convoluted",phonetic:"/ˈkɒnvəluːtɪd/",pos:"adj.",definition:"错综复杂的；晦涩难懂的",example:"The instructions were convoluted.",level:4},
{word:"credulous",phonetic:"/ˈkredjʊləs/",pos:"adj.",definition:"轻信的；易受骗的",example:"A credulous person believes everything.",level:4},
{word:"cynic",phonetic:"/ˈsɪnɪk/",pos:"n.",definition:"愤世嫉俗者；犬儒主义者",example:"Cynics doubt every politician's motives.",level:4},
{word:"deference",phonetic:"/ˈdefərəns/",pos:"n.",definition:"尊重；服从；顺从",example:"He acted in deference to his boss.",level:4},
{word:"demagogue",phonetic:"/ˈdeməɡɒɡ/",pos:"n.",definition:"煽动者；蛊惑人心的政客",example:"The demagogue exploited public fears.",level:4},
{word:"depravity",phonetic:"/dɪˈprævəti/",pos:"n.",definition:"堕落；道德败坏",example:"The novel explores human depravity.",level:4},
{word:"dichotomy",phonetic:"/daɪˈkɒtəmi/",pos:"n.",definition:"二分法；对立；一分为二",example:"There is a dichotomy between theory and practice.",level:4},
{word:"dilapidated",phonetic:"/dɪˈlæpɪdeɪtɪd/",pos:"adj.",definition:"破旧的；荒废的；年久失修的",example:"The building was dilapidated.",level:4},
{word:"discrepancy",phonetic:"/dɪˈskrepənsi/",pos:"n.",definition:"差异；不符；矛盾",example:"There is a discrepancy in the accounts.",level:4},
{word:"disdain",phonetic:"/dɪsˈdeɪn/",pos:"n./v.",definition:"鄙视；蔑视；不屑",example:"He looked at them with disdain.",level:4},
{word:"disparity",phonetic:"/dɪˈspærəti/",pos:"n.",definition:"不同；差异；不均等",example:"There is a wide disparity in wealth.",level:4},
{word:"dogma",phonetic:"/ˈdɒɡmə/",pos:"n.",definition:"教条；信条；教义",example:"He challenged the dogma of the church.",level:4},
{word:"elusive",phonetic:"/ɪˈluːsɪv/",pos:"adj.",definition:"难以捉摸的；逃避的；不易记住的",example:"Success was elusive for years.",level:4},
{word:"empathy",phonetic:"/ˈempəθi/",pos:"n.",definition:"共情；同理心；移情",example:"Good leaders show empathy.",level:3},
{word:"enigma",phonetic:"/ɪˈnɪɡmə/",pos:"n.",definition:"谜；神秘的人/事；难以理解的事物",example:"His behavior remains an enigma.",level:4},
{word:"ephemeral",phonetic:"/ɪˈfemərəl/",pos:"adj.",definition:"短暂的；昙花一现的；瞬息的",example:"Fame is often ephemeral.",level:4},
{word:"eradicate",phonetic:"/ɪˈrædɪkeɪt/",pos:"v.",definition:"根除；消灭；彻底铲除",example:"We must eradicate poverty.",level:4},
{word:"erroneous",phonetic:"/ɪˈrəʊniəs/",pos:"adj.",definition:"错误的；不正确的",example:"His assumption was erroneous.",level:4},
{word:"esoteric",phonetic:"/ˌesəˈterɪk/",pos:"adj.",definition:"深奥的；秘传的；小圈子的",example:"The book is too esoteric for beginners.",level:4},
{word:"exacerbate",phonetic:"/ɪɡˈzæsəbeɪt/",pos:"v.",definition:"使恶化；加重；激怒",example:"The delay exacerbated the problem.",level:4},
{word:"exemplify",phonetic:"/ɪɡˈzemplɪfaɪ/",pos:"v.",definition:"例证；成为…典范；例示",example:"This project exemplifies innovation.",level:4},
{word:"expedient",phonetic:"/ɪkˈspiːdiənt/",pos:"adj./n.",definition:"权宜的；方便的；权宜之计",example:"It was an expedient solution.",level:4},
{word:"exuberant",phonetic:"/ɪɡˈzjuːbərənt/",pos:"adj.",definition:"充满活力的；生气勃勃的；茂盛的",example:"She is exuberant and full of energy.",level:4},
{word:"facade",phonetic:"/fəˈsɑːd/",pos:"n.",definition:"（建筑）正面；虚伪的外表；幌子",example:"His cheerfulness was just a facade.",level:4},
{word:"fallacy",phonetic:"/ˈfæləsi/",pos:"n.",definition:"谬误；错误的想法；虚假",example:"That argument is a common fallacy.",level:4},
{word:"fervent",phonetic:"/ˈfɜːrvənt/",pos:"adj.",definition:"热烈的；热情的；炽热的",example:"She was a fervent supporter of the cause.",level:4},
{word:"fluctuation",phonetic:"/ˌflʌktʃuˈeɪʃn/",pos:"n.",definition:"波动；涨落；起伏",example:"Price fluctuations affect the economy.",level:3},
{word:"formidable",phonetic:"/fɔːˈmɪdəbl/",pos:"adj.",definition:"强大的；可怕的；令人敬畏的",example:"She is a formidable opponent.",level:4},
{word:"futile",phonetic:"/ˈfjuːtaɪl/",pos:"adj.",definition:"无用的；无效的；徒劳的",example:"All efforts proved futile.",level:4},
{word:"gregarious",phonetic:"/ɡrɪˈɡeəriəs/",pos:"adj.",definition:"爱社交的；合群的；群居的",example:"Dolphins are gregarious animals.",level:4},
{word:"hamper",phonetic:"/ˈhæmpər/",pos:"v./n.",definition:"阻碍；妨碍；大篮子",example:"Bad weather hampered rescue efforts.",level:4},
{word:"herald",phonetic:"/ˈherəld/",pos:"v./n.",definition:"预示；宣布；先驱",example:"Spring heralds new beginnings.",level:4},
{word:"homogeneous",phonetic:"/ˌhɒməˈdʒiːniəs/",pos:"adj.",definition:"同质的；同类的；均匀的",example:"The population was largely homogeneous.",level:4},
{word:"hypocritical",phonetic:"/ˌhɪpəˈkrɪtɪkl/",pos:"adj.",definition:"虚伪的；伪善的",example:"It would be hypocritical to pretend otherwise.",level:4},
{word:"idealize",phonetic:"/aɪˈdiːəlaɪz/",pos:"v.",definition:"理想化；把…理想化",example:"We often idealize the past.",level:4},
{word:"idiosyncratic",phonetic:"/ˌɪdiəsɪŋˈkrætɪk/",pos:"adj.",definition:"特异的；特殊的；有个人特色的",example:"His idiosyncratic style is recognizable.",level:4},
{word:"impede",phonetic:"/ɪmˈpiːd/",pos:"v.",definition:"阻碍；妨碍；阻止",example:"Lack of funding impeded progress.",level:4},
{word:"implication",phonetic:"/ˌɪmplɪˈkeɪʃn/",pos:"n.",definition:"含义；暗示；牵连",example:"The implications of this decision are serious.",level:3},
{word:"inadvertent",phonetic:"/ˌɪnədˈvɜːrtənt/",pos:"adj.",definition:"无意的；疏忽的；非故意的",example:"It was an inadvertent mistake.",level:4},
{word:"incessant",phonetic:"/ɪnˈsesnt/",pos:"adj.",definition:"不断的；持续不停的",example:"The incessant noise was unbearable.",level:4},
{word:"incite",phonetic:"/ɪnˈsaɪt/",pos:"v.",definition:"煽动；激起；刺激",example:"The speech incited public anger.",level:4},
{word:"incongruous",phonetic:"/ɪnˈkɒŋɡruəs/",pos:"adj.",definition:"不协调的；不相称的；不一致的",example:"His casual attire seemed incongruous.",level:4},
{word:"indifferent",phonetic:"/ɪnˈdɪfrənt/",pos:"adj.",definition:"冷漠的；不关心的；一般的",example:"She seemed indifferent to the outcome.",level:3},
{word:"indulge",phonetic:"/ɪnˈdʌldʒ/",pos:"v.",definition:"沉迷；纵容；迁就",example:"Don't indulge in unhealthy habits.",level:3},
{word:"inept",phonetic:"/ɪˈnept/",pos:"adj.",definition:"无能的；不称职的；笨拙的",example:"The inept manager caused chaos.",level:4},
{word:"infer",phonetic:"/ɪnˈfɜːr/",pos:"v.",definition:"推断；推论；暗示",example:"We can infer his intention from his actions.",level:3},
{word:"ingenuity",phonetic:"/ˌɪndʒɪˈnjuːəti/",pos:"n.",definition:"心灵手巧；独创性；机巧",example:"The design shows great ingenuity.",level:4},
{word:"innate",phonetic:"/ɪˈneɪt/",pos:"adj.",definition:"天生的；固有的；先天的",example:"Curiosity is an innate human trait.",level:4},
{word:"instigate",phonetic:"/ˈɪnstɪɡeɪt/",pos:"v.",definition:"激起；煽动；发起",example:"He instigated the conflict.",level:4},
{word:"integrity",phonetic:"/ɪnˈteɡrəti/",pos:"n.",definition:"诚信；正直；完整性",example:"A leader must have integrity.",level:3},
{word:"intrepid",phonetic:"/ɪnˈtrepɪd/",pos:"adj.",definition:"无畏的；勇敢的；大胆的",example:"The intrepid explorer climbed Mount Everest.",level:4},
{word:"inundate",phonetic:"/ˈɪnʌndeɪt/",pos:"v.",definition:"淹没；使不知所措；压倒",example:"They were inundated with applications.",level:4},
{word:"jeopardize",phonetic:"/ˈdʒepərdaɪz/",pos:"v.",definition:"危及；损害；使处于危险",example:"Don't jeopardize your health.",level:4},
{word:"juxtapose",phonetic:"/ˌdʒʌkstəˈpəʊz/",pos:"v.",definition:"并置；对比；将…并排放置",example:"The article juxtaposes two very different views.",level:4},
{word:"latent",phonetic:"/ˈleɪtnt/",pos:"adj.",definition:"潜在的；隐藏的；休眠的",example:"He has latent artistic talent.",level:4},
{word:"laud",phonetic:"/lɔːd/",pos:"v.",definition:"赞美；称颂；表扬",example:"Critics lauded the film.",level:4},
{word:"lucid",phonetic:"/ˈluːsɪd/",pos:"adj.",definition:"清晰的；易懂的；神志清醒的",example:"She gave a lucid explanation.",level:4},
{word:"magnanimous",phonetic:"/mæɡˈnænɪməs/",pos:"adj.",definition:"宽宏大量的；慷慨的；高尚的",example:"The leader was magnanimous in victory.",level:4},
{word:"malicious",phonetic:"/məˈlɪʃəs/",pos:"adj.",definition:"恶意的；蓄意的；怀恨的",example:"The malicious rumor damaged his reputation.",level:4},
{word:"meticulous",phonetic:"/məˈtɪkjələs/",pos:"adj.",definition:"一丝不苟的；谨慎的；过分仔细的",example:"She is meticulous in her work.",level:4},
{word:"mitigate",phonetic:"/ˈmɪtɪɡeɪt/",pos:"v.",definition:"减轻；缓解；缓和",example:"Trees help mitigate climate change.",level:4},
{word:"mundane",phonetic:"/mʌnˈdeɪn/",pos:"adj.",definition:"平凡的；普通的；世俗的",example:"He found the work mundane.",level:4},
{word:"naïve",phonetic:"/naɪˈiːv/",pos:"adj.",definition:"天真的；幼稚的；轻信的",example:"It would be naïve to trust everyone.",level:3},
{word:"nonchalant",phonetic:"/ˈnɒnʃələnt/",pos:"adj.",definition:"漫不经心的；冷静的；若无其事的",example:"She was nonchalant about the criticism.",level:4},
{word:"obscure",phonetic:"/əbˈskjʊər/",pos:"adj./v.",definition:"不出名的；模糊的；使模糊",example:"The meaning is obscure.",level:3},
{word:"obsolete",phonetic:"/ˌɒbsəˈliːt/",pos:"adj.",definition:"废弃的；过时的；不再使用的",example:"This technology is now obsolete.",level:3},
{word:"omnipotent",phonetic:"/ɒmˈnɪpətənt/",pos:"adj.",definition:"全能的；无所不能的",example:"No leader is omnipotent.",level:4},
{word:"oppressive",phonetic:"/əˈpresɪv/",pos:"adj.",definition:"压迫性的；沉重的；令人难受的",example:"The heat was oppressive.",level:4},
{word:"ostracize",phonetic:"/ˈɒstrəsaɪz/",pos:"v.",definition:"排斥；排挤；使流放",example:"He was ostracized by his peers.",level:4},
{word:"painstaking",phonetic:"/ˈpeɪnzteɪkɪŋ/",pos:"adj.",definition:"辛苦的；勤勉的；精心的",example:"The restoration required painstaking work.",level:4},
{word:"palpable",phonetic:"/ˈpælpəbl/",pos:"adj.",definition:"可感知的；明显的；明确的",example:"The tension in the room was palpable.",level:4},
{word:"pedantic",phonetic:"/pɪˈdæntɪk/",pos:"adj.",definition:"迂腐的；卖弄学问的；过于注重细节的",example:"His pedantic lecture bored everyone.",level:4},
{word:"perfunctory",phonetic:"/pərˈfʌŋktəri/",pos:"adj.",definition:"敷衍的；草率的；例行公事的",example:"She gave a perfunctory nod.",level:4},
{word:"peripheral",phonetic:"/pəˈrɪfərəl/",pos:"adj.",definition:"外围的；次要的；周边的",example:"This issue is peripheral to our main concern.",level:4},
{word:"pertinent",phonetic:"/ˈpɜːrtɪnənt/",pos:"adj.",definition:"相关的；恰当的；切题的",example:"Please ask pertinent questions.",level:4},
{word:"plausible",phonetic:"/ˈplɔːzɪbl/",pos:"adj.",definition:"看似合理的；貌似可信的",example:"The theory seems plausible.",level:4},
{word:"polarization",phonetic:"/ˌpəʊlərɪˈzeɪʃn/",pos:"n.",definition:"两极化；极化；对立",example:"Political polarization has increased.",level:4},
{word:"pragmatic",phonetic:"/præɡˈmætɪk/",pos:"adj.",definition:"务实的；实用主义的；实际的",example:"A pragmatic approach works best.",level:4},
{word:"precarious",phonetic:"/prɪˈkeəriəs/",pos:"adj.",definition:"不稳定的；危险的；不确定的",example:"Their situation was precarious.",level:4},
{word:"precipitate",phonetic:"/prɪˈsɪpɪteɪt/",pos:"v./adj.",definition:"促成；沉淀；仓促的",example:"The crisis precipitated change.",level:4},
{word:"prerogative",phonetic:"/prɪˈrɒɡətɪv/",pos:"n.",definition:"特权；专有权利",example:"It's the president's prerogative.",level:4},
{word:"prescient",phonetic:"/ˈpresiənt/",pos:"adj.",definition:"有先见之明的；能预知的",example:"His prescient warning proved correct.",level:4},
{word:"prodigious",phonetic:"/prəˈdɪdʒəs/",pos:"adj.",definition:"惊人的；巨大的；大量的",example:"She has a prodigious memory.",level:4},
{word:"proliferate",phonetic:"/prəˈlɪfəreɪt/",pos:"v.",definition:"激增；扩散；迅速发展",example:"Social media has proliferated rapidly.",level:4},
{word:"provocative",phonetic:"/prəˈvɒkətɪv/",pos:"adj.",definition:"挑衅的；刺激的；激起争议的",example:"His remarks were deliberately provocative.",level:4},
{word:"prudent",phonetic:"/ˈpruːdnt/",pos:"adj.",definition:"谨慎的；精明的；有远见的",example:"A prudent investor diversifies risks.",level:4},
{word:"punitive",phonetic:"/ˈpjuːnɪtɪv/",pos:"adj.",definition:"惩罚性的；严厉的",example:"The punitive measures shocked many.",level:4},
{word:"putative",phonetic:"/ˈpjuːtətɪv/",pos:"adj.",definition:"公认的；推定的；假定的",example:"He is the putative leader.",level:4},
{word:"quandary",phonetic:"/ˈkwɒndri/",pos:"n.",definition:"困境；困惑；左右为难",example:"She was in a quandary about what to do.",level:4},
{word:"querulous",phonetic:"/ˈkwerʊləs/",pos:"adj.",definition:"爱抱怨的；牢骚满腹的",example:"The querulous customer complained constantly.",level:4},
{word:"rampant",phonetic:"/ˈræmpənt/",pos:"adj.",definition:"猖獗的；泛滥的；不可控制的",example:"Corruption was rampant.",level:4},
{word:"reconcile",phonetic:"/ˈrekənsaɪl/",pos:"v.",definition:"调和；使和解；使接受",example:"She tried to reconcile the two parties.",level:4},
{word:"rectify",phonetic:"/ˈrektɪfaɪ/",pos:"v.",definition:"纠正；矫正；改正",example:"We must rectify the mistakes.",level:4},
{word:"relentless",phonetic:"/rɪˈlentləs/",pos:"adj.",definition:"不间断的；坚持不懈的；冷酷无情的",example:"She showed relentless determination.",level:4},
{word:"resilience",phonetic:"/rɪˈzɪliəns/",pos:"n.",definition:"恢复力；弹力；韧性",example:"Communities need resilience in crises.",level:3},
{word:"reticent",phonetic:"/ˈretɪsnt/",pos:"adj.",definition:"不爱说话的；沉默寡言的",example:"He was reticent about his past.",level:4},
{word:"rhetoric",phonetic:"/ˈretərɪk/",pos:"n.",definition:"修辞；夸夸其谈；雄辩术",example:"The speech was full of rhetoric but lacking substance.",level:4},
{word:"rigorous",phonetic:"/ˈrɪɡərəs/",pos:"adj.",definition:"严格的；严密的；严苛的",example:"Scientific research requires rigorous methods.",level:4},
{word:"rudimentary",phonetic:"/ˌruːdɪˈmentri/",pos:"adj.",definition:"基本的；初步的；不完善的",example:"She has a rudimentary knowledge of French.",level:4},
{word:"salient",phonetic:"/ˈseɪliənt/",pos:"adj.",definition:"显著的；突出的；最重要的",example:"What are the salient points?",level:4},
{word:"sanctimonious",phonetic:"/ˌsæŋktɪˈməʊniəs/",pos:"adj.",definition:"假装虔诚的；道貌岸然的",example:"His sanctimonious attitude annoyed others.",level:4},
{word:"scrutinize",phonetic:"/ˈskruːtɪnaɪz/",pos:"v.",definition:"仔细审查；详细检查；细察",example:"The committee will scrutinize the accounts.",level:4},
{word:"speculate",phonetic:"/ˈspekjuleɪt/",pos:"v.",definition:"推测；猜测；投机",example:"Economists speculate about growth rates.",level:3},
{word:"sporadic",phonetic:"/spəˈrædɪk/",pos:"adj.",definition:"零星的；不时发生的；断断续续的",example:"There were sporadic protests.",level:4},
{word:"static",phonetic:"/ˈstætɪk/",pos:"adj.",definition:"静止的；不变的；静态的",example:"The situation remained static.",level:3},
{word:"stigmatize",phonetic:"/ˈstɪɡmətaɪz/",pos:"v.",definition:"污名化；使蒙羞；给…打上烙印",example:"Mental illness is often stigmatized.",level:4},
{word:"stoic",phonetic:"/ˈstəʊɪk/",pos:"adj./n.",definition:"坚忍的；忍受的；斯多葛主义者",example:"She maintained a stoic demeanor.",level:4},
{word:"stringent",phonetic:"/ˈstrɪndʒənt/",pos:"adj.",definition:"严格的；严厉的；严苛的",example:"Stringent measures are needed.",level:4},
{word:"subjugate",phonetic:"/ˈsʌbdʒʊɡeɪt/",pos:"v.",definition:"征服；压制；使顺从",example:"The empire subjugated many peoples.",level:4},
{word:"superficial",phonetic:"/ˌsuːpərˈfɪʃl/",pos:"adj.",definition:"肤浅的；浅显的；表面的",example:"The analysis was too superficial.",level:3},
{word:"superfluous",phonetic:"/suːˈpɜːrfluəs/",pos:"adj.",definition:"多余的；过剩的；不必要的",example:"Remove superfluous details from the report.",level:4},
{word:"susceptible",phonetic:"/səˈseptɪbl/",pos:"adj.",definition:"易受影响的；易受感染的；敏感的",example:"Children are susceptible to infections.",level:4},
{word:"taciturn",phonetic:"/ˈtæsɪtɜːrn/",pos:"adj.",definition:"沉默寡言的；不爱说话的",example:"He was taciturn by nature.",level:4},
{word:"tangible",phonetic:"/ˈtændʒɪbl/",pos:"adj.",definition:"切实的；有形的；可感知的",example:"We need tangible results.",level:3},
{word:"tenacious",phonetic:"/tɪˈneɪʃəs/",pos:"adj.",definition:"顽强的；坚持不懈的；牢固的",example:"Her tenacious spirit helped her succeed.",level:4},
{word:"tentative",phonetic:"/ˈtentətɪv/",pos:"adj.",definition:"试探性的；暂时的；不确定的",example:"We made tentative plans.",level:3},
{word:"trepidation",phonetic:"/ˌtrepɪˈdeɪʃn/",pos:"n.",definition:"忧虑；惶恐；战战兢兢",example:"She approached the interview with trepidation.",level:4},
{word:"truncate",phonetic:"/trʌŋˈkeɪt/",pos:"v.",definition:"截断；缩短；砍断末端",example:"The long speech was truncated.",level:4},
{word:"ubiquitous",phonetic:"/juːˈbɪkwɪtəs/",pos:"adj.",definition:"无处不在的；普遍存在的",example:"Smartphones have become ubiquitous.",level:4},
{word:"unprecedented",phonetic:"/ʌnˈpresɪdentɪd/",pos:"adj.",definition:"空前的；前所未有的；无先例的",example:"The flood was unprecedented.",level:3},
{word:"unravel",phonetic:"/ˌʌnˈrævl/",pos:"v.",definition:"解开；阐明；瓦解",example:"Scientists are unraveling the mystery of DNA.",level:4},
{word:"vacillate",phonetic:"/ˈvæsɪleɪt/",pos:"v.",definition:"摇摆不定；犹豫不决",example:"She vacillated between the two choices.",level:4},
{word:"venerate",phonetic:"/ˈvenəreɪt/",pos:"v.",definition:"崇拜；尊重；敬重",example:"The community venerated the elder.",level:4},
{word:"verbose",phonetic:"/vɜːˈbəʊs/",pos:"adj.",definition:"冗长的；唠叨的；废话连篇的",example:"His report was verbose and unclear.",level:4},
{word:"vigilant",phonetic:"/ˈvɪdʒɪlənt/",pos:"adj.",definition:"警觉的；警惕的；警戒的",example:"Stay vigilant at all times.",level:3},
{word:"vindicate",phonetic:"/ˈvɪndɪkeɪt/",pos:"v.",definition:"证明…正确；为…辩护；雪…冤",example:"The verdict vindicated him.",level:4},
{word:"virulent",phonetic:"/ˈvɪrʊlənt/",pos:"adj.",definition:"剧毒的；恶毒的；极有害的",example:"The virulent virus spread quickly.",level:4},
{word:"wary",phonetic:"/ˈweəri/",pos:"adj.",definition:"谨慎的；警觉的；小心翼翼的",example:"Be wary of strangers.",level:3},
{word:"wield",phonetic:"/wiːld/",pos:"v.",definition:"行使；挥舞；使用（权力/武器）",example:"The senator wields considerable power.",level:4},
{word:"zealous",phonetic:"/ˈzeləs/",pos:"adj.",definition:"热心的；热情的；狂热的",example:"She was zealous in her campaign work.",level:4},
];

// ====== 导出词库信息 ======
const VOCAB_INFO = {
  total: KAOYAN_WORDS.length,
  levels: {
    1: KAOYAN_WORDS.filter(w => w.level === 1).length,
    2: KAOYAN_WORDS.filter(w => w.level === 2).length,
    3: KAOYAN_WORDS.filter(w => w.level === 3).length,
    4: KAOYAN_WORDS.filter(w => w.level === 4).length,
  }
};
console.log(`词库加载完成：共 ${VOCAB_INFO.total} 词`);
